<ol class="breadcrumb">
	<li><a href="<?php echo $this->url("home");?>">Home</a></li>
	<li><a href='<?php echo $this->url('about') ?>'>About Us</a></li>
	<li class='active'>Company Philosophy</li>
</ol>
<br>

<div class="whole-body clearfix">
	<div class="col-md-3">
		<?php echo $this->partial("application/partial/_about_us_nav")?>
	</div>
	
	<div class='col-md-9 sothyka-about-box '>
		<div class='sothyka-about'>
			<blockquote>
				<h3>
					Because… home is the psychological center of everybody;
					whether it is a time of happiness or distress, home is always a mind-resting place for family members
				</h3>
			</blockquote>
			
			<p class='text-muted'>
				More than 38 years ago, Mr. Prawat Techamahaphant, a highly committed person at the age of 57, made a pledge to make the dreams of getting access to high quality building and construction products become a reality. So began the very strong pace of the brand "SOTHYKA". This was the starting point of our 'Fibre Composite Solutions' (FCS) technology and its dynamic, non-stop development ever since.
			</p>
			<p class='text-muted'>
				In 1974, The Thai Olympic Fibre-Cement Co., Ltd., was founded with the aim of producing fibre cement roofing under the brand "Ha Huang" (meaning 'five circles' in Thai), which served as the solid foundation and the source for nurturing the commitment, inspiration and skills among staff from generation to generation. These efforts contributed to making the dreams of Thai people come true.
			</p>
			<p class='text-muted'>	
				The last 38 years of commitment has seen significant growth. The company has expanded to a number of plants serving Thailand and the Asian region and it has taken part in ensuring growing quality of life not only for Thai society but also for the region.
				The company has grown significantly under the brand "SOTHYKA", which is not limited only to roofing but has extended its range to fiber cement materials for walling, ceiling, flooring and furniture.
			</p>
			<p class='text-center'><img src='<?php echo $this->basepath()?>/img/aboutus/img-tree-philosophy.png'></p>
		</div>
	</div>	
</div>