<ol class="breadcrumb">
	<li><a href="<?php echo $this->url("home");?>">Home</a></li>
	<li class='active'>Contact <i>Sothyka</i></li>
</ol>
<br>
<div class="whole-body clearfix">
	<div class="col-md-4 sothyka-contact-address">
		<div class="list-group sothyka-list-group">
			<h3>Contact Information</h3>
			<p><strong>SOTHYKA SHERA</strong></p>
			<p><span>Address: </span> 283, National Road 1 Prek Cheung Prom Village, Vealsbov Quater, Meanchey District, Phnom Penh City, Cambodia</p>
			<p><span>Tel: (855) 12 66 33 92</span></p>			
				
			<p><span>Email: </span> sothyka@sothykashera.com</p>	
		</div>	
		
		<p><img src='<?php echo $this->basepath()?>/img/contact/map.png' width='350px'>	</p>
		<p><strong>Contact to careers with SOTHYKA</strong></p>
		<p><span>Email: </span> sothyka@sothykashera.com</p>	
	</div>
	
	<div class='col-md-8 sothyka-contact catalog-box'>
		<h3>Contact Form</h3>		
		<form class="form-horizontal" role="form">
		  <div class="form-group">
		    <label for="firstName" class="col-sm-2 control-label">First Name</label>
		    <div class="col-sm-6">
		      <input type="text" class="form-control" id="inputFirstName" placeholder="Frist Name">
		    </div>		    
		  </div>
		  
		  <div class="form-group">
		  	<label for="lastName" class="col-sm-2 control-label">Last Name</label>
		    <div class="col-sm-6">
		      <input type="text" class="form-control" id="inputLastName" placeholder="Last Name">
		    </div>
		   </div>
		   
		   <div class="form-group">
		  	<label for="email" class="col-sm-2 control-label">Email</label>
		    <div class="col-sm-6">
		      <input type="text" class="form-control" id="email" placeholder="Email">
		    </div>
		   </div>
		   
		   <div class="form-group">
		  	<label for="tel" class="col-sm-2 control-label">Telephone</label>
		    <div class="col-sm-6">
		      <input type="text" class="form-control" id="tel" placeholder="Telephone">
		    </div>
		   </div>
		   
		   <div class="form-group">
		  	<label for="company" class="col-sm-2 control-label">Company</label>
		    <div class="col-sm-6">
		      <input type="text" class="form-control" id="company" placeholder="Company">
		    </div>
		   </div>
		   
		   <div class="form-group">
		  	<label for="company" class="col-sm-2 control-label">Detail</label>
		    <div class="col-sm-6">
		      <textarea class="form-control" rows="3" placeholder='Detail'></textarea>
		    </div>
		   </div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
			      <button type="submit" class="btn btn-success">SUBMIT</button>
			    </div>
			</div>		  
		</form>
		
		<div class='col-md-4'></div>
	</div>
</div>

<br>
<br>