<div class="box-white clearfix border-radius-5 margin-10-0 font-13">

   <div class="col-md-12">
       <div class="row">
           <div class="col-md-12">
               <h4>Profile Information</h4>
               <hr>
           </div>
       </div>
       <div class="row">
           <div class="col-md-3"><label>First Name</label> <input type="text" class="form-control"> </div>
           <div class="col-md-3"><label>Last Name</label><input type="text" class="form-control"></div></div>
       <div class="row">
           <div class="col-md-3"><label>Gender</label><select class="form-control"><option>Male</option><option>Female</option></select></div>
           <div class="col-md-3"><label>Email</label><input type="text" class="form-control"></div>
       </div>
       <div class="row">
           <div class="col-md-3"><label>User Name</label><input type="text" class="form-control"></div>
           <div class="col-md-3"><label>Password </label><input type="text" class="form-control"></div>
           <div class="col-md-3"><label>Re-Password </label><input type="text" class="form-control"></div>
       </div>

       <div class="row">
           <div class="col-md-9"><label>Information</label><textarea class="form-control"></textarea></div>
       </div>

       <div class="row">
           <div class="col-md-6">
                <h4>How do you intend in employer or seeker?</h4>
                <select class="form-control"><option>Select</option><option>Employer</option><option>Seeker</option></select>

           </div>

       </div>
       <div class="company-info">
           <div class="row">
               <div class="col-md-12">
                   <h4 class="">Company Information</h4>
                   <hr>
               </div>
           </div>

           <div class="row">
               <div class="col-md-3"><label>Company Name</label><input type="text" class="form-control"></div>
               <div class="col-md-3"><label>Contact Name</label><input type="text" class="form-control"></div>
               <div class="col-md-3"> <label>Phone</label><input type="text" class="form-control"></div>
           </div>
           <div class="row">
               <div class="col-md-3"><label>Email</label><input type="text" class="form-control"></div>
               <div class="col-md-3"><label>Website</label><input type="text" class="form-control"></div>
               <div class="col-md-3"><label>Service Phone</label><input type="text" class="form-control"></div>
           </div>
           <div class="row">
               <div class="col-md-9"><label>Address</label><textarea class="form-control"></textarea></div>
           </div>
           <div class="row">
               <div class="col-md-9"><label>Company Information</label><textarea class="form-control"></textarea></div>
           </div>
       </div>
       <br>
        <div class="row">
           <div class="col-md-12">
               <button class="btn btn-success col-md-2">Submit</button>
           </div>
       </div>
       <br>
   </div>
    <br><br>
</div>
