<?php
$this->headLink ()->prependStylesheet ( $this->basePath () . '/css/bootstrap-wysihtml5.css');
$this->headScript ()->prependFile ( $this->basePath () . '/js/bootstrap-wysihtml5.js');
$this->headScript ()->prependFile ( $this->basePath () . '/js/wysihtml5-0.3.0.js');
?>
<?php
    $form = $this->form;
    echo $this->form()->openTag($form);
    $gender = array("Male"=>"Male","Female"=>"Female");
    $optionRegister = array(1=>"Seeker",2=>"Employer");
    $option = $this->option; // 1 mean seeker 2 mean employer
?>
<div class="box-white clearfix border-radius-5 margin-10-0 font-13">

   <div class="col-md-12">
       <div class="row">
           <div class="col-md-12">
               <h4>Profile Information</h4>
               <hr>
           </div>
       </div>
       <div class="row">
           <div class="col-md-6">
               <div class="padding-10-0 font-13">How do you intend in employer or seeker?</div>
               <?php echo $this->formselect($form->get('option_register')->setAttributes(array('class'=>'form-control opt-register','options'=>$optionRegister,'value'=>$option)))?>
           </div>
       </div>
       <br>
       <div class="row">
           <div class="col-md-3"><label>First Name</label> <?php echo $this->formrow($form->get('first_name')->setAttributes(array('class'=>'form-control')))?></div>
           <div class="col-md-3"><label>Last Name</label><?php echo $this->formrow($form->get('last_name')->setAttributes(array('class'=>'form-control')))?></div>
           <div class="col-md-3"><label>Phone</label><?php echo $this->formrow($form->get('user_phone')->setAttributes(array('class'=>'form-control')))?></div>
       </div>
       <br>
       <div class="row">
           <div class="col-md-3"><label>Gender</label><?php echo $this->formselect($form->get('gender')->setAttributes(array('class'=>'form-control','options'=>$gender)))?></div>
           <div class="col-md-3"><label>Personal Email</label><?php echo $this->formrow($form->get('user_email')->setAttributes(array('class'=>'form-control')))?></div>
       </div>
       <br>
       <div class="row">
           <div class="col-md-3"><label>User Name</label><?php echo $this->formrow($form->get('user_name')->setAttributes(array('class'=>'form-control')))?></div>
           <div class="col-md-3"><label>Password </label><?php echo $this->formrow($form->get('password')->setAttributes(array('class'=>'form-control')))?></div>
           <div class="col-md-3"><label>Re-Password </label><?php echo $this->formrow($form->get('repassword')->setAttributes(array('class'=>'form-control')))?></div>
       </div>
       <br>
       <div class="row user-info <?php if($option==2){echo "hidden";}else{echo "";}?>">
           <div class="col-md-9"><label>User Address</label><?php echo $this->formtextarea($form->get('user_address')->setAttributes(array('class'=>'form-control')))?></div>
       </div>
       <br>
       <div class="row user-info <?php if($option==2){echo "hidden";}else{echo "";}?>">
           <div class="col-md-9"><label>User Information</label><?php echo $this->formtextarea($form->get('user_info')->setAttributes(array('class'=>'form-control')))?></div>
       </div>


       <div class="company-info <?php if($option==1){echo "hidden";}else{echo "";}?>">
           <div class="row">
               <div class="col-md-12">
                   <h4 class="">Company Information</h4>
                   <hr>
               </div>
           </div>
           <div class="row">
               <div class="col-md-3">
                   <?php echo $this->formrow($form->get('images')->setAttributes(array('class'=>'form-control')));?>
                   <?php echo $this->error;?>
               </div>
               <div class="col-md-3"><label>Company Name</label><?php echo $this->formrow($form->get('com_name')->setAttributes(array('class'=>'form-control')))?></div>
<!--               <div class="col-md-3"><label>Contact Name</label>--><?php //echo $this->formrow($form->get('contact_name')->setAttributes(array('class'=>'form-control')))?><!--</div>-->
               <div class="col-md-3"> <label>Company Phone</label><?php echo $this->formrow($form->get('com_phone')->setAttributes(array('class'=>'form-control')))?></div>
           </div>
           <br>
           <div class="row">
               <div class="col-md-3"><label>Company Email</label><?php echo $this->formrow($form->get('com_email')->setAttributes(array('class'=>'form-control')))?></div>
               <div class="col-md-3"><label>Website</label><?php echo $this->formrow($form->get('com_website')->setAttributes(array('class'=>'form-control')))?></div>
               <div class="col-md-3"><label>Working Time</label><?php echo $this->formrow($form->get('com_service_phone')->setAttributes(array('class'=>'form-control')))?></div>
           </div>
           <br>
           <div class="row">
               <div class="col-md-9"><label>Company Address</label><?php echo $this->formtextarea($form->get('com_address')->setAttributes(array('class'=>'form-control')))?></div>
           </div>
           <br>
           <div class="row">
               <div class="col-md-9"><label>Company Information</label><?php echo $this->formtextarea($form->get('com_info')->setAttributes(array('class'=>'form-control')))?></div>
           </div>

       </div>
       <br>
        <div class="row">
           <div class="col-md-9 text-right">
               <button type="submit" class="btn btn-success">Submit</button>
           </div>
       </div>
       <br>
   </div>
    <br><br>
</div>
<?php echo $this->form()->closeTag();?>
<script>
    $(function(){
        $('.opt-register').change(function(){
            opt = $(this).val();
            if(opt==1){
                $('.company-info').addClass('hidden');
                $('.user-info').removeClass('hidden');
            }else{
                $('.company-info').removeClass('hidden');
                $('.user-info').addClass('hidden');
            }
        });
        $('textarea').wysihtml5();
    });

</script>