<div class="clearfix">
    <div class="col-md-12">
        <div class="clearfix">
            <label class="col-md-4"><b>Highest Qualification</b></label>
            <span>: Bachelor Degree</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Latest Career Level</b></label>
            <span>: Manager <Manager></Manager></span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Year of Experience</b></label>
            <span>: 6 </span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Lastest Position</b></label>
            <span>: Project Manager</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Latest Job Function</b></label>
            <span>: Information Technology</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Latest Job Industry</b></label>
            <span>: Information Technology</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Lasest Salary</b></label>
            <span>: $ 850</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Address</b></label>
            <span>: #59Cz, Street 150z, Sangkat Psa Depot II, Khan Toul Kork, Phnom Penh, Cambodia</span>
        </div>
    </div>
</div>