<?php
/**
 * Created by PhpStorm.
 * User: dimang12
 * Date: 11/21/14
 * Time: 8:21 PM
 */
?>
<div class="list-group">
    <a href="<?php echo $this->basepath();?>/resume/general" class="list-group-item <?php if($this->curPage == "General") echo "active" ?>">
        General Information
    </a>
    <a href="<?php echo $this->basepath();?>/resume/careerprofile" class="list-group-item <?php if($this->curPage == "Career profile") echo "active" ?> ">Career Profile</a>
    <a href="<?php echo $this->basepath();?>/resume/preference" class="list-group-item <?php if($this->curPage == "Job preference") echo "active" ?>">Job Preference</a>
    <a href="<?php echo $this->basepath();?>/resume/education" class="list-group-item <?php if($this->curPage == "Educations") echo "active" ?>">Educations</a>
    <a href="<?php echo $this->basepath();?>/resume/experience" class="list-group-item <?php if($this->curPage == "Experiences") echo "active" ?>">Experiences</a>
    <a href="<?php echo $this->basepath();?>/resume/skill" class="list-group-item <?php if($this->curPage == "Skills") echo "active" ?>">Skills</a>
</div>