	<?php 
	$sm = $this->getHelperPluginManager ()->getServiceLocator ();
	$routeMatch = $sm->get ( 'Application' )->getMvcEvent ()->getRouteMatch ();
	$router = $routeMatch->getMatchedRouteName();
	if($router != 'login' && $router != 'member' && $router != 'seeker'):
	?>
	<div class="navbar navbar-inverse navbar-fixed-top bg-gradient-light-gray" style="height: 1px;border:none;background: #E5E5E5;">
		<div class="container">
            <div class="col-md-10 col-md-offset-1">
                <div class="navbar-header" style="border:none">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target=".navbar-collapse">
                        <span class="sr-only"></span> <span
                            class="icon-bar"></span> <span class="icon-bar"></span> <span
                            class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('dashboard')?>"></a>

                </div>
                <div class="navbar-collapse collapse" style="margin-right: 40px;height: 48px;">

                    <form class="navbar-form navbar-right"></form>
                </div>
            </div>
		</div>
        <div class="header-bottom text-right">
            <div class="container">
                <div class="col-md-10 col-md-offset-1">

                    <ul class="">
                        <li><a href='<?php echo $this->basepath()?>' target=_blank><span class='glyphicon glyphicon-globe'></span> View Site</a></li>
                        <li class='i1' data-toggle="tooltip" data-placement="bottom" title="LOGOUT"><a class="color-red" href="<?php echo $this->basepath()?>/logout"><span class='glyphicon glyphicon-user'></span><span> Logout</span></a></li>
                    </ul>

                </div>
            </div>
        </div>
	</div>
	<?php endif ?>
