<?php
/**
 * Created by PhpStorm.
 * User: dimang12
 * Date: 12/28/14
 * Time: 1:24 PM
 */
$e = $this->detail;
?>

<div class="row-fluid box-admin-main">
    <div class="col-md-2 padding-left-0">
        <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    </div>
    <div class='col-md-10 box-admin-right'>
        <div class='row box-row-title'>
            <div class='col-md-8'><h4>Document Share: view</h4></div>
            <div class='col-md-4 text-right'></div>
        </div>
        <div class="">
            <div class="box-white border-radius-5 margin-10-0 clearfix">
                <div class="col-md-12">
                    <h4 class="border-bottom-gray padding-10-0"><?php echo $e["shar_title"]; ?> </h4>
                    <div class="clearfix">
                        <aside class="col-md-9">
                            <div class="padding-10-0">
                                <?php echo $e["shar_detail"]; ?>
                            </div>
                        </aside>
                        <aside class="col-md-3">
                            <img class="full-w" src="<?php echo $this->basepath()."/img/share/". $e["shar_img"];?>" />
                        </aside>
                    </div>

                    <div class="clearfix border-top-gray padding-10-0">
                        <aside class="col-md-4">
                            <span>Posted by: </span><label class="color-blue"><?php echo $e["shar_post_by"]; ?></label>
                        </aside>
                        <aside class="col-md-4">
                            <span>Posting date: </span><label class="color-blue"><?php echo $e["shar_post_date"]; ?></label>
                        </aside>

                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="text-right col-md-12">
            <a href="#" class="color-red btn-delete"> <i class="glyphicon glyphicon-trash"></i> Delete</a>
            <span>&nbsp; | &nbsp;</span>
            <a href="#" class="btn-approval" data-approval="<?php echo ($e["shar_approval"]==0)?1:0; ?>"><i class="glyphicon glyphicon-ok"></i> Approval</a>
        </div>
        <br><br>
    </div>
</div>

<script>
    $(function(){
        var id = '<?php echo $e["share_id"]?>';
        var baseUrl = '<?php echo $this->basepath();?>';
        $('.btn-delete').click(function(){
            if(confirm("Are you sure you want to delete?")){

                url='<?php echo $this->url('admin-share')."delete/"?>'+id;
                $.ajax({
                    url:url,
                    success:function(){
                        window.location.href=baseUrl + '/admin-share';
                    }
                });
            }

            return false;

        });
        $('.btn-approval').click(function(){
            var ch =$(this).attr('data-approval');
            url='<?php echo $this->url('admin-share')."approve/"?>'+id+'?ch='+ch;
            $.ajax({
                url:url,
                success:function(){
                    window.location.href=baseUrl + '/admin-share';
                }
            });
            return false;
        });
    });
</script>
