<?php
/**
 * Created by PhpStorm.
 * User: dimang12
 * Date: 11/23/14
 * Time: 1:36 PM
 */
?>
<ol class="breadcrumb no-margin no-background">
    <li><a href="<?php echo $this->basepath(); ?>/"><i class="glyphicon glyphicon-home"></i> Home</a></li>
    <li><a href="<?php echo $this->basepath(); ?>/info"> <i class="glyphicon glyphicon-book "></i> Information </a></li>
    <li class="active"> <i class="glyphicon <?php echo $this->icon; ?>"></i> <?php echo $this->curPage; ?></li>
</ol>