<?php if(count($this->technicals)!=0){?>
<div class='row-fluid'>
			<div class='table-responsive'>
				<table class='table table-bordered'>
					<tr class='warning'>
						<th>No.</th>
						<th>Category Id</th>
						<th>Field</th>
						<th>Field(kh)</th>
						<th>Value</th>
						<th>Value(kh)</th>
						<th>Action</th>
					</tr>
					<?php foreach ($this->technicals as $k => $col): ?>
						<tr>
							<td><?php echo $k+1?></td>
							<td><?php echo $col['category_id']?></td>
							<td><?php echo $col['tech_field']?></td>
							<td><?php echo $col['kh_tech_field']?></td>
							<td><?php echo $col['tech_value']?></td>
							<td><?php echo $col['kh_tech_value']?></td>
							<td>
								<div class='pull-left'><a href='<?php echo $this->url('dashboard-product-technical-edit')?>?Id=<?php echo $col['technical_id']?>' title='Edit'><span class='icon-edit glyphicon glyphicon-pencil'></span></a></div>
								<div class='pull-right'><a href='#' title='Remove'><span data-remove='<?php echo $col['technical_id']?>'class='icon-remove glyphicon glyphicon-remove'></span></a></div>
							</td>
						</tr>
					<?php endforeach ?>
				</table>
			</div>

</div>
<?php }else{?>
	<div class="alert alert-info"><strong>Sorry ,</strong> Record not found!</div>
<?php }?>
<script>
	$(function(){
		$('.icon-remove').on('click', function(){
			id = $(this).parents('td').find('.icon-remove').attr('data-remove');
			url ='<?php echo $this->url('dashboard-product-technical-remove')?>?id='+id;
			if(confirm('Are you sure to delete?')){
				$.ajax({url: url, success: function(){window.location.href='';}});
			}
		});
	});
	//click filter 
	$('.btn-filter').on('click', function(){
		filter = $('.text-filter').val();
		url = '<?php echo $this->url('dashboard-product-technical-filter');?>?id='+filter;
		$.ajax({url: url, success: function(result){$('.addons').html(result);}});
	});
</script>