<div class='container-fluid'>
	<?php echo $this->partial('admin/partial/_nav_menu')?>
	<div class='col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main'>
		<div class='page-header'>
			<div class='row'>
				<div class='col-md-2'><h1 class='text-warning'>Information</h1></div>
				<div class='col-md-6'>
					<?php 
					$tmp = array();
					$parentCate = array();
					$count = 0;
					$tempOption = $this->option;
					foreach ($tempOption as $k=>$v)
					{
						if($v['cate_parent'] ==0)
						{
							$parentCate[$v['category_id']] = $v['cate_name'];
							unset($tempOption[$k]);
						}
						
					}
					
					foreach($parentCate as $k=>$v){
						$subCate = array();
						foreach ($tempOption as $subK =>$subV){
							if($k == $subV["cate_parent"]){
								$subCate[$subV["category_id"]] = $subV["cate_name"];
								unset($tempOption[$subK]);
							}
							
						}
						$parentCate[$k] = array("label"=>$v, "options"=>$subCate);
					}?>
					<div class='row'>
						<div class="form-group col-md-10">
							<?php echo $this->formselect($form->get('category_id')->setAttributes(array('options'=>$parentCate,'class'=>'form-control text-filter')))?>
						</div>
						<a type="submit" class="col-md-2 btn btn-warning btn-filter"><span class='glyphicon glyphicon-filter'></span>  Filter</a>
					</div>
				</div>
				<div class='col-md-4 text-right'><a href='<?php echo $this->url('dashboard-product-info-add')?>' class='btn btn-success'>New information</a></div>
			</div>
		</div>
		
		<div class='row-fluid addons'>
			<div class='table-responsive'>
				<table class='table table-bordered'>
					<tr class='warning'>
						<th>No.</th>
						<th>Description</th>
						<th>Description(kh)</th>
						<th>General</th>
						<th>General(kh)</th>
						<th>Color</th>
						<th>Color(kh)</th>
						<th>Actions</th>
					</tr><?php $i=1?>
					<?php foreach ($this->info as $k => $col): ?>
						<tr>
							<td><?php echo $i++?></td>
							<td title='<?php echo $col['info_desc']?>'><?php echo strlen($col['info_desc']) > 28 ? substr($col['info_desc'], 0, 25).'...': $col['info_desc']?></td>
							<td title='<?php echo $col['kh_info_desc']?>'><?php echo strlen($col['kh_info_desc']) > 28 ? substr($col['kh_info_desc'], 0, 25).'...': $col['kh_info_desc']?></td>
							<td title='<?php echo $col['info_gene']?>'><?php echo strlen($col['info_gene']) > 28 ? substr($col['info_gene'], 0, 25).'...': $col['info_gene']?></td>
							<td title='<?php echo $col['kh_info_gene']?>'><?php echo strlen($col['kh_info_gene']) > 28 ? substr($col['kh_info_gene'], 0, 25).'...': $col['kh_info_gene']?></td>
							<td title='<?php echo $col['info_color']?>'><?php echo strlen($col['info_color']) > 28 ? substr($col['info_color'], 0, 25).'...': $col['info_color']?></td>
							<td title='<?php echo $col['kh_info_color']?>'><?php echo strlen($col['kh_info_color']) > 28 ? substr($col['kh_info_color'], 0, 25).'...': $col['kh_info_color']?></td>
							
							<td>
								<div class='pull-left'><a href='<?php echo $this->url('dashboard-product-info-edit')?>?Id=<?php echo $col['information_id']?>' title='Edit'><span class='icon-edit glyphicon glyphicon-pencil'></span></a></div>
								<div class='pull-right'><a href='#' title='Remove'><span data-remove='<?php echo $col['information_id']?>'class='icon-remove glyphicon glyphicon-remove'></span></a></div>
							</td>
						</tr>
					<?php endforeach ?>
				</table>
			</div>

		</div>
	</div>
</div>
<script>
	$(function(){
		$('.icon-remove').on('click', function(){
			id = $(this).parents('td').find('.icon-remove').attr('data-remove');
			url ='<?php echo $this->url('dashboard-product-info-remove')?>?id='+id;
			if(confirm('Are you sure to delete?')){
				$.ajax({url: url, success: function(){window.location.href='';}});
			}
		});

		$('.btn-filter').on('click', function(){
			filter = $('.text-filter').val();
			url = '<?php echo $this->url('dashboard-product-information-filter')?>?id='+filter;
			$.ajax({
					url: url,
					success: function(r)
					{
						$('.addons').html(r);
					}
			});
			
		});
	});
</script>

