<?php
/**
 * Created by PhpStorm.
 * User: dimang12
 * Date: 12/6/14
 * Time: 3:26 PM
 */
?>

<!--<div class="bg-gray border-gray margin-10-0 border-radius-5">
    <div class="border-radius-top-5 no-padding">
        <?php /*echo $this->partial("application/info/partial/_breadcrumb", array("curPage"=>"About Us","icon"=>" glyphicon-user")); */?>
    </div>
</div>-->

<div class="box-white border-gray margin-10-0 border-radius-5 clearfix" style="line-height: 25px;">
    <div class="col-md-12">
        <h4 class="border-bottom-gray padding-10-0">About Us</h4>
        <div>
            <div class="col-md-8 text-justify">
                <h4 class="clearfix font-16 padding-10-0 border-bottom-gray color-light-black">Company Background</h4>
                YOUJOB.INFO is launched in December 30, 2014 by a Cambodian person as a professional human resource website, which focuses on job announcement, educational information, work or business experiences share and related human resource development. It is a website which employers and employees, educational providers and learners, and professional or successful person and non-successful person can share their job announcements, educational programs and work or business experiences to each other. Moreover, our active team uses their experiences from international companies and customers’ complaints or feedback to evaluate and develop our website because we want this site to be everyone’s.

                <br><br>
                YOUJOB is the human resource information partner site which contains many useful documents such as job announcements, applications, educational information, work or business experience share and human resource information events.
            </div>
            <div class="col-md-4">
                <br/><br/>
                <img class="full-w margin-top-10" src="<?php echo $this->basepath("/img/no-img-512x512.png"); ?>" alt=""/>
            </div>
        </div>

        <div>
            <div class="col-md-8 text-justify">
                <h4 class="clearfix font-16 padding-10-0 border-bottom-gray color-light-black margin-top-35">Our Vision</h4>
                YOUJOB is the leading human resource information and everyone’s site in Cambodia, and the region. Based on our business plan, this website will be your partner on such as:

                <br><br>
                <ul class="about-li" style="margin-left: 30px;">
                    <li> The leading job announcement site for both employers and employees.</li>
                    <li> The educational information site for both educational providers and learners.</li>
                    <li> The business site which people can share and learn business experiences.</li>
                    <li> The event information site which relates to human resource development.</li>
                </ul>

            </div>

            <div class="col-md-4">
                <br/><br/>
                <img class="full-w margin-top-10" src="<?php echo $this->basepath("/img/no-img-512x512.png"); ?>" alt=""/>
            </div>
        </div>

        <div>
            <div class="col-md-8 text-justify">
                <h4 class="clearfix font-16 padding-10-0 border-bottom-gray color-light-black">Our Mission</h4>
                To achieve our vision, we have mission which we categorize our strategies to promote this site to cooperators and users to ensure that this site is important tools of human resource information such as:

                <br><br>
                <ul class="about-li" style="margin-left: 30px;">
                    <li> Cooperating with previous industries to get job announcements for job seekers.</li>
                    <li> Collaborating with educational sectors to provide educational information for learners</li>
                    <li> Keeping close-relationship with employers, successful people and employees to share business and work experiences to our next generations.</li>
                    <li> Cooperating with human resource event-organizers to update new useful information for our users.</li>
                </ul>
            </div>

            <div class="col-md-4">
                <br/><br/>
                <img class="full-w margin-top-10" src="<?php echo $this->basepath("/img/no-img-512x512.png"); ?>" alt=""/>
                <br/><br/>
            </div>
        </div>
    </div>
    <br>
</div>

