<?php
/**
 * Created by PhpStorm.
 * User: dimang12
 * Date: 12/6/14
 * Time: 3:27 PM
 */
?>

<div class="box-white margin-10-0 border-radius-5">
    <div class="bg-gray border-radius-top-5 border-bottom-gray no-padding">
        <?php echo $this->partial("application/info/partial/_breadcrumb", array("curPage"=>"Contact Us","icon"=>" glyphicon-plus")); ?>
    </div>
    <div class="clearfix">
        <div class="col-md-12">Contact page</div>
    </div>
</div>