<?php
/**
 * Created by PhpStorm.
 * User: dimang12
 * Date: 12/6/14
 * Time: 3:47 PM
 */
?>

<div class="box-white margin-10-0 border-radius-5">
    <div class="bg-gray border-radius-top-5 border-bottom-gray no-padding">
        <?php echo $this->partial("application/info/partial/_breadcrumb", array("curPage"=>"Our Service","icon"=>" glyphicon-plus")); ?>
    </div>
    <div class="clearfix">
        <div class="col-md-12">
            <h4 class="border-bottom-gray padding-10-0">Our Service</h4>
            <div class="color-blue font-24">Welcome to YouJob,</div>
            <div class="clearfix">
                <div class="col-md-8 no-padding-left font-14">
                    <br/>
                    YOUJOB is professional and education information partner that
                    you can trust in. It has many package options that you can
                    advertise your job announcement and company with us. Here are
                    packages that you can purchase from us:
                    <br/><br/>
                    <ul>
                        <li>Job Posting Services</li>
                        <li>Resume Purchasing Packages</li>
                        <li>Featured Company Services</li>
                        <li>Banner Advertisement Services</li>
                    </ul>
                    <br/>
                    <div class="font-24 padding-10-0 border-bottom-gray">Job Posting Services</div>
                    <div class="font-24 padding-10-0 border-bottom-gray">Resume Purchasing Packages</div>
                    <div class="font-24 padding-10-0 border-bottom-gray">Featured Company Services</div>
                    <div class="font-24 padding-10-0 border-bottom-gray">Banner Advertisement Services</div>

                </div>
                <div class="col-md-4"></div>
            </div>
        </div>
    </div>
</div>