<div class="clearfix">
    <div class="col-md-12">
        <div class="clearfix">
            <label class="col-md-4"><b>Highest Qualification</b></label>
            <span>: {{r.resu_current_degree}}</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Latest Career Level</b></label>
            <span>: {{r.resu_position_level}} <Manager></Manager></span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Year of Experience</b></label>
            <span>: {{r.resu_year_experience}} </span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Latest Position</b></label>
            <span>: {{r.resu_current_position}}</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Latest Job Category</b></label>
            <span>: {{r.cate_name}}</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Latest Job Industry</b></label>
            <span>: {{r.indu_name}}</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Latest Salary</b></label>
            <span>: {{r.resu_salary}}</span>
        </div>

    </div>
</div>