<div class="clearfix">
    <div class="col-md-12">
        <div class="clearfix">
            <label class="col-md-4"><b>Preferred Industry</b></label>
            <span>: Information Technology</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Preferred Location</b></label>
            <span>: Phnom Penh / Siem Reap / Kamppng Cham <Manager></Manager></span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Preferred Position</b></label>
            <span>: Project Manager / Consultant /Senior API Developer  </span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Expected Salary</b></label>
            <span>: $1000 - $1800</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Term</b></label>
            <span>: Full Time</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Availability</b></label>
            <span>: At least one month</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Willing to travel</b></label>
            <span>: Yes</span>
        </div>

    </div>
</div>