<div class="box-white border-radius-5 margin-10-0  clearfix">
    <div class="bg-gray border-radius-top-5 border-bottom-gray no-padding">
        <?php echo $this->partial("application/education/partial/_breadcrumb", array("curPage"=>"Create new education","icon"=>" glyphicon-plus")); ?>
    </div>
    <div class="clearfix col-md-12">
        <?php echo $this->partial("application/education/partial/_add_education_form"); ?>
    </div>
</div>