<div class="box-white border-radius-5 margin-10-0 clearfix">
    <div class="bg-gray padding-5-0 clearfix border-bottom-gray border-radius-top-5">
        <ol class="breadcrumb no-margin no-background">
            <li><a href="<?php $this->basePath(); ?>">Home</a></li>
            <li class="active">Education</li>
        </ol>
    </div>
    <div class="box-body">
        <div class="col-md-12 clearfix">
            <h4 class="color-blue padding-10-0 border-bottom-gray" style="padding-bottom:20px;">Education Information
                <button class="btn btn-sm btn-default pull-right"><i class="glyphicon glyphicon-plus"></i> Post new aducation</button>
            </h4>

        </div>
        <div class="padding-10-0 clearfix">
            <aside class="col-md-8" style="padding-top:15px;">
                <?php foreach($this->eduData as $k=>$v): ?>
                <div class="media margin-10-0 clearfix">
                    <a href="#"><h4 class="media-heading color-blue pa"><?php echo $v["educ_title"];?></h4></a>
                    <a class="pull-left" href="#">
                        <img src="<?php echo $this->basePath(); ?>/img/user-login.png" alt="" class="img-thumbnail" width="100">
                    </a>
                    <div class="media-body">

                        <small class="color-ultra-light-black display-block margin-bottom-10 clearfix"> <b class="color-black">post by:</b> <?php echo $v["educ_post_by"]?> <b class="color-black">close date: </b> <?php echo date("d M, Y",strtotime($v["educ_post_date"]));?></small>
                        <?php echo $v["detail"];?>... <a href="#" class="color-red"> read more</a>
                    </div>
                </div>
                <?php endforeach; ?>
            </aside>
            <aside class="col-md-4 no-padding-right">
                <br>
                <div>
                    <img src="<?php echo $this->basePath()?>/img/promotion/1.png" class="col-md-12">
                    <img src="<?php echo $this->basePath()?>/img/promotion/2.gif" class="col-md-12 margin-10-0">
                </div>
            </aside>
        </div>
    </div>
</div>