<div class="row-fluid box-admin-main">
    <div class="col-md-2 padding-left-0">
        <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    </div>
    <div class='col-md-10 box-admin-right'>
        <div class='row box-row-title'>
            <div class='col-md-8'><h4 class='text-warning'>Education Information</h4></div>
            <div class='col-md-4 text-right'></div>
        </div>
        <br>
        <div class='row'>
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered">
                        <tr class="box-row-title">
                            <th>Code</th>
                            <th>Title</th>
                            <th>Posted By</th>
                            <th>Posting By</th>
                            <th>Closing Date</th>
                            <th>Approval</th>
                            <th>Action</th>
                        </tr>
                        <?php foreach ( $this->eduData as $key => $row ) {?>
                        <?php $check = $row["educ_approval"]==1?"checked":"";?>
                            <tr>
                                <td><?php echo $row['education_id']?></td>
                                <td><a href="<?php echo $this->basepath()."/admin-education/detail/".$row["education_id"];?>"><?php echo $row['educ_title']?></a></td>
                                <td><?php echo $row['educ_post_by']?></td>
                                <td><?php echo $row['educ_post_date']?></td>
                                <td><?php echo $row['educ_close_date']?></td>
                                <td align="center"><input education-id="<?php echo $row["education_id"]?>" class="chk-approval" type="checkbox" <?php echo $check?>></td>
                                <td align="center"><a href="#" class="btn btn-danger btn-delete" delete-id="<?php echo $row["education_id"]?>">Delete</a> </td>
                            </tr>
                        <?php }?>
                    </table>
                    <div class="text-center">
                        <?php echo $this->paginationControl($this->eduData,'Sliding','admin/partial/my_pagination_control.phtml'); ?>
                    </div>
                </div>
            </div>
        </div>
        <br>
    </div>
</div>

<script>
    $(function(){
        $('.btn-delete').click(function(){
            if(confirm("Are you sure you want to delete?")){
                education_id = $(this).attr('delete-id');
                url='<?php echo $this->url('delete-education')?>?educationId='+education_id;
                $.ajax({
                    url:url,
                    success:function(){
                        window.location.href='';
                    }
                });
            }

        });
        $('.chk-approval').click(function(){
            education_id = $(this).attr('education-id');
            ch ="0";
            if($(this).is(":checked"))
            {
                ch="1";
            }
            url='<?php echo $this->url('approval-education')?>?educationId='+education_id+'&ch='+ch;
            $.ajax({
                url:url,
                success:function(){

                }
            });
        });
    });
</script>
