<div class="row-fluid box-admin-main">
    <div class="col-md-2 padding-left-0">
        <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    </div>
    <div class='col-md-10 box-admin-right'>
        <div class='row box-row-title'>
            <div class='col-md-8'><h4 class='text-warning'>Education Information</h4></div>
            <div class='col-md-4 text-right'></div>
        </div>
        <br>
        <div class='row'>
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered">
                        <tr class="box-row-title">
                            <th>Code</th>
                            <th>Education Title</th>
                            <th>Education Detail</th>
                            <th>Education Close Date</th>
                            <th>Post By</th>
                        </tr>
                        <?php foreach ( $this->eduData as $key => $row ) {?>
                            <tr>
                                <td><?php echo $row['education_id']?></td>
                                <td><?php echo $row['educ_title']?></td>
                                <td><?php echo $row['educ_detail']?></td>
                                <td><?php echo $row['educ_post_date']?></td>
                                <td><?php echo $row['educ_post_by']?></td>
                            </tr>
                        <?php }?>
                    </table>
                    <?php echo $this->paginationControl($this->eduData,'Sliding','admin/partial/my_pagination_control.phtml'); ?>
                </div>
            </div>
        </div>
        <br>
    </div>
</div>
