<?php
    $adv_title = $adv_desc = $adv_ordering = "";
    foreach ($this->advData as $row){
        $adv_title = $row["adv_title"];
        $adv_desc = $row["adv_desc"];
        $adv_ordering = $row["adv_ordering"];
    }
?>
<?php $form = $this->form; echo $this->form()->openTag($form)?>
<div class="row-fluid box-admin-main">
    <div class="col-md-3 padding-left-0">
        <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    </div>
    <div class='col-md-9 box-admin-right'>
        <div class='row box-row-title'>
            <div class='col-md-8'><h4 class='text-warning'>Edit Advertisement</h4></div>
            <div class="col-md-4 padding-top-10 text-right"><button type="submit" class="btn-link"><span class="glyphicon glyphicon-save"></span> Update</button>
            <a href="<?php echo $this->url()?>" class=""><span class="glyphicon glyphicon-chevron-left"></span> Back</a></div>
        </div>
        <br>
        <div class='row'>
            <div class="col-md-4"><label>Advertisement Name</label><?php echo $this->formrow($form->get("adv_title")->setAttributes(array("value"=>$adv_title)))?></div>
            <div class="col-md-4"><label>Ordering</label><?php echo $this->formrow($form->get("adv_ordering")->setAttributes(array("value"=>$adv_ordering)))?></div>
        </div>
        <br>
        <div class='row'>
            <div class="col-md-12"><label>Advertisement Description</label><?php echo $this->formtextarea($form->get("adv_desc")->setAttributes(array("value"=>$adv_desc)))?></div>
        </div>
        <br>
    </div>
</div>
<?php echo $this->form()->closeTag($form)?>