<div class="row-fluid box-admin-main">
    <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    <div class='col-md-10 box-admin-right'>
        <div class='row box-row-title'>
            <div class='col-md-9'><h4 class='text-warning'>Advertisement</h4></div>
            <div class="col-md-3 text-right"><a href="<?php echo $this->url()."new"?>" class="btn btn-info margin-top-2 col-md-12">New Advertisement</a></div>
        </div>
        <br>
        <div class='row'>
            <div class='col-md-12'>
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <tr>
                            <th>No</th>
                            <th>Advertisement Name</th>
                            <th>Advertisement Description</th>
                            <th>Ordering</th>
                            <th>Action</th>
                        </tr>
                        <?php
                        $i=1;
                        foreach ( $this->advData as $key => $row ) {?>
                            <tr>
                                <td><?php echo $i?></td>
                                <td><?php echo $row['adv_title']?></td>
                                <td><?php echo $row['adv_desc']?></td>
                                <td><?php echo $row['adv_ordering']?></td>
                                <td><a href="<?php echo $this->url()."edit/".$row['adv_id']?>"><span class='icon-edit glyphicon glyphicon-pencil'></span></a> |
                                    <a href='#' title='Remove'><span data-remove='<?php echo $row['adv_id']?>'  class='icon-remove glyphicon glyphicon-remove'></span></a></td>
                            </tr>
                            <?php $i++; }?>
                    </table>
                </div>
            </div>
        </div>
        <br>
    </div>
</div>
<script>
    $(function(){
        $('.icon-remove').on('click',function(){
            var advId = $(this).attr('data-remove');
            if(advId != '')
            {
                if(confirm('Are you sure to delete?'))
                {
                    var url ='<?php echo $this->url()."delete/"?>'+advId;
                    $.ajax({url: url, success:function(){window.location.href='';}});
                }
                return false;
            }
        });
    });

</script>
