<?php $form = $this->form; echo $this->form()->openTag($form)?>
<div class="row-fluid box-admin-main">
    <div class="col-md-3 padding-left-0">
        <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    </div>
    <div class='col-md-9 box-admin-right'>
        <div class='row box-row-title'>
            <div class='col-md-8'><h4 class='text-warning'>New Advertisement</h4></div>
            <div class="col-md-4 text-right padding-top-10"><button type="submit" class="btn-link"><i class="glyphicon glyphicon-floppy-disk"></i> Save</button>
            <a href="<?php echo $this->url()?>" class="btn-link m"><i class="glyphicon glyphicon-chevron-left"></i> Back</a></div>
        </div>
        <br>
        <div class='row'>
            <div class="col-md-4"><label>Choose Image </label><?php echo $this->formrow($form->get("adv_image")->setAttributes(array("required"=>true)))?></div>
            <div class="col-md-4"><label>Advertisement Name</label><?php echo $this->formrow($form->get("adv_title"))?></div>
            <div class="col-md-4"><label>Ordering</label><?php echo $this->formrow($form->get("adv_ordering"))?></div>
        </div>
        <br>
        <div class='row'>
            <div class="col-md-12"><label>Advertisement Description</label><?php echo $this->formtextarea($form->get("adv_desc"))?></div>
        </div>
        <br>
    </div>
</div>
<?php echo $this->form()->closeTag($form)?>


