<?php $form = $this->form; echo $this->form()->openTag($form)?>
<div class="row-fluid box-admin-main">
    <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    <div class='col-md-10 box-admin-right'>
        <div class='row box-row-title'>
            <div class='col-md-8'><h4 class='text-warning'>New Advertisement</h4></div>
            <div class="col-md-2 text-right"><button type="submit" class="btn btn-info margin-top-2 col-md-12">Save</button></div>
            <div class="col-md-2 text-right"><a href="<?php echo $this->url()?>" class="btn btn-default margin-top-2 col-md-12">Back</a></div>
        </div>
        <br>
        <div class='row'>
            <div class="col-md-4"><label>Choose Image </label><?php echo $this->formrow($form->get("adv_image")->setAttributes(array("required"=>true)))?></div>
            <div class="col-md-4"><label>Advertisement Name</label><?php echo $this->formrow($form->get("adv_title"))?></div>
            <div class="col-md-4"><label>Ordering</label><?php echo $this->formrow($form->get("adv_ordering"))?></div>
        </div>
        <br>
        <div class='row'>
            <div class="col-md-12"><label>Advertisement Description</label><?php echo $this->formtextarea($form->get("adv_desc"))?></div>
        </div>
        <br>
    </div>
</div>
<?php echo $this->form()->closeTag($form)?>


