<?php echo $this->headLink ()->prependStylesheet ( $this->basePath () . '/css/datetimepicker/jquery.datetimepicker.css')?>
<?php echo $this->headScript ()->prependFile ( $this->basePath () . '/css/datetimepicker/jquery.datetimepicker.js')?>

<?php $form = $this->form?>
<?php echo $this->form()->openTag($form)?>
<?php
    $feat_started_date = '';
    $feat_end_date = '';
    $feat_ordering = '';
    foreach($this->featureData as $row){
        $feat_started_date = $row['feat_started_date'];
        $feat_end_date = $row['feat_end_date'];
        $feat_ordering = $row['feat_ordering'];
    }
?>
<div class='container-fluid'>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="page-header">
            <div class='row'>
                <div class="col-md-8">
                    <h1 class='text-warning'>Edit Feature</h1>
                </div>
                <div class="col-md-4 text-right">
                    <?php echo $this->formbutton()->openTag($form->get('submit')->setAttributes(array('class'=>'btn btn-success')));?>
                    <span class='glyphicon glyphicon-upload'></span> Update<?php echo $this->formbutton()->closeTag()?>
                    <a href="<?php echo $this->url("admin-feature")?>" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-4">
                <?php echo $this->formlabel($form->get("feat_started_date"))?>
                <?php echo $this->forminput($form->get('feat_started_date')->setAttributes(array('class'=>'col-md-12 form-control','id'=>'datetimepicker1','value'=>$feat_started_date)));?>
            </div>
            <div class="col-md-4">
                <?php echo $this->formlabel($form->get("feat_end_date"))?>
                <?php echo $this->forminput($form->get('feat_end_date')->setAttributes(array('class'=>'col-md-12 form-control','id'=>'datetimepicker2','value'=>$feat_end_date)));?>
            </div>
            <div class="col-md-4">
                <?php echo $this->formlabel($form->get("feat_ordering"))?>
                <?php echo $this->forminput($form->get('feat_ordering')->setAttributes(array('class'=>'col-md-12 form-control','value'=>$feat_ordering)));?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag()?>
<script>
    $(function(){
        $('#datetimepicker1').datetimepicker({
            timepicker:false,
            format:'Y-m-d'
        });
        $('#datetimepicker2').datetimepicker({
            timepicker:false,
            format:'Y-m-d'
        });
        $('.icon-delete').on('click', function(){
            livingId = $(this).parents('.showcase-image').find('.icon-delete').attr('living-id');
            url = '<?php echo $this->url('deletebeyond')?>?livingId='+ livingId;
            $.ajax({
                async: false,
                url: url,
                success: function(){
                    window.location.href= '';
                }
            });
        });

    });
</script>