<?php echo $this->headLink ()->prependStylesheet ( $this->basePath () . '/css/datetimepicker/jquery.datetimepicker.css')?>
<?php echo $this->headScript ()->prependFile ( $this->basePath () . '/css/datetimepicker/jquery.datetimepicker.js')?>


<?php
    $feat_started_date = '';
    $feat_end_date = '';
    $feat_ordering = '';
    foreach($this->featureData as $row){
        $feat_started_date = $row['feat_started_date'];
        $feat_end_date = $row['feat_end_date'];
        $feat_ordering = $row['feat_ordering'];
    }
?>
<?php $form = $this->form; echo $this->form()->openTag($form)?>
<div class="row-fluid box-admin-main">
    <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    <div class='col-md-10 box-admin-right'>
        <div class='row box-row-title'>
            <div class='col-md-8'><h4 class='text-warning'>Edit Feature</h4></div>
            <div class="col-md-2 text-right"><button type="submit" class="btn btn-info margin-top-2 col-md-12">Update</button></div>
            <div class="col-md-2 text-right"><a href="<?php echo $this->url("admin-feature")?>" class="btn btn-default margin-top-2 col-md-12">Back</a></div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-4">
                <?php echo $this->formlabel($form->get("feat_started_date"))?>
                <?php echo $this->forminput($form->get('feat_started_date')->setAttributes(array('class'=>'col-md-12 form-control','id'=>'datetimepicker1','value'=>$feat_started_date)));?>
            </div>
            <div class="col-md-4">
                <?php echo $this->formlabel($form->get("feat_end_date"))?>
                <?php echo $this->forminput($form->get('feat_end_date')->setAttributes(array('class'=>'col-md-12 form-control','id'=>'datetimepicker2','value'=>$feat_end_date)));?>
            </div>
            <div class="col-md-4">
                <?php echo $this->formlabel($form->get("feat_ordering"))?>
                <?php echo $this->forminput($form->get('feat_ordering')->setAttributes(array('class'=>'col-md-12 form-control','value'=>$feat_ordering)));?>
            </div>
        </div>
        <br>
    </div>
</div>
<?php echo $this->form()->closeTag()?>
<script>
    $(function(){
        $('#datetimepicker1').datetimepicker({
            timepicker:false,
            format:'Y-m-d'
        });
        $('#datetimepicker2').datetimepicker({
            timepicker:false,
            format:'Y-m-d'
        });
        $('.icon-delete').on('click', function(){
            livingId = $(this).parents('.showcase-image').find('.icon-delete').attr('living-id');
            url = '<?php echo $this->url('deletebeyond')?>?livingId='+ livingId;
            $.ajax({
                async: false,
                url: url,
                success: function(){
                    window.location.href= '';
                }
            });
        });

    });
</script>