<div class='container-fluid'>
    <?php //echo $this->partial('admin/partial/_nav_menu')?>

    <div class='col-md-10 col-md-offset-2 main'>
        <div class='page-header'>
            <div class='row'>
                <div class='col-md-8'><h1 class='text-warning'>Feature</h1></div>
                <div class='col-md-4 text-right'><a href='<?php echo $this->url('admin-feature-new')?>' class='btn btn-success'>New Feature</a></div>
            </div>
        </div>
        <div class='row-fluid'>
            <div class='table-responsive'>
                <table class='table table-bordered'>
                    <tr class='warning'>
                        <th>No.</th>
                        <th>Company Name</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                        <th>Ordering</th>
                        <th>Action</th>
                    </tr><?php $i = 1?>
                    <?php foreach ($this->featureData as $k => $col):?>
                        <tr>
                            <td><?php echo ($i++)?></td>
                            <td><?php echo $col['com_name']?></td>
                            <td><?php echo $col['feat_started_date']?></td>
                            <td><?php echo $col['feat_end_date']?></td>
                            <td><?php echo $col['feat_ordering']?></td>
                            <td><a href="<?php echo $this->url('admin-feature-edit')?>?featId=<?php echo $col['feature_id']?>"><span class='icon-edit glyphicon glyphicon-pencil'></span></a> |
                                <a href='#' title='Remove'><span data-remove='<?php echo $col['feature_id']?>'  class='icon-remove glyphicon glyphicon-remove'></span></a></td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
</div>
</div>

<script>
    $(function(){
        $('.icon-remove').on('click', function(){
            id = $(this).attr('data-remove');
            if(id != '')
            {
                if(confirm('Are you sure to delete?'))
                {
                    url ='<?php echo $this->url('admin-feature-delete')?>?featid='+id;
                    $.ajax({url: url, success:function(){window.location.href='';}});
                }
                return false;
            }
        });
    });
</script>