<div class="row-fluid box-admin-main">
    <div class="col-md-3 padding-left-0">
        <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    </div>
    <div class='col-md-9 box-admin-right'>
        <div class='row box-row-title'>
            <div class='col-md-9'><h4 class='text-warning'>Feature</h4></div>
            <div class="col-md-3 text-right padding-top-10"><a href="<?php echo $this->url('admin-feature-new')?>" class=""><span class="glyphicon glyphicon-plus"></span>New Feature</a></div>
        </div>
        <br>
        <div class='row'>
            <div class='col-md-12'>
                <div class='table-responsive'>
                    <table class='table table-hover table-bordered'>
                        <tr class='box-row-title'>
                            <th>No.</th>
                            <th>Company Name</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Link</th>
                            <th>Ordering</th>
                            <th>Action</th>
                        </tr><?php $i = 1?>
                        <?php foreach ($this->featureData as $k => $col):?>
                            <tr>
                                <td><?php echo ($i++)?></td>
                                <td><?php echo $col['company_name']?></td>
                                <td><?php echo $col['feat_started_date']?></td>
                                <td><?php echo $col['feat_end_date']?></td>
                                <td><?php echo $col['feat_link']?></td>
                                <td><?php echo $col['feat_ordering']?></td>
                                <td><a href="<?php echo $this->url('admin-feature-edit')?>?featId=<?php echo $col['feature_id']?>"><span class='icon-edit glyphicon glyphicon-pencil'></span></a> |
                                    <a href='#' title='Remove'><span data-remove='<?php echo $col['feature_id']?>'  class='icon-remove glyphicon glyphicon-remove'></span></a></td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
        <br>
    </div>
</div>

<script>
    $(function(){
        $('.icon-remove').on('click', function(){
            id = $(this).attr('data-remove');
            if(id != '')
            {
                if(confirm('Are you sure to delete?'))
                {
                    url ='<?php echo $this->url('admin-feature-delete')?>?featId='+id;
                    $.ajax({url: url, success:function(){window.location.href='';}});
                }
                return false;
            }
        });
    });
</script>