<?php echo $this->headLink ()->prependStylesheet ( $this->basePath () . '/css/datetimepicker/jquery.datetimepicker.css')?>
<?php echo $this->headScript ()->prependFile ( $this->basePath () . '/css/datetimepicker/jquery.datetimepicker.js')?>

<?php $form = $this->form; echo $this->form()->openTag($form)?>
<div class="row-fluid box-admin-main">
    <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    <div class='col-md-10 box-admin-right'>
        <div class='row box-row-title'>
            <div class='col-md-8'><h4 class='text-warning'>New Feature</h4></div>
            <div class="col-md-2 text-right"><button type="submit" class="btn btn-info margin-top-2 col-md-12">Save</button></div>
            <div class="col-md-2 text-right"><a href="<?php echo $this->url("admin-feature")?>" class="btn btn-default margin-top-2 col-md-12">Back</a></div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-4">
                <?php echo $this->formlabel($form->get('feat_image'));?>
                <?php echo $this->forminput($form->get('feat_image')->setAttributes(array('class'=>'form-control col-md-12','required'=>true)));?>
                <?php echo $this->error ?>
            </div>
            <div class="col-md-4">
                <?php
                $groups = array ();
                foreach ( $companyData as $value ) {
                    $groups [$value ['company_id']] = $value ['com_name'];
                }
                ?>
                <?php echo $this->formlabel($form->get('company_id'))?>
                <?php echo $this->formSelect($form->get('company_id')->setAttributes(array('class'=>'col-md-12 form-control','options'=>$groups)));?>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-4">
                <?php echo $this->formlabel($form->get("feat_started_date"))?>
                <?php echo $this->forminput($form->get('feat_started_date')->setAttributes(array('class'=>'col-md-12 form-control','id'=>'datetimepicker1','required'=>true)));?>
            </div>
            <div class="col-md-4">
                <?php echo $this->formlabel($form->get("feat_end_date"))?>
                <?php echo $this->forminput($form->get('feat_end_date')->setAttributes(array('class'=>'col-md-12 form-control','id'=>'datetimepicker2','required'=>true)));?>
            </div>
            <div class="col-md-4">
                <?php echo $this->formlabel($form->get("feat_ordering"))?>
                <?php echo $this->forminput($form->get('feat_ordering')->setAttributes(array('class'=>'col-md-12 form-control')));?>
            </div>
        </div>
        <br>
    </div>
</div>
<?php echo $this->form()->closeTag($form)?>
<script>
    $(function(){
        $('#datetimepicker1').datetimepicker({
            timepicker:false,
            format:'Y-m-d'
        });
        $('#datetimepicker2').datetimepicker({
            timepicker:false,
            format:'Y-m-d'
        });
        $('.icon-delete').on('click', function(){
            livingId = $(this).parents('.showcase-image').find('.icon-delete').attr('living-id');
            url = '<?php echo $this->url('deletebeyond')?>?livingId='+ livingId;
            $.ajax({
                async: false,
                url: url,
                success: function(){
                    window.location.href= '';
                }
            });
        });

    });
</script>