<?php echo $this->headLink ()->prependStylesheet ( $this->basePath () . '/css/datetimepicker/jquery.datetimepicker.css')?>
<?php echo $this->headScript ()->prependFile ( $this->basePath () . '/css/datetimepicker/jquery.datetimepicker.js')?>

<?php $form = $this->form; echo $this->form()->openTag($form)?>
<div class="row-fluid box-admin-main">
    <div class="col-md-3 padding-left-0">
        <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    </div>
    <div class='col-md-9 box-admin-right'>
        <div class='row box-row-title'>
            <div class='col-md-8'><h4 class='text-warning'>New Feature</h4></div>
            <div class="col-md-4 text-right padding-top-10"><button type="submit" class="btn-link"><i class="glyphicon glyphicon-floppy-disk"></i> Save</button>
                <a href="<?php echo $this->url("admin-feature")?>" class="btn-link m"><i class="glyphicon glyphicon-chevron-left"></i> Back</a></div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-4"><?php echo $this->formlabel($form->get('company_name'))?></div>
                    <div class="col-md-8">
                        <?php echo $this->formInput($form->get('company_name')->setAttributes(array('class'=>'col-md-12 form-control')  ));?>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-4"><?php echo $this->formlabel($form->get("feat_started_date"))?></div>
                    <div class="col-md-8">

                        <?php echo $this->forminput($form->get('feat_started_date')->setAttributes(array('class'=>'col-md-12 form-control','id'=>'datetimepicker1','required'=>true)));?>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-4"><?php echo $this->formlabel($form->get("feat_end_date"))?></div>
                    <div class="col-md-8">
                        <?php echo $this->forminput($form->get('feat_end_date')->setAttributes(array('class'=>'col-md-12 form-control','id'=>'datetimepicker2','required'=>true)));?>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-4"><?php echo $this->formlabel($form->get("feat_ordering"))?></div>
                    <div class="col-md-8">
                        <?php echo $this->forminput($form->get('feat_ordering')->setAttributes(array('class'=>'col-md-12 form-control')));?>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                    <?php echo $this->formRow($form->get("feat_image"))?>
            </div>
        </div>

        <br>
    </div>
</div>
<?php echo $this->form()->closeTag($form)?>
<script>
    $(function(){
        $('#datetimepicker1').datetimepicker({
            timepicker:false,
            format:'Y-m-d'
        });
        $('#datetimepicker2').datetimepicker({
            timepicker:false,
            format:'Y-m-d'
        });
        $('.icon-delete').on('click', function(){
            livingId = $(this).parents('.showcase-image').find('.icon-delete').attr('living-id');
            url = '<?php echo $this->url('deletebeyond')?>?livingId='+ livingId;
            $.ajax({
                async: false,
                url: url,
                success: function(){
                    window.location.href= '';
                }
            });
        });

    });
</script>