<div class="row-fluid box-admin-main">
    <div class="col-md-2 padding-left-0">
        <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    </div>
    <div class='col-md-10 box-admin-right'>
        <div class='row box-row-title'>
            <div class='col-md-8'><h4 class='text-warning'>All Employer</h4></div>
            <div class='col-md-4 text-right'></div>
        </div>
        <br>
        <div class='row'>
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered">
                        <tr class="box-row-title">
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Gender</th>
                            <th>Phone</th>
                            <th>Email</th>
                           <!-- <th>Count Job</th>-->
                        </tr>
                        <?php foreach ( $this->empData as $key => $row ) {?>
                            <tr>
                                <td><?php echo $row['user_first_name']?></td>
                                <td><?php echo $row['user_last_name']?></td>
                                <td><?php echo $row['user_gender']?></td>
                                <td><?php echo $row['user_phone']?></td>
                                <td><?php echo $row['user_email']?></td>
                            </tr>
                        <?php }  ?>
                    </table>
                    <?php //echo $this->paginationControl($this->jobData,'Sliding','admin/partial/my_pagination_control.phtml'); ?>
                </div>
            </div>
        </div>
        <br>
    </div>
</div>