<div class="row-fluid box-admin-main">
    <div class="col-md-3 padding-left-0">
        <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    </div>
    <div class='col-md-9 box-admin-right'>
        <div class='row box-row-title'>
            <div class='col-md-9'><h4 class='text-warning'>Job industry</h4></div>
            <div class="col-md-3 text-right"><a href="<?php echo $this->url('dashboard-industry-add')?>" class="margin-10 pull-right"> <i class="glyphicon glyphicon-plus"></i> New industry</a></div>
        </div>
        <br>
        <div class='row'>
            <div class='col-md-12'>
                <div class='table-responsive'>
                    <table class='table table-hover table-bordered'>
                        <tr class='box-row-title'>
                            <th>No.</th>
                            <th>Job industry Name</th>
                            <th>Job industry Detail</th>
                            <th>Ordering</th>
                            <th>Action</th>
                        </tr><?php $i = 1?>
                        <?php foreach ($this->catData as $k => $col): if($col['indu_parent'] == 0): ?>
                            <tr>
                                <td><?php echo ($i++)?></td>
                                <td><?php echo $col['indu_name']?></td>
                                <td><?php echo $col['indu_details']?></td>
                                <td><?php echo $col['indu_order']?></td>
                                <td><a href="<?php echo $this->url('dashboard-industry-edit')?>?catId=<?php echo $col['industry_id']?>"><span class='icon-edit glyphicon glyphicon-pencil'></span></a> |
                                    <a href='#' title='Remove'><span data-remove='<?php echo $col['industry_id']?>'  class='icon-remove glyphicon glyphicon-remove'></span></a></td>
                            </tr>
                        <?php endif; endforeach ?>
                    </table>
                    <?php echo $this->paginationControl($this->catData,'Sliding','admin/partial/my_pagination_control.phtml'); ?>
                </div>
            </div>
        </div>
        <br>
    </div>
</div>

<script>
    $(function(){
        $('.icon-remove').on('click', function(){
            id = $(this).parents('td').find('.icon-remove').attr('data-remove');
            if(id != '')
            {
                if(confirm('Are you sure to delete?'))
                {
                    url ='<?php echo $this->url('dashboard-industry-delete')?>?id='+id;
                    $.ajax({url: url, success:function(){window.location.href='';}});
                }
                return false;
            }
        });
    });
</script>