<div class="border-radius-5 margin-10-0  clearfix margin-bottom-dus-11">
    <div class="row">
        <div class="col-md-3 padding-right-11">
            <?php echo $this->partial("application/partial/_employer_menu.phtml");?>
        </div>

        <div class="col-md-9  padding-right-30">
            <div class="row">
                <div class="col-md-12 background-white border-gray border-radius-5 padding-right-15 height-514">
                    <div class="row"><div class="col-md-12"><h5 class="border-bottom-gray-light padding-bottom-11">Home</h5></div> </div>
                    <br>

                    <div class='row'>

                        <div class='col-md-4'>
                            <a href='<?php echo $this->url("job-seeker")."newjob";?>'>
                                <div class="placeholder col-md-12">
                                    <span class='glyphicon glyphicon-tags'></span>
                                    <h5>Job Posting</h5>
                                </div>
                            </a>
                        </div>
                        <div class='col-md-4'>
                            <a href='<?php echo $this->url("job-seeker")."joblisting";?>'>
                                <div class="placeholder col-md-12">
                                    <span class='glyphicon glyphicon-list-alt'></span>
                                    <h5>Job Viewing</h5>
                                </div>
                            </a>
                        </div>
                        <div class='col-md-4'>
                            <a href='#'>
                                <div class="placeholder col-md-12">
                                    <span class='glyphicon glyphicon-book'></span>
                                    <h5>Job Edition</h5>
                                </div>
                            </a>
                        </div>
                    </div>

                    <div class='row'>
                        <div class='col-md-4'>
                            <a href='#'>
                                <div class="placeholder col-md-12">
                                    <span class='glyphicon glyphicon-search'></span>
                                    <h5>Resume Search</h5>
                                </div>
                            </a>
                        </div>
                        <div class='col-md-4'>
                            <a href='#'>
                                <div class="placeholder col-md-12">
                                    <span class='glyphicon glyphicon-bookmark'></span>
                                    <h5>Resume Purchase</h5>
                                </div>
                            </a>
                        </div>
                        <div class='col-md-4'>
                            <a href='#'>
                                <div class="placeholder col-md-12">
                                    <span class='glyphicon glyphicon-file'></span>
                                    <h5>Resume Request</h5>
                                </div>
                            </a>
                        </div>
                    </div>

                    <div class='row'>
                        <div class='col-md-4'>
                            <a href='<?php echo $this->url("job-seeker")."companyinfo";?>'>
                                <div class="placeholder col-md-12">
                                    <span class='glyphicon glyphicon-th'></span>
                                    <h5>Company Profile</h5>
                                </div>
                            </a>
                        </div>
                        <div class='col-md-4'>
                            <a href='#'>
                                <div class="placeholder col-md-12">
                                    <span class='glyphicon glyphicon-list-alt'></span>
                                    <h5>Contact Person</h5>
                                </div>
                            </a>
                        </div>
                        <div class='col-md-4'>
                            <a href='<?php echo $this->url("job-seeker")."accountinfo";?>'>
                                <div class="placeholder col-md-12">
                                    <span class='glyphicon glyphicon-user'></span>
                                    <h5>User Change</h5>
                                </div>
                            </a>
                        </div>
                    </div>

                </div>
            </div>


        </div>
    </div>
</div>