<?php
$this->headLink ()->prependStylesheet ( $this->basePath () . '/css/bootstrap-wysihtml5.css');
$this->headScript ()->prependFile ( $this->basePath () . '/js/bootstrap-wysihtml5.js');
$this->headScript ()->prependFile ( $this->basePath () . '/js/wysihtml5-0.3.0.js');
?>
<?php
    $form = $this->form;
    echo $this->form()->openTag($form);
    foreach($this->comData as $row){
        $com_name=$row["com_name"];
        $com_contact_person=$row["com_contact_person"];
        $com_phone=$row["com_phone"];
        $com_email=$row["com_email"];
        $com_website=$row["com_website"];
        $com_phone_schedule=$row["com_phone_schedule"];
        $com_info=$row["com_info"];
        $com_address =$row["com_address"];
    }
?>
<div class="box-white border-radius-5 margin-10-0 clearfix">
    <div class="row-fluid">
        <div class="col-md-3">
            <?php echo $this->partial("application/partial/_employer_menu.phtml");?>
        </div>

        <div class="col-md-9 box-right margin-top-10">
            <div class="row box-row-title">
                <div class="col-md-12">
                    <h4 class="">Company Information</h4>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-4"><label>Company Name</label><?php echo $this->formrow($form->get('com_name')->setAttributes(array('class'=>'form-control','value'=>$com_name)))?></div>
                <div class="col-md-4"><label>Contact Name</label><?php echo $this->formrow($form->get('contact_name')->setAttributes(array('class'=>'form-control','value'=>$com_contact_person)))?></div>
                <div class="col-md-4"> <label>Phone</label><?php echo $this->formrow($form->get('com_phone')->setAttributes(array('class'=>'form-control','value'=>$com_phone)))?></div>
            </div>
            <div class="row">
                <div class="col-md-4"><label>Email</label><?php echo $this->formrow($form->get('com_email')->setAttributes(array('class'=>'form-control','value'=>$com_email)))?></div>
                <div class="col-md-4"><label>Website</label><?php echo $this->formrow($form->get('com_website')->setAttributes(array('class'=>'form-control','value'=>$com_website)))?></div>
                <div class="col-md-4"><label>Service Phone</label><?php echo $this->formrow($form->get('com_service_phone')->setAttributes(array('class'=>'form-control','value'=>$com_phone_schedule)))?></div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-12"><label>Company Information</label><?php echo $this->formtextarea($form->get('com_info')->setAttributes(array('class'=>'form-control','value'=>$com_info)))?></div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-12"><label>Company Address</label><?php echo $this->formtextarea($form->get('com_address')->setAttributes(array('class'=>'form-control','value'=>$com_address)))?></div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-12">
                    <button type="submit" class="btn  btn-info col-md-4">Update</button>
                </div>
            </div>
            <br>
        </div>
    </div>
</div>
<?php $this->form()->closeTag();?>
<script>
    $(function(){
        $('textarea').wysihtml5();
    });
</script>