<div class="box-white border-radius-5 margin-10-0 clearfix">
    <div class="row-fluid">
        <div class="col-md-3">
            <?php echo $this->partial("application/partial/_employer_menu.phtml");?>
        </div>

        <div class="col-md-9">
            <div class='container-fluid margin-top-10'>
                <div class="table-responsive">
                    <table class="table table-hover table-bordered">
                        <tr>
                            <th>No</th>
                            <th>Position</th>
                            <th>Hiring No</th>
                            <th>Posting Date</th>
                            <th>Location</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        <?php
                        $i=1;
                        foreach ( $jobData as $key => $row ) {?>
                            <tr>
                                <td><?php echo $i?></td>
                                <td><?php echo $row['job_name']?></td>
                                <td><?php echo $row['job_hiring_number']?></td>
                                <td><?php echo $row['job_published_date']?></td>
                                <td><?php echo $row['city_name']?></td>
                                <td><?php if($row['job_status']==1)echo 'Active'; else echo 'Expire';?></td>
                                <td><a href="<?php echo $this->url('job-seeker')."editjob/".$row['job_id']?>"><span class='icon-edit glyphicon glyphicon-pencil'></span></a> |
                                    <a href='#' title='Remove'><span data-remove='<?php echo $row['job_id']?>'  class='icon-remove glyphicon glyphicon-remove'></span></a></td>
                            </tr>
                            <?php $i++; }?>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function(){
        $('.icon-remove').on('click',function(){
            var jobId = $(this).attr('data-remove');
            if(jobId != '')
            {
                if(confirm('Are you sure to delete?'))
                {
                    var url ='<?php echo $this->url('job-seeker')."deletejob/"?>'+jobId;
                    $.ajax({url: url, success:function(){window.location.href='';}});
                }
                return false;
            }
        });
    });

</script>


