<?php
/**
 * Created by PhpStorm.
 * User: dimang12
 * Date: 1/7/15
 * Time: 1:26 PM
 */
?>

<div class="border-radius-5 margin-10-0  clearfix margin-bottom-dus-11">
    <div class="row">
        <div class="col-md-3 padding-right-11">
            <?php echo $this->partial("application/partial/_employer_menu.phtml");?>
        </div>

        <div class="col-md-9  padding-right-30 box-white border-radius-5">
            <h4 class="border-bottom-gray clearfix padding-bottom-11">
                <label class="pull-left margin-top-5 ">Purchased Resume:</label>
            </h4>

            <div class="table-responsive">
                <table class="table table-hover table-bordered">
                    <tr class="box-row-title">
                        <th>No</th>
                        <th>Name</th>
                        <th>Current Position</th>
                        <th>Level</th>
                        <th>Experience</th>
                        <th></th>
                    </tr>
                    <?php $i=1; foreach ( $this->resume as $key => $row ) { ?>
                        <tr>
                            <td><?php echo $i;?></td>
                            <td><?php echo $row['user_first_name'] ." " .$row['user_last_name'];?></td>
                            <td><?php echo $row["resu_current_position"]?></td>
                            <td><?php echo $row['resu_position_level']?></td>
                            <td><?php echo $row['resu_year_experience']?> year(s)</td>
                            <td>
                                <a href="<?php echo $this->basepath()."/job-employer/detail/".$row["resume_id"]; ?>">
                                    <i class="glyphicon glyphicon-eye-open"></i> View
                                </a>
                            </td>
                        </tr>
                        <?php $i++;}  ?>
                </table>
                <div class="text-center"><?php echo $this->paginationControl($this->resume,'Sliding','admin/partial/my_pagination_control.phtml'); ?></div>
            </div>
        </div>
    </div>
</div>