<div class="clearfix">
    <div class="col-md-3">
        <img class="full-w" src="<?php echo $this->basepath(); ?>/img/resume/dimang.jpg" />
    </div>
    <div class="col-md-9">
        <div class="clearfix">
            <label class="col-md-4"><b>Full Name</b></label>
            <span>: CHOU Dimang</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Date of birth</b></label>
            <span>: January 12 1989</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Gender</b></label>
            <span>: Male</span>
        </div>



        <div class="clearfix">
            <label class="col-md-4"><b>Nationality</b></label>
            <span>: Cambodia</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Location of Residence</b></label>
            <span>: Phnom Penh</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Email</b></label>
            <span>: dimang12@gmail.com</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Phone Number</b></label>
            <span>: 012 952 975 / 010 952 975</span>
        </div>

        <div class="clearfix">
            <label class="col-md-4"><b>Address</b></label>
            <span>: #59Cz, Street 150z, Sangkat Psa Depot II, Khan Toul Kork, Phnom Penh, Cambodia</span>
        </div>
    </div>
</div>