<?php
    $this->headScript()->prependFile($this->basepath()."/js/angular.js");
?>
<div ng-app = "resume"  class="box-white border-radius-5 clearfix margin-10-0">
    <div class="col-md-12 bg-gray border-radius-top-5 border-bottom-gray no-padding">
        <ol class="breadcrumb no-margin no-background">
            <li><a href="#"><i class="glyphicon glyphicon-home"></i> Home</a></li>
            <li class="active"> <i class="glyphicon glyphicon-file"></i> Resume</li>
        </ol>
    </div>
    <div class="padding-10-0 clearfix">
        <br>
        <div class="col-md-3">
            <br>
            <div class="list-group">
                <a href="#general-info" class="list-group-item active">
                    General Information
                </a>
                <a href="#career-profile" class="list-group-item">Career Profile</a>
<!--                <a href="#job-preference" class="list-group-item">Job Preference</a>-->
                <a href="#educations" class="list-group-item">Education</a>
                <a href="#experiences" class="list-group-item">Experiences</a>
                <a href="#skills" class="list-group-item">Skills</a>
                <a href="<?php echo $this->basepath();?>/resume/logout" class="list-group-item">Logout</a>
            </div>
        </div>
        <div class="col-md-9  font-13" ng-controller = "resumeController">
            <h4 id="general-info" class="padding-10-0 margin-15-0 border-bottom-gray">General Information
                <a class="font-13 pull-right" href="<?php echo $this->basepath();?>/resume/general"><i class="glyphicon glyphicon-pencil"></i> Edit</a>
            </h4>
            <?php echo $this->partial("application/resume/partial/_general"); ?>
            <h4 id="career-profile" class="padding-10-0 margin-15-0 border-bottom-gray">Career Profile
                <a class="font-13 pull-right" href="<?php echo $this->basepath();?>/resume/careerprofile"><i class="glyphicon glyphicon-pencil"></i> Edit</a>
            </h4>
            <?php echo $this->partial("application/resume/partial/_career_profile"); ?>

            <h4 id="educations" class="padding-10-0 margin-15-0 border-bottom-gray">Education
                <a class="font-13 pull-right" href="<?php echo $this->basepath();?>/resume/education"><i class="glyphicon glyphicon-pencil"></i> Edit</a>
            </h4>
            <?php echo $this->partial("application/resume/partial/_education"); ?>
            <h4 id="experiences" class="padding-10-0 margin-15-0 border-bottom-gray">Experiences
                <a class="font-13 pull-right" href=""><i class="glyphicon glyphicon-pencil"></i> Edit</a>
            </h4>
            <?php echo $this->partial("application/resume/partial/_experience"); ?>
            <h4 id="skills" class="padding-10-0 margin-15-0 border-bottom-gray">Skills
                <a class="font-13 pull-right" href="#"><i class="glyphicon glyphicon-pencil"></i> Edit</a>
            </h4>
            <?php echo $this->partial("application/resume/partial/_skill"); ?>
        </div>
    </div>

</div>
<script>
    var resumeApp = angular.module("resume", []);
    resumeApp.controller("resumeController",function($scope){
        $scope.r = <?php if(count($this->general)>0) echo json_encode($this->general); else echo '{}'; ?>;
        $scope.d = <?php if(count($this->detail)>0) echo json_encode($this->detail); else echo '{}'; ?>;

    });
</script>