<?php
    $this->headScript()->prependFile($this->basepath()."/js/angular.js");
?>
<div ng-app = "resume"  class=" border-radius-5 margin-top-10">
    <div class="row">
        <div class="col-md-3 padding-right-11">
            <?php echo $this->partial("application/partial/_resume_menu")?>
        </div>
        <div class="col-md-9  font-13 padding-right-30 margin-bottom-10" ng-controller = "resumeController">
            <div class="row">
                <div class="col-md-12 background-white border-gray border-radius-5">
                    <h4 id="general-info" class="padding-10-0 margin-15-0 border-bottom-gray">General Information
                        <a class="font-13 pull-right" href="<?php echo $this->basepath();?>/resume/general"><i class="glyphicon glyphicon-pencil"></i> Edit</a>
                    </h4>
                    <?php echo $this->partial("application/resume/partial/_general"); ?>
                    <h4 id="career-profile" class="padding-10-0 margin-15-0 border-bottom-gray">Career Profile
                        <a class="font-13 pull-right" href="<?php echo $this->basepath();?>/resume/careerprofile"><i class="glyphicon glyphicon-pencil"></i> Edit</a>
                    </h4>
                    <?php echo $this->partial("application/resume/partial/_career_profile"); ?>

                    <h4 id="educations" class="padding-10-0 margin-15-0 border-bottom-gray">Education
                        <a class="font-13 pull-right" href="<?php echo $this->basepath();?>/resume/education"><i class="glyphicon glyphicon-pencil"></i> Edit</a>
                    </h4>
                    <?php echo $this->partial("application/resume/partial/_education"); ?>
                    <h4 id="experiences" class="padding-10-0 margin-15-0 border-bottom-gray">Experiences
                        <a class="font-13 pull-right" href=""><i class="glyphicon glyphicon-pencil"></i> Edit</a>
                    </h4>
                    <?php echo $this->partial("application/resume/partial/_experience"); ?>
                    <h4 id="skills" class="padding-10-0 margin-15-0 border-bottom-gray">Skills
                        <a class="font-13 pull-right" href="#"><i class="glyphicon glyphicon-pencil"></i> Edit</a>
                    </h4>
                    <?php echo $this->partial("application/resume/partial/_skill"); ?>
                </div>
            </div>
        </div>
    </div>

</div>
<script>
    var resumeApp = angular.module("resume", []);
    resumeApp.controller("resumeController",function($scope){
        $scope.r = <?php if(count($this->general)>0) echo json_encode($this->general); else echo '{}'; ?>;
        $scope.d = <?php if(count($this->detail)>0) echo json_encode($this->detail); else echo '{}'; ?>;

    });
</script>