<div class="border-radius-5 margin-10-0 padding-right-15 clearfix">
    <?php $loginForm = $this->loginForm; $loginForm->prepare();	echo $this->form()->openTag($loginForm); ?>
    <div class='col-md-5' style="margin: 95px 0 100px 28%; ">
        <div class='panel-success panel-login border-light-gray border-radius-5' style="box-shadow:0px 2px 2px #D5D5D5; padding-top:30px;">
            <div class="">
                <div class="text-center"><img src="<?php echo $this->basePath(); ?>/img/user-login.png" width="100" /></div>
                <h3 class="text-center">MEMBER LOGIN </h3>
            </div>
            <div class='panel-body'>
                <br />
                <div class='form-group'>
                    <div class='col-sm-12'>
                        <div class='input-group'>
                            <?php echo $this->formText($loginForm->get('username')->setAttributes(array('required'=>true))); ?>
                            <span class='input-group-addon'><span class='glyphicon glyphicon-user'></span></span>
                        </div>
                    </div>
                </div>
                <div class='form-group'>
                    <div class='col-sm-12'>
                        <div class='input-group'>
                            <?php echo $this->formpassword($loginForm->get('password')->setAttributes(array('required'=>true))); ?>
                            <span class='input-group-addon'><span class='glyphicon glyphicon-record'></span></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class='panel-footer text-right' style="padding-bottom: 1px">
                <div class='form-group'>
                    <div class='col-sm-12'>
                        <?php echo $this->formButton()->openTag($loginForm->get('btnlogin')); ?>Log In<?php echo $this->formButton()->closeTag();?>
                    </div>
                    <?php echo $this->formElement($loginForm->get('csrf')) ?>
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag($loginForm); ?>
</div>