<?php
/**
 * Created by PhpStorm.
 * User: dimang12
 * Date: 11/21/14
 * Time: 6:31 PM
 */
?>

<div class=" border-radius-5 margin-top-10">
    <div class="row">
        <div class="col-md-3 padding-right-11">
            <?php echo $this->partial("application/partial/_resume_menu")?>
        </div>
        <div class="col-md-9  font-13 padding-right-30 margin-bottom-10">
            <div class="row">
                <div class="col-md-12 background-white border-gray border-radius-5">
                    <?php echo $this->partial("application/resume/form/_skill_form"); ?>
                    <br/>
                </div>
            </div>

        </div>
    </div>
</div>