<?php
$this->headLink()->prependStylesheet($this->basePath() . '/css/education.css');
?>

<div class="box-white border-radius-5 margin-10-0 clearfix">
    <div class="bg-gray padding-5-0 clearfix border-bottom-gray border-radius-top-5">
        <ol class="breadcrumb no-margin no-background">
            <li><a href="<?php echo $this->basePath(); ?>/">Home</a></li>
            <li class="active">Document share</li>
        </ol>
    </div>
    <div class="box-body">
        <div class="col-md-12 clearfix">
            <h4 class="color-blue padding-10-0 border-bottom-gray" style="padding-bottom:20px;">Document Share
                <a href="<?php echo $this->basepath();?>/document-share/add" class="font-13 pull-right margin-top-10"><i class="glyphicon glyphicon-plus"></i> Post new document</a>
            </h4>
        </div>
        <div class="padding-10-0 clearfix">

            <aside class="col-md-12" style="padding-top:15px;">
                <?php foreach($this->paginator as $k=>$v): ?>
                    <div class="media margin-10-0 clearfix col-md-6 no-padding-left">

                        <a class="col-md-3 margin-5 border-light-gray" href="<?php echo $this->basepath()."/education/detail/".$v["share_id"];?>"
                            style="background-image: url('<?php echo $this->basepath()."/img/share/".$v["shar_img"]; ?>'); height:90px; background-position: center; background-size: cover; "
                            >
                        </a>
                        <div class="media-body padding-0-5">
                            <a href="<?php echo $this->basepath()."/document-share/detail/".$v["share_id"]?>">
                                <h4 class="media-heading color-blue font-14 no-margin"><?php echo $v["shar_title"];?></h4></a>
                                <small class="color-ultra-light-black display-block margin-bottom-10 clearfix margin-10-0">
                                    <span class="clearfix tooltip-panel">
                                        <label class="color-black col-md-4 no-padding-left">Uploaded by</label>
                                        : <a style="width: 300px;" href="#" data-toggle="popover" class="bottom" data-placement="bottom" title="<?php echo $v["shar_title"]; ?>" ><?php echo $v["shar_post_by"]?></a>
                                        <div class="tooltip bottom tooltip-content" role="tooltip">
                                            <div class="clearfix"><div class="col-md-5 bold no-padding-left">Uploaded by</div>: <?php echo $v["shar_post_by"] ?></div>
                                            <div class="clearfix"><div class="col-md-5 bold no-padding-left">Address</div>: <?php echo $v["shar_address"] ?></div>
                                            <div class="clearfix"><div class="col-md-5 bold no-padding-left">Phone Number</div>: <?php echo $v["shar_phone"] ?></div>
                                            <div class="clearfix"><div class="col-md-5 bold no-padding-left">Email Address</div>: <?php echo $v["shar_email"] ?></div>
                                            <div class="clearfix"><div class="col-md-5 bold no-padding-left">Website</div>: <?php echo $v["shar_website"] ?></div>
                                        </div>
                                    </span>
                                    <span class="clearfix">
                                        <label class="color-black col-md-4 no-padding-left">Uploaded date </label> : <?php echo date("d M, Y",strtotime($v["shar_post_date"]));?>
                                    </span>
                                </small>
                            <?php echo substr(strip_tags($v["shar_detail"]),0,80);?>
                        </div>
                    </div>
                    <?php
                        if(($k+1)%2==0) echo "<div class='clearfix'></div>";
                    ?>
                <?php endforeach; ?>
                <div class="clearfix"></div>
                <div class="text-center clearfix"> <?php echo $this->paginationControl($this->paginator,'sliding',array('layout/_paginator.phtml','viewmore'),array('controller' => 'Education','category'=>''));?> </div>
            </aside>

        </div>
    </div>
</div>
<script>
    $(document).ready(function(){

        $('[data-toggle="popover"]').each(function(k,v){
            var title = $(v).text();
            var body = $(v).parents('.tooltip-panel').find('.tooltip-content').html();
            $(v).popover({
                title: title,
                content: body,
                html:true,
                container:'body'
            });
            $(v).on('click', function(){ return false;});
        });
    });
</script>