<div class='container-fluid'>
	<?php echo $this->partial('admin/partial/_nav_dashboard')?>

	<div class='col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main'>
		<div class='page-header'>
			<h1 class='text-warning'>Dashboard</h1>
		</div>
		<div class='row'>
			<div class='col-md-3'>
				<a href='<?php echo $this->url('dashboard-beyondliving')?>'>
					<div class="placeholder col-md-12">
						<span class='glyphicon glyphicon-home'></span>
						<h4>Beyond Living</h4>
					</div>
				</a>
			</div>

			<div class='col-md-3'>
				<a href='<?php echo $this->url('dashboard-category')?>'>
					<div class="placeholder col-md-12">
						<span class='glyphicon glyphicon-th-large'></span>
						<h4>Category</h4>
					</div>
				</a>
			</div>
			<div class='col-md-3'>
				<a href='<?php echo $this->url('dashboard-production')?>'>
					<div class="placeholder col-md-12">
						<span class='glyphicon glyphicon-shopping-cart'></span>
						<h4>Production</h4>
					</div>
				</a>
			</div>
			<div class='col-md-3'>
				<a href='<?php echo $this->url('dashboard-showcase')?>'>
					<div class="placeholder col-md-12">
						<span class='glyphicon glyphicon-map-marker'></span>
						<h4>Showcase</h4>
					</div>
				</a>
			</div>
			
		</div>
		<div class='row'>
			<div class='col-md-3'>
				<a href='<?php echo $this->url('dashboard-slide')?>'>
					<div class="placeholder col-md-12">
						<span class='glyphicon glyphicon-sound-stereo'></span></span>
						<h4>Slides Control</h4>
					</div>
				</a>
			</div>
		</div>
		
	</div>
</div>
