<div class="container-fluid bg">
    <?php echo $this->partial('admin/partial/_member_menu.phtml'); ?>
    <div class='col-md-10 main'>
        <div class='row'>
            <div class='col-md-3'>
                <a href='<?php echo $this->url('member-admin-job')?>'>
                    <div class="placeholder col-md-12">
                        <span class='glyphicon glyphicon-home'></span>
                        <h4>Job Management</h4>
                    </div>
                </a>
            </div>

        </div>
    </div>
</div>
