<ol class="breadcrumb">
	<li><a href="<?php echo $this->url("home");?>">Home</a></li>
	<li><a href='<?php echo $this->url('support') ?>'>Support</a></li>
	<li class='active'>Download Catalog</li>
</ol>
<br>
<div class="whole-body clearfix">
	<div class="col-md-3">
		<?php echo $this->partial("application/partial/_support_nav_left")?>
	</div>

	<div class='col-md-9 sothyka-catalog catalog-box'>
			<div class='col-md-12 sothyka-catalog-title'>
				<h3>Catalog and Product Information</h3>
			</div>
			<div class='row '>
				<div class='col-md-3 text-center'>
					<div class='thumbnail'>
					<img src='<?php echo $this->basepath()?>/img/support/aw_woodcatt_thai_newci_cover_front1.jpg'>
						<div class='caption sothyka-product-caption'>
							<h3>SOTHYKA Wood</h3>
							<p><button class='btn btn-success btn-sm'><span class='glyphicon glyphicon-cloud'></span> &nbsp;Download PDF</button></p>
					</div>
					</div>
				</div>
				<div class='col-md-3 text-center'>
					<div class='thumbnail'>
					<img src='<?php echo $this->basepath()?>/img/support/shera-board-en.png'>
						<div class='caption sothyka-product-caption'>
							<h3>SOTHYKA Board</h3>
							<p><button class='btn btn-success btn-sm'><span class='glyphicon glyphicon-cloud'></span> &nbsp;Download PDF</button></p>
					</div>
					</div>
				</div>
				<div class='col-md-3 text-center'>
					<div class='thumbnail'>
					<img src='<?php echo $this->basepath()?>/img/support/infillwall_cover__en.jpg'>
						<div class='caption sothyka-product-caption'>
							<h3>SOTHYKA Infillwall</h3>
							<p><button class='btn btn-success btn-sm'><span class='glyphicon glyphicon-cloud'></span> &nbsp;Download PDF</button></p>
					</div>
					</div>
				</div>
				<div class='col-md-3 text-center'>
					<div class='thumbnail'>
					<img src='<?php echo $this->basepath()?>/img/support/paint_cover.jpg'>
						<div class='caption sothyka-product-caption'>
							<h3>SOTHYKA Paint</h3>
							<p><button class='btn btn-success btn-sm'><span class='glyphicon glyphicon-cloud'></span> &nbsp;Download PDF</button></p>
						</div>
					</div>
				</div>				
				</div>
				
				<hr>
				
				<div class='row'>
				<div class='col-md-3 text-center'>
					<div class='thumbnail'>
					<img src='<?php echo $this->basepath()?>/img/support/icon.jpg'>
						<div class='caption sothyka-product-caption'>
							<h3>SOTHYKA Home</h3>
							<p><button class='btn btn-success btn-sm'><span class='glyphicon glyphicon-cloud'></span> &nbsp;Download PDF</button></p>
						</div>
					</div>
				</div>
				<div class='col-md-3 text-center'>
					<div class='thumbnail'>
					<img src='<?php echo $this->basepath()?>/img/support/catalog-window-door-system-th.png'>
						<div class='caption sothyka-product-caption'>
							<h3>ระบบประตูเฌอร่า</h3>
							<p><button class='btn btn-success btn-sm'><span class='glyphicon glyphicon-cloud'></span> &nbsp;Download PDF</button></p>
						</div>
					</div>
				</div>
				<div class='col-md-3 text-center'>
					<div class='thumbnail'>
					<img src='<?php echo $this->basepath()?>/img/support/catalog-shera-ply-th.png'>
						<div class='caption sothyka-product-caption'>
							<h3>ไม้อัดเฌอร่า</h3>
							<p><button class='btn btn-success btn-sm'><span class='glyphicon glyphicon-cloud'></span> &nbsp;Download PDF</button></p>
						</div>
					</div>
				</div>				
				<div class='col-md-3 text-center'>
					<div class='thumbnail'>
					<img src='<?php echo $this->basepath()?>/img/support/catalog-shera-board-th.png'>
						<div class='caption sothyka-product-caption'>
							<h3>แผ่นลายเฌอร่าบอร์ด</h3>
							<p><button class='btn btn-success btn-sm'><span class='glyphicon glyphicon-cloud'></span> &nbsp;Download PDF</button></p>
						</div>
					</div>
				</div>
				
				</div>
				
				<hr>
				
				<div class='row'>
					<div class='col-md-3 text-center'>
					<div class='thumbnail'>
					<img src='<?php echo $this->basepath()?>/img/support/catalog-shera-deco-ceiling-th.png'>
						<div class='caption sothyka-product-caption'>
							<h3>แผ่นฝ้าลายเฌอร่าบอร์ด</h3>
							<p><button class='btn btn-success btn-sm'><span class='glyphicon glyphicon-cloud'></span> &nbsp;Download PDF</button></p>
						</div>
					</div>
				</div>
				<div class='col-md-3 text-center'>
					<div class='thumbnail'>
					<img src='<?php echo $this->basepath()?>/img/support/shingle_cover.jpg'>
						<div class='caption sothyka-product-caption'>
							<h3>กระเบื้องหลังคาห้าห่วงชิงเกิ้ล</h3>
							<p><button class='btn btn-success btn-sm'><span class='glyphicon glyphicon-cloud'></span> &nbsp;Download PDF</button></p>
						</div>
					</div>
				</div>
				<div class='col-md-3 text-center'>
					<div class='thumbnail'>
					<img src='<?php echo $this->basepath()?>/img/support/catalog-magma_cover.jpg'>
						<div class='caption sothyka-product-caption'>
							<h3>กระเบื้องหลังคาห้าห่วงแม็กม่า</h3>
							<p><button class='btn btn-success btn-sm'><span class='glyphicon glyphicon-cloud'></span> &nbsp;Download PDF</button></p>
						</div>
					</div>
				</div>
				<div class='col-md-3 text-center'>
					<div class='thumbnail'>
					<img src='<?php echo $this->basepath()?>/img/support/cove1r.jpg'>
						<div class='caption sothyka-product-caption'>
							<h3>SOTHYKA Slate</h3>
							<p><button class='btn btn-success btn-sm'><span class='glyphicon glyphicon-cloud'></span> &nbsp;Download PDF</button></p>
						</div>
					</div>
				</div>
				</div>	
		</div>
	</div>


<br>

<br>