<?php
/**
 * Created by PhpStorm.
 * User: dimang12
 * Date: 12/14/14
 * Time: 11:06 PM
 */
?>
<div class="box-white border-radius-5 margin-10-0  clearfix">
    <div class="bg-gray border-radius-top-5 border-bottom-gray no-padding">
        <?php echo $this->partial("application/share/partial/_breadcrumb", array("curPage"=>"Post new experience","icon"=>" glyphicon-plus")); ?>
</div>
<div class="clearfix col-md-12">
    <?php echo $this->partial("application/experience/partial/_add_expr_form"); ?>
</div>
</div>

