<?php
/**
 * Created by PhpStorm.
 * User: dimang12
 * Date: 12/14/14
 * Time: 11:06 PM
 */

$url = $data["expr_video"];
$queryString = parse_url($url);
parse_str($queryString['query'], $query);

?>

<div class="margin-10-0 clearfix">
    <div class="border-gray border-radius-5 bg-gray padding-5-0 clearfix margin-bottom-10">
        <ol class="breadcrumb no-margin no-background">
            <li><a href="<?php echo $this->basePath(); ?>/">Home</a></li>
            <li><a href="<?php echo $this->url("experience-share"); ?>">Experience Share</a></li>
            <li class="active">Video</li>
        </ol>
    </div>
    <div class="clearfix">
        <div class="col-md-8 box-white border-radius-5">
            <h4 class="border-bottom-gray padding-10-0">Experience Share, Video</h4>
            <div class="">
                <iframe class="full-w no-border" height="370" src="//www.youtube.com/embed/<?php echo $query["v"]; ?>">

                </iframe>
            </div>
        </div>
        <div class="col-md-4 no-padding-right">
            <div class="box-white  border-radius-5">
                <h4 class="padding-10 border-bottom-gray">Video by ...</h4>
                <div class="clearfix">
                    <?php foreach($this->related as $k=>$v):
                        $img = "";
                        if(!empty($v["expr_video"])){
                            $url = $v["expr_video"];
                            $queryString = parse_url($url);
                            parse_str($queryString['query'], $query);
                            $img = "http://img.youtube.com/vi/{$query["v"]}/default.jpg";
                        }else{
                            $img = "{$this->basepath()}/img/user-login.png";
                        }
                        ?>
                    <div class="margin-10-0 col-md-12">
                        <a class="col-md-3 margin-5 border-light-gray" href="<?php echo $this->basepath()."/experience-share/detail/".$v["experience_id"];?>"
                           style="background-image: url('<?php echo $img; ?>'); height:60px; background-position: center; background-size: cover; "
                            >
                        </a>
                        <div class="media-body padding-0-5">
                            <a href="<?php echo $this->basepath()."/experience-share/detail/".$v["share_id"]?>">
                                <h4 class="media-heading color-blue font-14 no-margin"><?php echo $v["expr_title"];?></h4></a>
                            <small class="color-ultra-light-black display-block margin-bottom-10 clearfix margin-10-0">
                            <span class="clearfix tooltip-panel">
                                <label class="color-black col-md-6 no-padding-left">Uploaded by</label>
                                :<a style="width: 300px;" href="#" data-toggle="popover" class="bottom" data-placement="bottom" title="<?php echo $v["expr_title"]; ?>" ><?php echo $v["expr_post_by"]?></a>
                                <div class="tooltip bottom tooltip-content" role="tooltip">
                                    <div class="clearfix"><div class="col-md-5 bold no-padding-left">Uploaded by</div>:<?php echo $v["expr_post_by"] ?></div>
                                    <div class="clearfix"><div class="col-md-5 bold no-padding-left">Address</div>:<?php echo $v["expr_address"] ?></div>
                                    <div class="clearfix"><div class="col-md-5 bold no-padding-left">Phone Number</div>:<?php echo $v["expr_phone"] ?></div>
                                    <div class="clearfix"><div class="col-md-5 bold no-padding-left">Email Address</div>:<?php echo $v["expr_email"] ?></div>
                                    <div class="clearfix"><div class="col-md-5 bold no-padding-left">Website</div>:<?php echo $v["expr_website"] ?></div>
                                </div>
                            </span>
                            <span class="clearfix">
                                <label class="color-black col-md-6 no-padding-left">Uploaded date </label> :<?php echo date("d M, Y",strtotime($v["expr_post_date"]));?>
                            </span>
                            </small>
                        </div>
                    </div>

                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>

</div>
<script>