<?php
/**
 * Created by PhpStorm.
 * User: dimang12
 * Date: 12/20/14
 * Time: 6:07 AM
 */
$this->headLink()->prependStylesheet($this->basePath() . '/css/education.css');
?>

<div class="margin-10-0 clearfix">
    <?php
        if($this->type==1){
            echo $this->partial("application/experience/partial/_more_document");
        }else{
            echo $this->partial("application/experience/partial/_more_video");
        }
     ?>
</div>
<script>
    $(document).ready(function(){

        $('[data-toggle="popover"]').each(function(k,v){
            var title = $(v).text();
            var body = $(v).parents('.tooltip-panel').find('.tooltip-content').html();
            $(v).popover({
                title: title,
                content: body,
                html:true,
                container:'body'
            });
            $(v).on('click', function(){ return false;});
        });
    });
</script>