<?php
/**
 * Created by PhpStorm.
 * User: dimang12
 * Date: 11/23/14
 * Time: 1:40 PM
 */
$this->headScript()->prependFile($this->basepath() . "/js/bootstrap-wysihtml5.js")
    ->prependFile($this->basepath() . "/js/wysihtml5-0.3.0.js");

$this->headLink ()->prependStylesheet ( $this->basePath () . '/css/jquery-ui.css')
                  ->prependStylesheet ( $this->basePath () . '/css/bootstrap-wysihtml5.css');;
$form = $this->form;
$form->setAttribute("action",$this->basepath()."/education/add");
$form->prepare();
?>
<div class="frm padding-10-0">
    <h3 class="margin-10-0 border-bottom-gray padding-10-0">Education
        <span class="label label-danger pull-right font-14 margin-top-10 hidden sms-fail"> Update fail.</span>
        <i class="loading pull-right margin-top-10 hidden"></i>
    </h3>
    <?php echo $this->form()->openTag($this->form); ?>
        <div class="clearfix">
            <div class="col-md-6 form-group">
                <?php echo $this->formLabel($form->get("educ_title")); ?>
                <?php echo $this->formInput($form->get("educ_title")); ?>

            </div>
            <div class="col-md-6 form-group">
                <?php echo $this->formLabel($form->get("educ_post_by")); ?>
                <?php echo $this->formInput($form->get("educ_post_by")); ?>
            </div>
        </div>

        <div class="clearfix">
            <div class="col-md-6 form-group">
                <?php echo $this->formLabel($form->get("educ_start_date")); ?>
                <?php echo $this->formInput($form->get("educ_start_date")); ?>
            </div>
            <div class="col-md-6 form-group">
                <?php echo $this->formLabel($form->get("educ_close_date")); ?>
                <?php echo $this->formInput($form->get("educ_close_date")); ?>
            </div>
        </div>
        <div class="clearfix">
            <div class="col-md-6 form-group">
                <?php echo $this->formLabel($form->get("educ_contact")); ?>
                <?php echo $this->formInput($form->get("educ_contact")); ?>
            </div>

            <div class="col-md-6 form-group">
                <?php echo $this->formLabel($form->get("image")); ?>
                <?php echo $this->formFile($form->get("image")); ?>
            </div>
        </div>
        <div class="clearfix">
            <div class="col-md-12 form-group">

                <ul class="ul-edu">
                    <li><label>Education Categories<label class="color-red">*</label>:</label> </li>
                    <li style="margin-left: 45px;"><label><input type="radio" name="education_category_id"/> Scholarship </label></li>
                    <li style="margin-left: 120px;"><label><input type="radio" name="education_category_id"/> Seminar/Conference </label></li>
                    <li style="margin-left: 120px;"><label><input type="radio" name="education_category_id"/> Career Exhibition </label></li>
                </ul>

                <ul class="ul-edu" style="margin-left: 182px;">
                    <li><label><input type="radio" name="education_category_id"/> Student Exchange Program </label></li>
                    <li style="margin-left: 28px;"><label><input type="radio" name="education_category_id"/> Social Charity </label></li>
                    <li style="margin-left: 156px;"><label><input type="radio" name="education_category_id"/> Training Courses </label></li>
                </ul>

                <ul class="ul-edu" style="margin-left: 182px;">
                    <li><label><input type="radio" name="education_category_id"/> Other Activities </label></li>
                </ul>
            </div>
        </div>
        <div class="clearfix">
            <div class="col-md-12 form-group">
                <?php echo $this->formLabel($form->get("educ_detail")); ?>
                <?php echo $this->formTextarea($form->get("educ_detail")); ?>
            </div>
        </div>

        <div class="clearfix text-center">
            <a href="<?php echo $this->basepath()?>/resume" class="btn btn-danger"> <i class="glyphicon glyphicon-remove-sign"></i> Cancel</a>
            <button class="btn btn-info btn-update"> <i class="glyphicon glyphicon-floppy-disk"></i> Save General</button>
        </div>
    <?php echo $this->form()->closeTag() ;?>
</div>
<script>
    $('textarea').wysihtml5();
    $('.form-control[name="educ_start_date"],.form-control[name="educ_close_date"] ').datepicker({dateFormat:'yy-mm-dd'});
</script>