<div class="w-center text-center">
    <br>
    <div class="clearfix font-11 margin-10-0">
        <a class="color-ultra-light-black shadow-white" href="<?php echo $this->basepath() ."/experience-share/"; ?>"><?php echo $this->translate("Experience Share");?></a>
        <span> | </span>
        <a class="color-ultra-light-black shadow-white" href="<?php echo $this->basepath() ."/info/about"; ?>"><?php echo $this->translate("About Us");?></a>
        <span> | </span>
        <a class="color-ultra-light-black shadow-white" href="<?php echo $this->basepath() ."/info/service"; ?>"><?php echo $this->translate("Our Services");?></a>
        <span> | </span>
        <a class="color-ultra-light-black" href="<?php echo $this->basepath() ."/info/feedback"; ?>"><?php echo  $this->translate("Feedback");?></a>
        <span> | </span>
        <a class="color-ultra-light-black" href="<?php echo $this->basepath() ."/info/contact"; ?>"><?php echo  $this->translate("Contact Us");?></a>
        <span> | </span>
        <a class="color-ultra-light-black" href="<?php echo $this->url("register")?>"><?php echo $this->translate("Register");?></a>
    </div>
    <div class="font-11 color-ultra-light-black">
        Copyright 2014 YourJob. All Rights Reserved.
    </div>
</div>
<br>
<br>