<div class="w-center text-center">
    <br>
    <div class="clearfix font-11 margin-10-0">
        <a class="color-ultra-light-black shadow-white" href="#"><?php echo $this->translate("Help Center");?></a>
        <span> | </span>
        <a class="color-ultra-light-black" href="#"><?php echo  $this->translate("Feedback");?></a>
        <span> | </span>
        <a class="color-ultra-light-black" href="#"><?php echo $this->translate("Share");?></a>
        <span> | </span>
        <a class="color-ultra-light-black" href="#"><?php echo $this->translate("Register");?></a>
    </div>
    <div class="font-11 color-ultra-light-black">
        Copyright 2014 YourJob. All Rights Reserved. Privacy Policy Site Design by Agust Interactive
    </div>
</div>
<br>
<br>