<div class="bg-white border-bottom-gray">
	<div class="w-center padding-10-0 border-bottom-gray ">
		<form action="" method="get" class="clearfix padding-5-0">
			<div class="col-md-5 no-padding">
				<input type="text" name="txtSearch" class="text border-radius-5 padding-8-5 full-w" id="txtSearch" placeholder="Search, Keywords" >
			</div>
			
			<div class="col-md-5">
				<div class="dropdown-gray padding-8-5 bold text-shadow border-radius-5 full-w">
					All Categories
					<i class="pull-right">more</i>
				</div>
			</div>
			
			<div class="col-md-2 no-padding">
				<button class="padding-8-5 btn-find-job no-border bold color-white shadow-red border-radius-5 full-w"><?php echo $this->translate("FIND JOB NOW!");?></button>
			</div>	
		</form>
	</div>
	<div class="w-center padding-10-0 text-right">
		<?php echo $this->translate("Welcome");?>
		<a >John Doe | Logout</a>
	</div>
	
</div>