<?php
   $cates = $this->getCategories();
    $count = count($cates);
    $limit = ($count%2==0)? $count/2: intval($count/2)+1;
?>

<div id="home" class="tab-pane fade in active clearfix top-cate">
    <input type="hidden" value="" class="search-cate-input" name="c">
    <aside class="col-md-6 no-padding-left border-right-gray search-cate">
        <ul>
            <?php for($i=0; $i<$limit; $i++): ?>
            <li class="full-w clearfix">
                <a data-id="<?php echo $cates[$i]["category_id"]?>" class="pull-left color-black"><?php echo $cates[$i]["cate_name"];?></a>
            </li>
            <?php endfor; ?>
        </ul>
    </aside>
    <aside class="col-md-6 no-padding-right search-cate">
        <ul>
            <?php for($i=$limit; $i<$count; $i++): ?>
                <li class="full-w clearfix">
                    <a data-id="<?php echo $cates[$i]["category_id"]?>" class="pull-left color-black"><?php echo $cates[$i]["cate_name"];?></a>
                </li>
            <?php endfor; ?>
        </ul>
    </aside>
</div>
<script>
    $('.search-cate a').on('click', function(){
        id = $(this).attr('data-id');
        $('.search-cate-input').val(id);
    });
</script>