<div class="box-white border-radius-5">
    <div class="padding-10-0 border-bottom-gray clearfix">
        <div class="col-md-12 clearfix">
            <div class="row">
                <aside class="col-md-5">
                    <div class="font-16 bold padding-10-0">Contact Us:</div>
                    <div class="col-md-4">
                        <img src="<?php echo $this->basepath()."/img/contact-us.png" ?>" width="100" />
                    </div>
                    <div class="col-md-8">
                        <div class="clearfix">
                            <label><b>Email: </b></label> sale@youjob.info
                        </div>
                        <div class="clearfix">
                            <label><b>Working days: </b></label> Monday - Sunday
                        </div>
                        <div class="clearfix">
                            <label><b>Working hours: </b></label> 8:00 AM - 5:00 PM
                        </div>
                    </div>
                </aside>

                <aside class="col-md-3 border-left-gray">
                    <div class="font-16 bold padding-10-0">Employer</div>
                    <div>
                        <a href="">Post job</a>
                        <a href="">Post urgent job</a><br>
                        <a href="">Resume search</a><br>
                        <a href="">Purchase Service Packages</a><br>
                        <a href="">Questions & Answers</a>
                    </div>
                </aside>

                <aside class="col-md-3 border-left-gray ">
                    <div class="font-16 bold padding-10-0">Job Seeker</div>
                    <div>
                        <a href="">Job search</a><br>
                        <a href="">Create Resume</a><br>
                        <a href="">Job Alert and Saved Searches</a><br>
                        <a href="">Questions & Answers</a>

                    </div>
                </aside>
            </div>

        </div>

    </div>
    <div class="bg-gray padding-10-0 clearfix">
        <div class="col-md-12">
            <div>
                <b>Be in touch:</b> read our blog
                <a href="http://twitter.com/share?url=http://www.codesdone.com"  onclick="return popitup('http://twitter.com/share?url=http://www.www.yourjob.com')">
                    <img class="pull-right" src="<?php echo $this->basepath().'/img/twitter.png';?>">
                </a>
                <a href="https://plus.google.com/share?url=http://www.codesdone.com"  onclick="return popitup('https://plus.google.com/share?url=http://www.www.yourjob.com')">
                    <img class="pull-right" src="<?php echo $this->basepath().'/img/google_plus.png';?>">
                </a>
                <a href="http://www.facebook.com/sharer.php?u=http://www.codesdone.com"  onclick="return popitup('http://www.facebook.com/sharer.php?u=http://www.yourjob.com')">
                    <img class="pull-right" src="<?php echo $this->basepath().'/img/facebook.png';?>">
                </a>
            </div>
        </div>
    </div>
</div>

