<div class="box-white border-radius-5">
    <div class="padding-10-0 border-bottom-gray clearfix">
        <div class="col-md-9 clearfix">
            <div class="row">
                <aside class="col-md-4">
                    <div class="font-16 bold padding-10-0">About Us</div>
                    <div>
                        Lorem ipsum dolor sit amet,
                        consectetur adipisicing elit,
                        sed do eiusmod tempor incididunt
                        ut labore et dolore magna aliqua.
                    </div>
                </aside>

                <aside class="col-md-4 border-left-gray">
                    <div class="font-16 bold padding-10-0">How to post a job?</div>
                    <div>
                        Lorem ipsum dolor sit amet,
                        consectetur adipisicing elit,
                        sed do eiusmod tempor incididunt
                        ut labore et dolore magna aliqua.
                    </div>
                </aside>

                <aside class="col-md-4 border-left-gray ">
                    <div class="font-16 bold padding-10-0">How to post a CV?</div>
                    <div>
                        Lorem ipsum dolor sit amet,
                        consectetur adipisicing elit,
                        sed do eiusmod tempor incididunt
                        ut labore et dolore magna aliqua.
                    </div>
                </aside>
            </div>

        </div>
        <div class="col-md-3"></div>
    </div>
    <div class="bg-gray padding-10-0 clearfix">
        <div class="col-md-12">
            <div>
                <b>Be in touch:</b> read our blog
            </div>
        </div>
    </div>
</div>

