<div class="box-white border-radius-5">
    <div class="padding-10-0 border-bottom-gray clearfix">
        <div class="col-md-9 clearfix">
            <div class="row">
                <aside class="col-md-4">
                    <div class="font-16 bold padding-10-0">About Us</div>
                    <div>
                        Lorem ipsum dolor sit amet,
                        consectetur adipisicing elit,
                        sed do eiusmod tempor incididunt
                        ut labore et dolore magna aliqua.
                    </div>
                </aside>

                <aside class="col-md-4 border-left-gray">
                    <div class="font-16 bold padding-10-0">How to post a job?</div>
                    <div>
                        Lorem ipsum dolor sit amet,
                        consectetur adipisicing elit,
                        sed do eiusmod tempor incididunt
                        ut labore et dolore magna aliqua.
                    </div>
                </aside>

                <aside class="col-md-4 border-left-gray ">
                    <div class="font-16 bold padding-10-0">How to post a CV?</div>
                    <div>
                        Lorem ipsum dolor sit amet,
                        consectetur adipisicing elit,
                        sed do eiusmod tempor incididunt
                        ut labore et dolore magna aliqua.
                    </div>
                </aside>
            </div>

        </div>
        <div class="col-md-3"></div>
    </div>
    <div class="bg-gray padding-10-0 clearfix">
        <div class="col-md-12">
            <div>
                <b>Be in touch:</b> read our blog
                <a href="http://twitter.com/share?url=http://www.codesdone.com"  onclick="return popitup('http://twitter.com/share?url=http://www.www.yourjob.com')">
                    <img class="pull-right" src="<?php echo $this->basepath().'/img/twitter.png';?>">
                </a>
                <a href="https://plus.google.com/share?url=http://www.codesdone.com"  onclick="return popitup('https://plus.google.com/share?url=http://www.www.yourjob.com')">
                    <img class="pull-right" src="<?php echo $this->basepath().'/img/google_plus.png';?>">
                </a>
                <a href="http://www.facebook.com/sharer.php?u=http://www.codesdone.com"  onclick="return popitup('http://www.facebook.com/sharer.php?u=http://www.yourjob.com')">
                    <img class="pull-right" src="<?php echo $this->basepath().'/img/facebook.png';?>">
                </a>
            </div>
        </div>
    </div>
</div>

