<div id="home" class="tab-pane fade in active clearfix top-location">
    <aside class="col-md-12 no-padding-left search-location">
        <input type="hidden" name="ct" value="" class="search-location-input" />
        <ul>
            <?php foreach($this->getLocations() as $k=>$v): ?>
            <li class="full-w clearfix">
                <a class="pull-left color-black" data-value ="<?php echo $v["city_id"]; ?>"><?php echo $v["city_name"]; ?></a>
            </li>
            <?php endforeach;?>
        </ul>
    </aside>
</div>
<script>
$('.serch-location a').on('click', function(){
    alert(1);
});
</script>