<div id="home" class="tab-pane fade in active clearfix top-location">
    <aside class="col-md-12 no-padding-left ">
        <ul>
            <li class="full-w clearfix"><a class="pull-left color-black" data-value = "1">Banteay Meanchey</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" data-value = "2">Battambang</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" data-value = "3">Kampong Cham</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" data-value = "4">Kampong Chhnang</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Kampong Som</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Kampong Spue</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Kampong Thom</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Kampot</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Kandal</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Kep</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Koh Kong</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Kratie</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Mondulkiri</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Oddar Meanchey</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Pailin</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Phnom Penh</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Prey Veng</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Preah Vihear</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Prey Veng</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Pursat</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Ratanakiri</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Siem Reap</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Stung Treng</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Svay Reang</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Takeo</a></li>
            <li class="full-w clearfix"><a class="pull-left color-black" href="/yourjobs/public/category/1">Tbong Khmum</a></li>
        </ul>
    </aside>
</div>