<ul class="menu">
    <li>
        <a class="bg-blue actived" href="<?php echo $this->basePath(); ?>">
            <i class="glyphicon glyphicon-home"></i>
            <span><?php echo $this->translate("Home");?></span>
        </a>
    </li>
    <li>
        <a class="bg-blue text-shadow" href="<?php echo $this->basePath(); ?>/job-seeker">
            <i class="glyphicon glyphicon-search"></i>
            <span><?php echo $this->translate("Job Seeker");?></span>
        </a>
    </li>
    <li>
        <a class="bg-blue text-shadow" href="<?php echo $this->basePath(); ?>/resume">
            <i class="glyphicon glyphicon-file"></i>
            <span><?php echo $this->translate("Resumes");?></span>
        </a>
    </li>
    <li>
        <a class="bg-blue text-shadow" href="<?php echo $this->basePath(); ?>/education">
            <i class="glyphicon glyphicon-book"></i>
            <span><?php echo $this->translate("Education");?></span>
        </a>
    </li>
</ul>