<div class="bg-gradient-light-gray border-top-blue">
	<div class="w-center clearfix top-header">
		<aside class="col-md-5 no-padding">
			<img alt="Your Job" src="<?php echo $this->basepath();?>/img/logo.png">
		</aside>
		<aside class="col-md-7 no-padding text-right clearfix">
			<div class="clearfix font-13">
				<a class="color-ultra-light-black shadow-white" href="#"><?php echo $this->translate("Help Center");?></a>
				<span> | </span>
				<a class="color-ultra-light-black" href="#"><?php echo  $this->translate("Feedback");?></a>
				<span> | </span>
				<a class="color-ultra-light-black" href="#"><?php echo $this->translate("Share");?></a>
				<span> | </span>
				<a class="color-ultra-light-black" href="#"><?php echo $this->translate("Register");?></a>
			</div>
            <?php echo $this->partial("layout/_menu"); ?>
		</aside>
	</div>
</div>