<?php
/**
 * Created by PhpStorm.
 * User: dimang12
 * Date: 11/23/14
 * Time: 1:40 PM
 */
$this->headScript()->prependFile($this->basepath() . "/js/bootstrap-wysihtml5.js")
    ->prependFile($this->basepath() . "/js/wysihtml5-0.3.0.js");

$this->headLink ()->prependStylesheet ( $this->basePath () . '/css/jquery-ui.css')
    ->prependStylesheet ( $this->basePath () . '/css/bootstrap-wysihtml5.css');;
$form = $this->form;
$form->setAttribute("action",$this->basepath()."/document-share/add");
$form->prepare();
?>
<div class="frm padding-10-0">
    <h3 class="margin-10-0 border-bottom-gray padding-10-0">Share Document
        <span class="label label-danger pull-right font-14 margin-top-10 hidden sms-fail"> Update fail.</span>
        <i class="loading pull-right margin-top-10 hidden"></i>
    </h3>
    <?php echo $this->form()->openTag($this->form); ?>
    <div class="clearfix">
        <div class="col-md-6 form-group">
            <?php echo $this->formLabel($form->get("shar_title")); ?>
            <?php echo $this->formInput($form->get("shar_title")); ?>

        </div>
        <div class="col-md-6 form-group">
            <?php echo $this->formLabel($form->get("shar_post_by")); ?>
            <?php echo $this->formInput($form->get("shar_post_by")); ?>
        </div>
    </div>

    <div class="clearfix">
        <div class="col-md-6 form-group">
            <?php echo $this->formLabel($form->get("shar_contact")); ?>
            <?php echo $this->formInput($form->get("shar_contact")); ?>
        </div>

        <div class="col-md-6 form-group">
            <?php echo $this->formLabel($form->get("image")); ?>
            <?php echo $this->formFile($form->get("image")); ?>
        </div>
    </div>

    <div class="clearfix">
        <div class="col-md-12 form-group">
            <?php echo $this->formLabel($form->get("shar_detail")); ?>
            <?php echo $this->formTextarea($form->get("shar_detail")); ?>
        </div>
    </div>


    <div class="clearfix text-center">
        <a href="<?php echo $this->basepath()?>/resume" class="btn btn-danger"> <i class="glyphicon glyphicon-remove-sign"></i> Cancel</a>
        <button class="btn btn-info btn-update"> <i class="glyphicon glyphicon-floppy-disk"></i> Save General</button>
    </div>
    <?php echo $this->form()->closeTag() ;?>
</div>
<script>
    $('textarea').wysihtml5();
    $('.form-control[name="shar_start_date"],.form-control[name="shar_close_date"] ').datepicker({dateFormat:'yy-mm-dd'});
</script>