
<ul class="nav nav-pills nav-stacked catalog-nav">
 	<li class='active'><a href='#'>Company Philosophy</a></li>
 	<li><a href='#'>Vision & Mission</a></li>
 	<li><a href='#'>SHERA FCS</a></li>
 	<li><a href='#'>Board of Directors</a></li>
 	<li><a href='#'>Product Technology & Standard</a></li>
 	<li><a href='#'>SHERA Media Gallery</a></li>
 	<li><a href='#'>  Contact SHERA</a></li>
</ul>
<br />
<br />

