<?php
$this->headLink ()->prependStylesheet ( $this->basePath () . '/css/accordion.css');

$this->headScript ()->prependFile ( $this->basePath () . '/js/accordion.js');

?>
<div id='cssmenu'>
    <ul>
        <li class='active'><a href='#'><span>Home</span></a></li>
        <li class='has-sub'><a href='#'><span>Profile Setting</span></a>
            <ul>
                <li><a href='#'><span>Account Information</span></a></li>
                <li class="active"><a href='#'><span>Company Information</span></a></li>
            </ul>
        </li>
        <li class='has-sub'><a href='#'><span>Job Management</span></a>
            <ul>
                <li><a href='#'><span>All Job</span></a></li>
                <li class='last'><a href='#'><span>New Job</span></a></li>
            </ul>
        </li>
    </ul>
</div>
<br>