<?php
$this->headLink ()->prependStylesheet ( $this->basePath () . '/css/accordion.css');
//$this->headScript ()->prependFile ( $this->basePath () . '/js/accordion.js');
?>
<?php
$sm = $this->getHelperPluginManager ()->getServiceLocator ();
$routeMatch = $sm->get ( 'Application' )->getMvcEvent ()->getRouteMatch ();
$router = $routeMatch->getMatchedRouteName();
$action="";
if ($routeMatch) {
    $controller = $routeMatch->getParam('controller');
    $action     = $routeMatch->getParam('action');
}
?>
<div id='cssmenu' class="background-white border-gray border-radius-5">
    <ul>
        <li class='has-sub'><a href='<?php echo $this->basepath();?>/resume'><span>Home</span></a>
            <ul>
                <li class='<?php if($action == 'general') echo 'actived';?>'><a href='<?php echo $this->basepath();?>/resume/general'><span>General Information</span></a></li>
                <li class='<?php if($action == 'careerprofile') echo 'actived';?>'><a href='<?php echo $this->basepath();?>/resume/careerprofile'><span>Career Profile</span></a></li>
                <li class="<?php if($action == 'education') echo 'actived';?>"><a href='<?php echo $this->basepath();?>/resume/education'><span>Educations</span></a></li>
                <li class="<?php if($action == 'experience') echo 'actived';?>"><a href='<?php echo $this->basepath();?>/resume/experience'><span>Experiences</span></a></li>
                <li class="<?php if($action == 'skill') echo 'actived';?>"><a href='<?php echo $this->basepath();?>/resume/skill'><span>Skills</span></a></li>
            </ul>
        </li>
        <li><a href='<?php echo $this->url("resume")."logout";?>'><span class="color-red">Logout</span></a></li>
    </ul>
</div>
<br>