<?php
$this->headLink ()->prependStylesheet ( $this->basePath () . '/css/accordion.css');
//$this->headScript ()->prependFile ( $this->basePath () . '/js/accordion.js');
?>
<?php
$sm = $this->getHelperPluginManager ()->getServiceLocator ();
$routeMatch = $sm->get ( 'Application' )->getMvcEvent ()->getRouteMatch ();
$router = $routeMatch->getMatchedRouteName();
$action="";
if ($routeMatch) {
    $controller = $routeMatch->getParam('controller');
    $action     = $routeMatch->getParam('action');
}
?>
<div id='cssmenu' class="background-white border-gray border-radius-5">
    <ul>
        <li class='<?php if($action=="index")echo "actived"?>'><a href='<?php echo $this->url("job-employer")?>'><span>Home</span></a></li>
        <li class='has-sub'><a href='#'><span>Job Management</span></a>
            <ul <?php if($action == 'joblisting' || $action == 'newjob' || $action == 'editjob') echo "style='display: block;'";?>>
                <li class='<?php if($action == 'newjob') echo 'actived';?>'><a href='<?php echo $this->url("job-employer")."newjob";?>'><span>Job Posting</span></a></li>
                <li class="<?php if($action == 'joblisting' || $action == 'editjob') echo 'actived';?>"><a href='<?php echo $this->url("job-employer")."joblisting";?>'><span>Job Viewing</span></a></li>
                <li class="<?php if($action == 'joblisting' || $action == 'editjob') echo '';?>"><a href='#'><span>Job Edition</span></a></li>
                <li class="<?php if($action == 'joblisting' || $action == 'editjob') echo '';?>"><a href='#'><span>Composing Sample</span></a></li>

            </ul>
        </li>
        <li class='has-sub'><a href='#'><span>Resume Management</span></a>
            <ul <?php if($action == 'accountinfo' || $action == 'companyinfo') echo "style='display: block;'";?>>
                <li class="<?php if($action == 'accountinfo') echo '';?>"><a href='#'><span>Resume Search</span></a></li>
                <li class="<?php if($action == 'companyinfo') echo '';?>"><a href='#'><span>Resume Purchase</span></a></li>
                <li class="<?php if($action == 'companyinfo') echo '';?>"><a href='#'><span>Resume Request</span></a></li>
            </ul>
        </li>
        <li class='has-sub'><a href='#'><span>Profile Setting</span></a>
            <ul <?php if($action == 'accountinfo' || $action == 'companyinfo') echo "style='display: block;'";?>>
                <li class="<?php if($action == 'companyinfo') echo 'actived';?>"><a href='<?php echo $this->url("job-employer")."companyinfo";?>'><span>Company Profile</span></a></li>
                <li class="<?php if($action == 'companyinfo') echo '';?>"><a href='#'><span>Contact Person</span></a></li>
                <li class="<?php if($action == 'accountinfo') echo 'actived';?>"><a href='<?php echo $this->url("job-employer")."accountinfo";?>'><span>User Change</span></a></li>

            </ul>
        </li>

        <li><a href='<?php echo $this->url("job-employer")."logout";?>'><span class="color-red">Logout</span></a></li>
    </ul>
</div>
<br>