<ul class="nav nav-pills nav-stacked catalog-nav">
 	<li class='active'><a href='#'>Download Catalog</a></li>
 	<li><a href='#'>Get a Quote</a></li>
 	<li><a href='#'>Live Chat</a></li>
 	<li><a href='#'>iCORNER</a></li>
 	<li><a href='#'>FAQs</a></li>
</ul>
<br />
<br />

<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Subscription</h3>
  </div>
  <div class="panel-body">
   <p>Leave your E-mail in the form below and you'll receive latest news and promotions before anyone else.</p>
   <form class="form-inline" role="form">
  		<div class="form-group">
    		<label class="sr-only" for="email">Email address</label>
    		<input type="email" class="form-control input-sm" id="email" placeholder="Enter email">
  		</div>
  		<button type="submit" class="btn btn-success btn-sm">Submit</button>
	</form>	
  </div>
</div>
<!-- img src='<?php echo $this->basepath()?>/img/references/calculator-tool.png' -->
<br>
<br>
<br>
<br>