<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Production\Module'                        => __DIR__ . '/Module.php',
    'Production\Controller\IndexController' => __DIR__ . '/src/Production/Controller/IndexController.php',
    'ProductionTest\Framework\TestCase'        => __DIR__ . '/tests/Production/Framework/TestCase.php',
    'ProductionTest\SampleTest'                => __DIR__ . '/tests/Production/SampleTest.php',
);
