<?php
    foreach($this->catData as $row){
        $cat_name = $row['cate_name'];
        $cat_order = $row['cate_order'];
        $cat_detail = $row['cate_details'];
    }
?>
<?php $form = $this->form; echo $this->form()->openTag($form)?>
    <div class="row-fluid box-admin-main">
        <div class="col-md-3 padding-left-0">
            <?php echo $this->partial('admin/partial/_left.phtml'); ?>
        </div>
    <div class='col-md-9 box-admin-right'>
        <div class='row box-row-title'>
            <div class="col-md-8">
                <h4 class='text-warning pull-left col-md-6'>Edit Category</h4>
            </div>
            <div class="col-md-4 padding-top-10">
                <a href="<?php echo $this->url("dashboard-category")?>" class="btn-link pull-right "><span class="glyphicon glyphicon-chevron-left"></span>  Back</a>
                <button type="submit" class="btn-link pull-right"   ><span class="glyphicon glyphicon-save"></span> Update</button>
            </div>

        </div>
        <br>
        <div class='row'>
            <div class='col-md-8'>
                <?php echo $this->formlabel($form->get('cate_name'))?>
                <?php echo $this->forminput($form->get('cate_name')->setAttributes(array('class'=>'form-control col-md-12 ','required'=>true,'value'=>$cat_name)))?>
            </div>

            <div class='col-md-4'>
                <?php echo $this->formlabel($form->get('cate_order'))?>
                <?php echo $this->forminput($form->get('cate_order')->setAttributes(array('class'=>'form-control col-md-12 ','value'=> $cat_order)))?>
            </div>
        </div>

        <div class='row'>
            <div class='col-md-12'><br>
                <?php echo $this->formlabel($form->get('cate_details'))?>
                <?php echo $this->formtextarea($form->get('cate_details')->setAttributes(array('class'=>'form-control col-md-12','rows'=>5,'value'=>$cat_detail)))?>
            </div>

        </div>
        <br>
    </div>
</div>
<?php echo $this->form()->closeTag($form)?>