<?php
    foreach($this->catData as $row){
        $cat_name = $row['cate_name'];
        $cat_order = $row['cate_order'];
        $cat_detail = $row['cate_details'];
    }
?>
<?php $form = $this->form; echo $this->form()->openTag($form)?>
<div class="container-fluid bg">
    <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    <div class='col-md-10 main'>
        <div class='page-header'>
            <div class='row'>
                <div class='col-md-8'><h1 class='text-warning'>Edit Category</h1></div>
                <div class='col-md-4 text-right'>
                    <a href='<?php echo $this->url('dashboard-category')?>' class='btn btn-default'><span class='glyphicon glyphicon-circle-arrow-left'></span> Back</a> &nbsp;&nbsp;
                    <?php echo $this->formbutton()->openTag($form->get('submit')->setAttributes(array('class'=>'btn btn-success')))?><span class='glyphicon glyphicon-floppy-disk'></span> Update<?php echo $this->formbutton()->closeTag()?>
                </div>
            </div>
        </div>

        <div class='row'>
            <div class='col-md-8'>
                <?php echo $this->formlabel($form->get('cate_name'))?>
                <?php echo $this->forminput($form->get('cate_name')->setAttributes(array('class'=>'form-control col-md-12 ','required'=>true,'value'=>$cat_name)))?>
            </div>

            <div class='col-md-4'>
                <?php echo $this->formlabel($form->get('cate_order'))?>
                <?php echo $this->forminput($form->get('cate_order')->setAttributes(array('class'=>'form-control col-md-12 ','value'=> $cat_order)))?>
            </div>

        </div>

        <div class='row'>
            <div class='col-md-12'><br>
                <?php echo $this->formlabel($form->get('cate_details'))?>
                <?php echo $this->formtextarea($form->get('cate_details')->setAttributes(array('class'=>'form-control col-md-12','rows'=>5,'value'=>$cat_detail)))?>
            </div>

        </div>

        <?php echo $this->form()->closeTag()?>
    </div>
</div>