<div class='container-fluid'>
	<?php echo $this->partial('admin/partial/_nav_menu')?>
	
	<div class='col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main'>
		<div class='page-header'>
			<div class='row'>
				<div class='col-md-8'><h1 class='text-warning'>Application</h1></div>
				<div class='col-md-4 text-right'><a href='<?php echo $this->url('dashboard-category-add')?>' class='btn btn-success'>New Application</a></div>
			</div>
		</div>
		
		<div class='row-fluid'>
			<div class='table-responsive'>
				<table class='table table-bordered'>
					<tr class='warning'>
						<th>No.</th>
						<th>Application</th>
						<th>App (kh)</th>
						<th>Order</th>
						<th>Desc (en)</th>
						<th>Desc (kh)</th>
						<th>Action</th>
					</tr><?php $i = 1?>
					<?php foreach ($this->getCate as $k => $col): if($col['cate_parent'] == 0): ?>
						<tr>
							<td><?php echo ($i++)?></td>
							<td><?php echo $col['cate_name']?></td>
							<td><?php echo $col['kh_cate_name']?></td>
							<td><?php echo $col['cate_order']?></td>
							<td title='<?php echo $col['cate_details']?>' ><?php echo strlen($col['cate_details']) > 28 ? substr($col['cate_details'], 0, 25).'...': $col['cate_details']?></td>
							<td title='<?php echo $col['kh_cate_details']?>'><?php echo strlen($col['kh_cate_details']) > 36 ? substr($col['kh_cate_details'], 0, 33).'...': $col['kh_cate_details']?></td>
							<td>
								<div class='pull-left'><a href='<?php echo $this->url('dashboard-category-edit')?>?cateId=<?php echo $col['category_id']?>' title='Edit'><span class='icon-edit glyphicon glyphicon-pencil'></span></a></div>
								<div class='pull-right'><a href='#' title='Remove'><span data-remove='<?php echo $col['category_id']?>'  class='icon-remove glyphicon glyphicon-remove'></span></a></div>
							</td>
						</tr>
					<?php endif; endforeach ?>
				</table>
			</div>

			<div class='page-header'>
				<div class='row'>
					<div class='col-md-2'>
						<h1 class='text-warning'>Categories</h1>
					</div>
					<div class='col-md-6'>
						<?php $form = $this->form; echo $this->form()->openTag($form);
							$tmp = array();
							foreach ($this->option as $k=>$v){
								$tmp[$v['category_id']]= $v['cate_name'];
							}					
						?>
						<div class="form-group">
							<?php echo $this->formselect($form->get('cate_parent')->setAttributes(array('options'=>$tmp,'class'=>'form-control col-md-12 text-filter')))?>
						</div>
						<a type="submit" class="btn btn-warning btn-filter"><span class='glyphicon glyphicon-filter'></span>  Filter</a>
					</div>
				<div class='col-md-4 text-right'><a href='<?php echo $this->url('dashboard-category-sub-add')?>' class='btn btn-success'>New Category</a></div>
				</div>
			</div>
			<div class='addons'>
				<div class='table-responsive'>
					<table class='table table-bordered'>
						<tr class='warning'>
							<th>No.</th>
							<th>Category</th>
							<th>Cate (kh)</th>
							<th>Order</th>
							<th>Action</th>
						</tr><?php $n=1?>
						<?php foreach ($this->getCate as $key => $sub): if($sub['cate_parent'] != 0): ?>
							<tr>
								<td><?php echo ($n++)?></td>
								<td><?php echo $sub['cate_name']?></td>
								<td><?php echo $sub['kh_cate_name']?></td>
								<td><?php echo $sub['cate_order']?></td>
								<td>
									<div class='pull-left'><a href='<?php echo $this->url('dashboard-category-sub-edit')?>?cateId=<?php echo $sub['category_id']?>' title='Edit' ><span  class='icon-edit glyphicon glyphicon-pencil'></span></a></div>
									<div class='pull-right'><a href='#' title='Remove'><span data-remove='<?php echo $sub['category_id']?>'  class='icon-remove glyphicon glyphicon-remove'></span></a></div>
								</td>
							</tr>
						<?php endif; endforeach ?>
					</table>
				</div>
			</div>	
		</div>
	</div>
</div>

<script>
	$(function(){
		$('.icon-remove').on('click', function(){
			id = $(this).parents('td').find('.icon-remove').attr('data-remove');
			if(id != '')
			{
				if(confirm('Are you sure to delete?'))
				{
					url ='<?php echo $this->url('dashboard-category-delete')?>?id='+id;
					$.ajax({url: url, success:function(){window.location.href='';}});
				}
				return false;
			}
		});

		//click on filter 
		$('.btn-filter').on('click', function(){
			filterId = $('.text-filter').val();
			url = '<?php echo $this->url('dashboard-category-filter')?>?id='+filterId;
			
			$.ajax({url: url, success: function(result){
				$('.addons').html(result);
			}});
		});

// 		//text-filter on change val
// 		$('.text-filter').change(function(){
// 			filterId = $('.text-filter').val();
			//url = '<?php //echo $this->url('dashboard-dashboard-filter')?>?id='+filterId;
			
// 			$.ajax({url: url, success: function(result){
// 				$('.addons').html(result);
// 			}});
// 		});
	});
</script>