<div class='col-md-9'>
		<div class='col-md-12 sothyka-tool'>
			<h4><?php echo $this->translate("New Products")?></h4>
		</div>
		<div class='row' style="padding:4px">
		<?php 
				$path = $this->basepath(). '/img/products/m/';
				$count = $this->count;
				$row = "<div class='row' style='margin-bottom: 15px'>";
				$col = $allRow = "";
				$i=1;		
				foreach ($this->paginator as $key => $new)
				{
					$loop = "
						<div class='col-md-3'>
							<a href='".$this->basepath().'/products/'.$new['prod_alias']."'class='thumbnail sothyka-thumbnail'>
								<img src='".$path . $new['imag_name']."'>
								<div class='caption sothyka-product-caption'>
									<h3>".$this->language($new, 'prod_name')."</h3>
									<p>".$this->language($new, 'prod_size')."</p>
								</div>
							</a>
						</div>
					";
					$col .= $loop;

					if($i%4 == 0 || $i == $count){
						$allRow .= $row.$col. "</div>";
						$col = "";
					}
					$i++;
					
				}
				echo $allRow;
			?>
			</div>		
	</div>