<ol class="breadcrumb">
	<li><a href="<?php echo $this->url("home");?>"><?php echo $this->translate('Home')?></a></li>
	 <li><a href="<?php echo $this->url("production");?>"><?php echo $this->translate('Products')?></a></li>
	<li class="active"><?php foreach ($this->getTitle as $k=> $li) { echo $this->language($li, 'prod_name'); }?></li>
</ol>
<br>
<div class="whole-body clearfix">
	<div class="col-md-3">
		<!-- col 3 -->
		<?php echo $this->partial("layout/_nav_category")?>
	</div>

	<div class='col-md-9 sothyka-info'>
		<div class='row'>
			
			<div class='col-md-7 sothyka-box'>
			<h3><?php foreach ($this->getTitle as $k=> $li) { echo $this->language($li, 'prod_name'); } ?></h3>			
				<p style="word-wrap: break-word"><?php foreach ($this->getInfo as $k=> $li) { echo $this->language($li, 'info_desc'); }?></p>
				<p>
					<strong><?php echo $this->translate('Material Code')?>: </strong><?php if(!empty($this->getCode)) echo $this->getCode?></p>

				<?php if(count($this->getSpecification) !=0):?><hr>
				<div class='sothyka-specification'>
					<h3><?php echo $this->translate('Specification')?></h3>
					<?php
					
					$path = $this->basepath () . '/img/specification/';
					foreach ( $this->getSpecification as $key => $sp ) {
						?><img src='<?php echo $path. $sp['spec_image']?> '
						title="<?php echo $sp['spec_title']?>">
						<?php echo "<b style='color:green;'>".$this->language($sp ,'spec_title')."</b>"?><br>
					<?php
					}
					?>
				</div><?php endif;?>

				<?php if(count($this->getStandard) !=0):?><hr>
				<div class='sothyka-standard'>
					<h3><?php echo $this->translate('Standard')?></h3>
					<?php
					$path = $this->basepath () . '/img/standard/';
					foreach ( $this->getStandard as $key => $stand ) {
						?><img src='<?php echo $path. $stand['stan_image']; ?>'>
						<?php echo '&nbsp;&nbsp;&nbsp;'.$stand ['stan_title'] . '<br><br >';}	?>				
				</div><?php endif;?>

				
			</div>
			<div class='col-md-5'>
	
				<div class='row-fluid'>
					<div class='preview' data-toggle="modal" data-target="#myModal" style="cursor:pointer;margin-bottom: 20px;border:1px solid #eee;border-radius:0; height:237px; width: 100%;background: url('<?php echo $this->basepath()?>/img/products/l/<?php echo $this->getImage ?>') no-repeat center;background-size:cover"></div>
				</div>
				<div class='row'>
					<?php foreach ( $this->getImages as $key => $img ) { ?>
						<div class='col-md-3'>
							<a href='#' class='other-image thumbnail' style="border:1px solid #eee;border-radius:0;height:60px;width:65px; background: url('<?php echo $this->basepath()?>/img/products/s/<?php echo $img['imag_name']?>') no-repeat center;background-size:cover"></a>
						</div>
					<?php } ?>
				<br>
				</div>
				<div class='sothyka-color'>
					<p style='word-wrap: break-word'><?php foreach ($this->getInfo as $k=> $li) { echo $this->language($li, 'info_color'); }?></p>
				</div>
				<div class='sothyka-remark'>
					<p>* More information, please contact your nearby local</p>
					<button class='btn btn-link'>SOTHYKA dealers.</button>
				</div>
				<?php if(count($this->getInfo) !=0):?><hr>
				<div class='sothyka-general'>
					<h3><?php echo $this->translate('General Information')?></h3>
					<p style='word-wrap: break-word'><?php foreach ($this->getInfo as $k=> $li) { echo $this->language($li, 'info_gene'); }?></p>
				</div><?php endif;?>
				
				<?php if(count( $this->getTechnical ) !=0): ?><hr>
				<div class='sothyka-technical'>
					<h3><?php echo $this->translate("Technical Information")?></h3>
					<table class='table table-striped'>
					<?php
					foreach ( $this->getTechnical as $key => $tech ) {
						?>
						<tr>
							<td><?php echo $this->language($tech, 'tech_field');?></td>
							<td><?php echo $this->language($tech, 'tech_value');?></td>
						</tr> <?php } ?>
					</table>
				</div><?php endif;?>
			</div>
		</div>
	</div>
</div>
<br />
<br />

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog"">
		<div class="modal-content large-image"
			style="width: 100%; height: 400px;border-radius:0;border: 4px solid #fff">
			<div class="modal-header" style="border: none">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
			</div>
		</div>
	</div>
</div>

<script>
	$(function(){
		$(".other-image").on("click", function(){			
			src = $(this).parents(".col-md-3").find("a").css("background-image");
			src = src.replace('/s/', '/l/');
			$(".preview").css({background: src+' no-repeat center',backgroundSize: 'cover'});
			return false;
		});

		$(".preview").on("click", function(){
			src = $(this).css("background-image");
			$(".large-image").css({background: src+' no-repeat center',backgroundSize: 'cover'});
		});

		$(".zoom-image").on('click', function(){
			$(".preview").trigger('click');
		});
	});
</script>
