<?php
$sm = $this->getHelperPluginManager ()->getServiceLocator ();
$routeMatch = $sm->get ( 'Application' )->getMvcEvent ()->getRouteMatch ();
$router = $routeMatch->getMatchedRouteName();
?>
<div class='col-md-2 sidebar' style="background: #28353B">
    <ul class="nav nav-sidebar">
        <li class="<?php if($router == 'admin-job-seeker') echo 'active'?>"><a href='<?php echo $this->url('admin-job-seeker')?>'><span class='glyphicon glyphicon-home' ></span> &nbsp;Resume / CV</a></li>
        <li class="<?php if($router == 'admin-resume-sample') echo 'active'?>"><a href="<?php echo $this->url('admin-resume-sample')?>"><span class='glyphicon glyphicon-map-marker'></span> &nbsp;Resume / CV Sample</a></li>
        <li class="<?php if($router == '') echo 'active'?>"><a href="#"><span class='glyphicon glyphicon-map-marker'></span> &nbsp;Job Alert</a></li>
        <li class="<?php if($router == '') echo 'active'?>"><a href="#"><span class='glyphicon glyphicon-map-marker'></span> &nbsp;Job Recommendation</a></li>
        <li class="<?php if($router == 'admin-seeker-jobsearch') echo 'active'?>"><a href="<?php echo $this->url('admin-seeker-jobsearch')?>"><span class='glyphicon glyphicon-map-marker'></span> &nbsp;Job Search</a></li>
        <li class="<?php if($router == '') echo 'active'?>"><a href="#"><span class='glyphicon glyphicon-map-marker'></span> &nbsp;Job Applying</a></li>
        <li class="<?php if($router == 'admin-userinfo') echo 'active'?>"><a href="<?php echo $this->url('admin-userinfo')?>"><span class='glyphicon glyphicon-map-marker'></span> &nbsp;Account Info</a></li>
    </ul>
</div>



