<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
          <h4 class="panel-title">
              <a  data-toggle="collapse" data-parent="#accordion" href="#job">
                  Resume Posting
              </a>
          </h4>
      </div>
      <div id="comment" class="panel-collapse collapse in">
          <div class="panel-body">
              <div class="panel-group" >
                  <ul>

                      <li><h4 class="panel-title"><a  href="<?php echo $this->url('admin-job-seeker')?>">Resume / CV</a></h4></li>
                      <li><h4 class="panel-title"><a  href="">Resume / CV Sample</a></h4></li>
                  </ul>
              </div>
          </div>
      </div>
      <div class="panel-heading">
          <h4 class="panel-title">
              <a  data-toggle="collapse" data-parent="#accordion" href="#job">
                  Job Information
              </a>
          </h4>
      </div>
      <div id="comment" class="panel-collapse collapse in">
          <div class="panel-body">
              <div class="panel-group" >
                  <ul>
                      <li><h4 class="panel-title"><a  href="">Job Alert</a></h4></li>
                      <li><h4 class="panel-title"><a  href="">Job Recommendation</a></h4></li>
                      <li><h4 class="panel-title"><a  href="">Job Search</a></h4></li>
                      <li><h4 class="panel-title"><a  href="">Job Applying</a></h4></li>
                  </ul>
              </div>
          </div>
      </div>
      <div class="panel-heading">
          <h4 class="panel-title">
              <a  data-toggle="collapse" data-parent="#accordion" href="#job">
                  User Account
              </a>
          </h4>
      </div>
      <div id="comment" class="panel-collapse collapse in">
          <div class="panel-body">
              <div class="panel-group" >
                  <ul>
                      <li><h4 class="panel-title"><a  href="<?php echo $this->url('admin-userinfo')?>">Account Info</a></h4></li>
                  </ul>
              </div>
          </div>
      </div>
  </div>
</div>
