<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a  data-toggle="collapse" data-parent="#accordion" href="#job">
          Job Announment
        </a>
      </h4>
    </div>
<div id="comment" class="panel-collapse collapse in">
      <div class="panel-body">
        <div class="panel-group" >
          <ul>
              <li><h4 class="panel-title"><a  href="<?php echo $this->url('job-posting')?>">Job Posting</a></h4></li>
              <li><h4 class="panel-title"><a  href="">Job Viewing</a></h4></li>
              <li><h4 class="panel-title"><a  href="">Composing Sample</a></h4></li>
          </ul>
         </div>
      </div>
    </div>
  </div>
</div>
