<div class='col-sm-2 sidebar' style="background: #28353B">
		<ul class="nav nav-sidebar">
			<li class="active"><a href='#'><span class='glyphicon glyphicon-th' ></span> &nbsp;Overview</a></li>
			<li><a href="#"><span class='glyphicon glyphicon-stats'></span> &nbsp;Rankings</a></li>
			<li><a href="#"><span class='glyphicon glyphicon-retweet'></span> &nbsp;Analytics</a></li>
			<li><a href="#"><span class='glyphicon glyphicon-link'></span> &nbsp;Links</a></li>
			<li><a href="#"><span class='glyphicon glyphicon-gift'></span> &nbsp;Social</a></li>
			<li><a href="#"><span class='glyphicon glyphicon-filter'></span> &nbsp;Research</a></li>
			<li><a href="#"><span class='glyphicon glyphicon-list-alt'></span> &nbsp;Reports</a></li>
			<li><a href="#"><span class='glyphicon glyphicon-cog'></span> &nbsp;Settings</a></li>
			<li><a href="#"><span class='glyphicon glyphicon-refresh'></span> &nbsp;Update</a></li>
		</ul>

</div>