<div class="container-flue-id">
    <?php echo $this->partial('admin/partial/_jobseeker_menu.phtml'); ?>
    <div class='col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main'>
        <div class='page-header'>
            <div class='row'>
                <div class='col-md-3'><h1 class='text-warning'>Resume</h1></div>
                <div class="col-md-9"><a href="<?php echo $this->url('admin-resume-new')?>" class="btn btn-success pull-right">New Resume</a></div>
            </div>
        </div>
        <div class='row'>
            <div class='container-fluid'>
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <tr>
                            <th>No</th>
                            <th>Name</th>
                            <th>Current Position</th>
                            <th>Apply For</th>
                            <th>Salary</th>
                            <th>Posting Date</th>
                            <th>Status</th>
                            <th>Educations</th>
                            <th>Years</th>
                            <th>Action</th>
                        </tr>
                        <?php
                        $i=1;
                        foreach ( $resumeData as $key => $row ) {?>
                            <tr>
                                <td><?php echo $i?></td>
                                <td><?php echo $row['username']?></td>
                                <td><?php echo $row['resu_current_position']?></td>
                                <td><?php echo $row['resu_position']?></td>
                                <td><?php echo $row['resu_salary']?></td>
                                <td><?php echo $row['resu_posting_date']?></td>
                                <td><?php if($row['resu_status']==0) echo 'Inactive'; else echo 'Active';?></td>
                                <td> <a href="<?php echo $this->url('admin-resume-education')?>?resumeId=<?php echo $row['resume_id']?>"><span class='icon-edit glyphicon glyphicon-pencil'></span></a></td>
                                <td><a href="<?php echo $this->url('admin-resume-year')?>?resumeId=<?php echo $row['resume_id']?>"><span class='icon-edit glyphicon glyphicon-pencil'></span></a></td>
                                <td><a href="<?php echo $this->url('admin-resume-editing')?>?resumeId=<?php echo $row['resume_id']?>"><span class='icon-edit glyphicon glyphicon-pencil'></span></a> |
                                    <a href='#' title='Remove'><span data-remove='<?php echo $row['resume_id']?>'  class='icon-remove glyphicon glyphicon-remove'></span></a></td>
                            </tr>
                            <?php $i++; } ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function(){
        $('.icon-remove').on('click',function(){
            var resumeId = $(this).attr('data-remove');
            if(resumeId != '')
            {
                if(confirm('Are you sure to delete?'))
                {
                    var url ='<?php echo $this->url('admin-resume-delete')?>?resumeId='+resumeId;
                    $.ajax({url: url, success:function(){window.location.href='';}});
                }
                return false;
            }
        });
    });

</script>

