<?php $search = $this->getParams('search');?>
<div class="container-flue-id">
    <?php echo $this->partial('admin/partial/_jobseeker_menu.phtml'); ?>
    <div class='col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main'>
        <div class='page-header'>
            <form method="get">
                <div class='row'>
                    <div class="col-md-3"><h3 class="text-warning" style="margin-top:0px;">Job Search </h3></div>
                    <div class="col-md-7"><input type="text" name="search" class="form-control" placeholder="Keyword here..." value="<?php echo $search?>"></div>
                    <div class="col-md-2"><button type="submit" class="btn btn-default">Search</button></div>
                </div>
            </form>
        </div>
        <div class='row'>
            <div class='container-fluid'>
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <tr>
                            <th>No</th>
                            <th>Position</th>
                            <th>Company</th>
                            <th>Location</th>
                            <th>Close Date</th>
                        </tr>
                        <?php
                        $i=1;
                        foreach ( $this->jobData as $key => $row ) {?>
                            <tr>
                                <td><?php echo $i?></td>
                                <td><?php echo $row['job_name']?></td>
                                <td><?php echo $row['com_name']?></td>
                                <td><?php echo $row['city_name']?></td>
                                <td><?php echo $row['job_close_date']?></td>
                            </tr>
                            <?php $i++; } ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


