<div class="container">
    <div class="row">
        <div class="col-md-3">
            <?php echo $this->partial('admin/partial/_jobseeker_menu.phtml'); ?>
        </div>
        <div class="col-md-9">
            <div class="row bg-title">
                <div class="col-md-3"><h3 class="text-warning"> &ensp;New Resume</h3></div>
                <div class="col-md-9"><button type="button" class="btn btn-success pull-right" style="margin-top: 10px;"> Save</button></div></div>
            <div class="row">

            </div>
        </div>

    </div>
</div>


