<div class="container">
    <div class="row">
        <div class="col-md-3">
            <?php echo $this->partial('admin/partial/_jobseeker_menu.phtml'); ?>
        </div>
        <div class="col-md-9">
            <div class="row">
                <div class="col-md-3"> <label>Personal Infomation</label></div>

            </div>
            <div class="row">
                <div class="col-md-3"><label>Full Name </label></div>
                <div class="col-md-6">: John Smith</div>
            </div>
        </div>
    </div>
</div>
