<div class="container">
    <div class="row">
        <div class="col-md-3">
            <?php echo $this->partial('admin/partial/_jobseeker_menu.phtml'); ?>
        </div>
        <div class="col-md-9">
            <div class="row bg-title">
                <div class="col-md-6"><h3 class="text-warning"> &ensp;Resume Years Experience</h3></div>
                <div class="col-md-6">
                    <a href="<?php echo $this->url('admin-job-seeker')?>" class="btn btn-default pull-right" style="margin-top: 10px;"> Back</a>
                    <a href="<?php echo $this->url('admin-resume-newyear')?>?resumeId=<?php echo $this->resumeId;?>" class="btn btn-success pull-right" style="margin-top: 10px;margin-right: 5px;">New Experience</a>
                </div>
            </div>
            <div class="row">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered">
                        <tr class="bg-title">
                            <th>Year</th>
                            <th>Description</th>
                            <th>Action</th>
                        </tr>
                        <?php
                        foreach ( $this->yearData as $key => $row ) {?>
                            <tr>
                                <td><?php echo $row['exp_title']?></td>
                                <td><?php echo $row['exp_detail']?></td>
                                <td><a href="<?php echo $this->url('admin-resume-edityear')?>?expId=<?php echo $row['exp_id']?>&resumeId=<?php echo $this->resumeId;?>"><span class='icon-edit glyphicon glyphicon-pencil'></span></a> |
                                    <a href='#' title='Remove'><span data-remove='<?php echo $row['exp_id']?>'  class='icon-remove glyphicon glyphicon-remove'></span></a></td>
                            </tr>
                            <?php } ?>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>
<script>
    $(function(){
        $('.icon-remove').on('click',function(){
            var expId = $(this).attr('data-remove');
            if(expId != '')
            {
                if(confirm('Are you sure to delete?'))
                {
                    var url ='<?php echo $this->url('admin-resume-deleteyear')?>?expId='+expId;
                    $.ajax({url: url, success:function(){window.location.href='';}});
                }
                return false;
            }
        });
    });

</script>

