<div class="row-fluid box-admin-main">
    <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    <div class='col-md-10 box-admin-right'>
        <div class='row box-row-title'>
            <div class='col-md-8'><h4 class='text-warning'>Job Viewing</h4></div>
            <div class='col-md-4 text-right'></div>
        </div>
        <br>
        <div class='row'>
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered">
                        <tr class="box-row-title">
                            <th>No</th>
                            <th>Position</th>
                            <th>Hiring No</th>
                            <th>Posting Date</th>
                            <th>Location</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        <?php
                        $i=1;
                        foreach ( $jobData as $key => $row ) {?>
                            <tr>
                                <td><?php echo $i?></td>
                                <td><?php echo $row['job_name']?></td>
                                <td><?php echo $row['job_hiring_number']?></td>
                                <td><?php echo $row['job_published_date']?></td>
                                <td><?php echo $row['city_name']?></td>
                                <td><?php if($row['job_status']==1)echo 'Active'; else echo 'Expire';?></td>
                                <td><a href="<?php echo $this->url('job-editing')?>?job_id=<?php echo $row['job_id']?>"><span class='icon-edit glyphicon glyphicon-pencil'></span></a> |
                                    <a href='#' title='Remove'><span data-remove='<?php echo $row['job_id']?>'  class='icon-remove glyphicon glyphicon-remove'></span></a></td>
                            </tr>
                            <?php $i++; }?>
                    </table>
                    <?php echo $this->paginationControl($this->jobData,'Sliding','admin/partial/my_pagination_control.phtml'); ?>
                </div>
            </div>
        </div>
        <br>
    </div>
</div>
<script>
    $(function(){
        $('.icon-remove').on('click',function(){
           var jobId = $(this).attr('data-remove');
            if(jobId != '')
            {
                if(confirm('Are you sure to delete?'))
                {
                    var url ='<?php echo $this->url('job-delete')?>?jobId='+jobId;
                    $.ajax({url: url, success:function(){window.location.href='';}});
                }
                return false;
            }
        });
    });

</script>

