<div class="row-fluid box-admin-main">
    <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    <div class='col-md-10 box-admin-right'>
        <div class='row box-row-title'>
            <form method="get">
            <div class='col-md-2'><h4 class='text-warning'>Resume Search</h4></div>
            <div class="col-md-7"><input type="text" name="search" class="form-control margin-top-2" placeholder="Search here..."></div>
            <div class="col-md-3 text-right"><button type="submit" class="btn btn-info margin-top-2 col-md-12"><span class="glyphicon glyphicon-search pull-left"></span>Search</button></div>
            </form>
        </div>
        <br>
        <div class='row'>
            <div class='col-md-12'>
                <div class="table-responsive">
                    <table class="table table-hover table-bordered">
                        <tr class="box-row-title">
                            <th>No</th>
                            <th>Name</th>
                            <th>Current Position</th>
                            <th>Apply For</th>
                            <th>Salary</th>
                            <th>Resume</th>
                            <th>Purchase</th>
                        </tr>
                        <?php
                        $i=1;
                        foreach ( $resumeData as $key => $row ) {?>
                            <tr>
                                <td><?php echo $i?></td>
                                <td><?php echo $row['user_id']?></td>
                                <td><?php echo $row['resu_current_position']?></td>
                                <td><?php echo $row['resu_position']?></td>
                                <td><?php echo $row['resu_salary']?></td>
                                <td><a href="<?php echo $this->url('resume-view')?>?resumeId=<?php echo $row['resume_id']?>"> View</a></td>
                                <td><a href="#"><span class="glyphicon glyphicon-shopping-cart purchase"></span></a></td>
                            </tr>
                            <?php $i++; }?>
                    </table>
                    <?php echo $this->paginationControl($this->resumeData,'Sliding','admin/partial/my_pagination_control.phtml'); ?>
                </div>
            </div>
        </div>
        <br>
    </div>
</div>

<script>
    $(function(){
        $('.icon-remove').on('click',function(){
            var jobId = $(this).attr('data-remove');
            if(jobId != '')
            {
                if(confirm('Are you sure to delete?'))
                {
                    var url ='<?php echo $this->url('job-delete')?>?jobId='+jobId;
                    $.ajax({url: url, success:function(){window.location.href='';}});
                }
                return false;
            }
        });
        $('.purchase').on('click',function(){
            alert(0);
        });
    });
</script>

