<div class="row-fluid box-admin-main">
    <div class="col-md-2 padding-left-0">
        <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    </div>
    <div class='col-md-10 box-admin-right'>
        <div class='row box-row-title'>
            <form method="get">
                <div class='col-md-2'><h4 class='text-warning'>Resume Request</h4></div>
                <div class="col-md-7"><input type="text" name="search" class="form-control margin-top-2" placeholder="Search here..."></div>
                <div class="col-md-3 text-right"><button type="submit" class="btn btn-info margin-top-2 col-md-12"><span class="glyphicon glyphicon-search pull-left"></span>Search</button></div>
            </form>
        </div>
        <br>
        <div class='row'>
            <div class='col-md-12'>
                <div class="table-responsive">
                    <table class="table table-hover table-bordered">
                        <tr class="box-row-title">
                            <th>No</th>
                            <th>Name</th>
                            <th>Current Position</th>
                            <th>Apply For</th>
                            <th>Salary</th>
                            <th>Resume</th>
                            <th>Approval</th>
                        </tr>
                        <?php
                        $i=1;
                        foreach ( $resumeData as $key => $row ) { $checked="";if($row["resu_status"]==1) $checked="checked";?>
                            <tr>
                                <td><?php echo $row['resume_id']?></td>
                                <td><?php echo $row['user_first_name']."  ".$row["user_last_name"]?></td>
                                <td><?php echo $row['resu_current_position']?></td>
                                <td><?php echo $row['resu_position']?></td>
                                <td><?php echo $row['resu_salary']?></td>
                                <td><a href="<?php echo $this->url('resume-request-view')?>?resumeId=<?php echo $row['resume_id']?>"> View</a></td>
                                <td><input resumeId=<?php echo $row['resume_id']?> type="checkbox" class="approval" <?php echo $checked?>></td>
                            </tr>
                            <?php $i++; }?>
                    </table>
                    <?php echo $this->paginationControl($this->resumeData,'Sliding','admin/partial/my_pagination_control.phtml'); ?>
                </div>
            </div>
        </div>
        <br>
    </div>
</div>

<script>
    $(function(){
        $('.approval').click(function(){
            if(confirm("Are you sure to approval this resume?")){
                resumeId = $(this).attr('resumeId');
                ch ="0";
                if($(this).is(":checked"))
                {
                    ch="1";
                }
                url='<?php echo $this->url('approvalresume')?>?resumeId='+resumeId+'&ch='+ch;
                $.ajax({
                    url:url,
                    success:function(){
                        window.location.href='';
                    }
                });
            }
        });
    });
</script>