<div class="row-fluid box-admin-main">
    <div class="col-md-2 padding-left-0">
        <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    </div>
    <div class='col-md-10 box-admin-right'>
        <div class='row box-row-title'>
            <div class='col-md-9'><h4 class='text-warning'>Resume Purchase</h4></div>
        </div>
        <br>
        <div class='row'>
            <div class='col-md-12'>
                Resume Purchase
            </div>
        </div>
        <br>
    </div>
</div>



