<?php
    foreach($this->resumeData as $row){
        $name = $row['username'];
        $current_position = $row['resu_current_position'];
        $position_apply = $row['resu_position'];
        $salary = $row['resu_salary'];
        $schedule = $row['resu_schedule'];
        $age = $row['resu_age'];
        $gender = $row['resu_gender'];
        $experience = $row['resu_year_experience'];
        $language = $row['resu_language'];
        $interest = $row['resu_interesting'];
        $skill = $row['resu_skill'];
    }
?>
<div class="container-fluid bg">
    <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    <div class='col-md-10 main'>
        <div class='page-header'>
            <div class='row'>
                <div class='col-md-8'><h1 class='text-warning'>Resume Detail</h1></div>
                <div class='col-md-4 text-right'></div>
            </div>
        </div>
        <div class='row'>
            <div class='container-fluid'>
                <div class="row"><div class="col-md-3 text-right"><label>Name:</label></div><div class="col-md-9">: <?php echo $name?></div></div>
                <div class="row"><div class="col-md-3 text-right"><label>Current Position</label></div><div class="col-md-9">: <?php echo $current_position?></div></div>
                <div class="row"><div class="col-md-3 text-right"><label>Apply For</label></div><div class="col-md-9">: <?php echo $position_apply?></div></div>
                <div class="row"><div class="col-md-3 text-right"><label>Salary</label></div><div class="col-md-9">: <?php echo $salary?></div></div>
                <div class="row"><div class="col-md-3 text-right"><label>Schedule</label></div><div class="col-md-9">: <?php echo $schedule?></div></div>
                <div class="row"><div class="col-md-3 text-right"><label>Age</label></div><div class="col-md-9">: <?php echo $age?></div></div>
                <div class="row"><div class="col-md-3 text-right"><label>Gender</label></div><div class="col-md-9">: <?php echo $gender?></div></div>
                <div class="row"><div class="col-md-3 text-right"><label>Experience</label></div><div class="col-md-9">: <?php echo $experience?></div></div>
                <div class="row"><div class="col-md-3 text-right"><label>Language</label></div><div class="col-md-9">: <?php echo $language?></div></div>
                <div class="row"><div class="col-md-3 text-right"><label>Interesting</label></div><div class="col-md-9">: <?php echo $interest?></div></div>
                <div class="row"><div class="col-md-3 text-right"><label>Skill</label></div><div class="col-md-9">: <?php echo $skill?></div></div>
            </div>
        </div>
    </div>
</div>


