<div class="row-fluid box-admin-main">
    <div class="col-md-3 padding-left-0">
        <?php echo $this->partial('admin/partial/_left.phtml'); ?>
    </div>
    <div class='col-md-9 box-admin-right'>
        <div class='row box-row-title'>
            <div class='col-md-9'><h4 class='text-warning'>Resume Purchase</h4></div>
        </div>
        <br>
        <div class='row'>
            <div class='col-md-12'>
                <div class="table-responsive">
                    <table class="table table-hover table-bordered">
                        <tr class="box-row-title">
                            <th>No</th>
                            <th>User Purchase name</th>
                            <th>Sex</th>
                            <th>Tel</th>
                            <th>Date Purchase</th>
                            <th>View Resume</th>
                        </tr>
                        <?php
                        $i=1;
                        foreach ( $this->purchaseData as $key => $row ) {?>
                            <tr>
                                <td><?php echo $row['employer_resume_id']?></td>
                                <td><?php echo $row['user_first_name']."  ".$row["user_last_name"]?></td>
                                <td align="center"><?php echo $row['user_gender']?></td>
                                <td align="center"><?php echo $row['user_phone']?></td>
                                <td align="center"><?php echo $row['purchase_date']?></td>
                                <td align="center"><a href="<?php echo $this->url('resume-view').'?resumeId='.$row['resume_id']?>"> View </a> </td>
                            </tr>
                            <?php $i++; }?>
                    </table>
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <?php echo $this->paginationControl($this->purchaseData,'Sliding','admin/partial/my_pagination_control.phtml'); ?>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <br>
    </div>
</div>



