<?php
$resultSet = new \Zend\Db\ResultSet\ResultSet();
$categories = $resultSet->initialize($this->categories);
?>
<div class="clearfix margin-10-0 font-13 nav nav-tabs" role="tablist">

    <aside class="all-cate box-white border-radius-5 w70">
        <div class="clearfix col-md-12">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs clearfix margin-15-0 border-bottom-blue" role="tablist">
            <li class="active"><a href="#category" role="tab" data-toggle="tab"><?php echo $this->translate("Job Categories"); ?></a></li>
            <li><a href="#location" role="tab" data-toggle="tab"><?php echo $this->translate("Location"); ?></a></li>
            <li><a href="#messages" role="tab" data-toggle="tab"><?php echo $this->translate("Industry");?></a></li>
            <li><a href="#settings" role="tab" data-toggle="tab"><?php echo $this->translate("Salary");?></a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content" >
            <div class="tab-pane fade in active" id="category">
                <?php
                $cateList = '';
                $asideList = '';
                $perColumn = round($categories->count() / 3);
                $add=1;

                for($i=1; $i<=3; $i++){
                    if(($categories->count() % 3) <> 0){
                        if($i > ($categories->count() % 3) ){
                            $add=0;
                        }
                    }
                    if($i==1){
                        $asideList = '<aside class="col-md-4 no-padding-left border-right-gray "><ul>';
                    }elseif($i == 2){
                        $asideList = '<aside class="col-md-4 border-right-gray"><ul>';
                    }else{
                        $asideList = '<aside class="col-md-4 no-padding-right"><ul>';
                    }
                    $j = 1;
                    foreach($categories as $k=>$v){
                        if($j > (($i-1) * ($perColumn+$add))  &&  $j <= ($i * ($perColumn+$add))){
                            $asideList .='<li class="full-w clearfix"><a href="'.$this->basepath()."/category/?c=".$v["category_id"].'" class="pull-left color-black">'.$v["cate_name"].'</a><label class="pull-right">('.$v["num"].')</label></li>';
                        }
                        $j++;
                    }
                    $cateList .= $asideList .'</ul></aside>';
                }
                echo $cateList;
                ?>
            </div>
            <div class="tab-pane fade" id="location">
                <?php  echo $this->partial("application/index/_location"); ?>
            </div>
            <div class="tab-pane fade" id="messages">

                <?php
                $cateList = '';
                $asideList = '';
                $perColumn = round($categories->count() / 3);
                $add=1;

                for($i=1; $i<=3; $i++){
                    if(($categories->count() % 3) <> 0){
                        if($i > ($categories->count() % 3) ){
                            $add=0;
                        }
                    }
                    if($i==1){
                        $asideList = '<aside class="col-md-4 no-padding-left border-right-gray "><ul>';
                    }elseif($i == 2){
                        $asideList = '<aside class="col-md-4 border-right-gray"><ul>';
                    }else{
                        $asideList = '<aside class="col-md-4 no-padding-right"><ul>';
                    }
                    $j = 1;
                    foreach($categories as $k=>$v){
                        if($j > (($i-1) * ($perColumn+$add))  &&  $j <= ($i * ($perColumn+$add))){
                            $asideList .='<li class="full-w clearfix"><a href="'.$this->basepath()."/category/?c=".$v["category_id"].'" class="pull-left color-black">'.$v["cate_name"].'</a><label class="pull-right">('.$v["num"].')</label></li>';
                        }
                        $j++;
                    }
                    $cateList .= $asideList .'</ul></aside>';
                }
                echo $cateList;
                ?>
            </div>
            <div class="tab-pane fade" id="settings">d</div>
        </div>
        </div>
    </aside>
    <aside class="col-lg-4 newest-job box-white border-radius-5" style="width:28%;">
        <menu class="no-padding border-bottom-gray font-16 padding-5-0">
            Job Announcement
        </menu>
        <ul class="newest-panel"></ul>
        <div class="row more full-w">
            <button class="btn btn-default col-lg-12 border-radius-0 no-border-left no-border-right" style="position:relative; top:7px;">
                <i class="glyphicon glyphicon-chevron-down color-pink"></i>
            </button>
        </div>
    </aside>
</div>




