<?php
$resultSet = new \Zend\Db\ResultSet\ResultSet();
$categories = $resultSet->initialize($this->categories);
?>
<div class="box-white clearfix border-radius-5 margin-10-0 font-13 nav nav-tabs" role="tablist">
    <aside class="col-lg-9 border-right-gray  ">
        <menu class="menu-invers no-padding border-bottom-blue full-w">
            <a class="bg-white active actived" href="#" role="tab"><?php echo $this->translate("Job Categories"); ?></a>
            <a class="bg-white" href="#"><?php echo $this->translate("Location"); ?></a>
            <a class="bg-white" href="#"><?php echo $this->translate("Industry");?></a>
            <a class="bg-white" href="#"><?php echo $this->translate("Salary");?></a>
        </menu>
        <div>
            <?php
                $cateList = '';
                $asideList = '';
                $perColumn = round($categories->count() / 3);
                if($categories->count() % 3 <> 0) $perColumn++;

                for($i=1; $i<=3; $i++){
                    if($i==1){
                        $asideList = '<aside class="col-md-4 no-padding-left border-right-gray"><ul>';
                    }elseif($i == 2){
                        $asideList = '<aside class="col-md-4 border-right-gray"><ul>';
                    }else{
                        $asideList = '<aside class="col-md-4 no-padding-right"><ul>';
                    }
                    $j = 1;
                    foreach($categories as $k=>$v){
                        if($j > (($i-1) * $perColumn)  &&  $j <= ($i * $perColumn)){
                           $asideList .='<li class="full-w clearfix"><a href="'.$this->basepath()."/category/".$v["category_id"].'" class="pull-left">'.$v["cate_name"].'</a><label class="pull-right">('.$v["category_id"].')</label></li>';
                        }
                        $j++;
                    }
                    $cateList .= $asideList .'</ul></aside>';
                }
                echo $cateList;
            ?>
        </div>

        <ul class="nav nav-tabs" role="tablist">

        </ul>
    </aside>
    <aside class="col-lg-3">
        <menu class="no-padding border-bottom-gray font-16 padding-5-0">
            Job Announcement
        </menu>
        <ul>
            <li class="text-overflow"><a class="pull-left">Branch Director </a>  - This is a place to display</li>
            <li class="text-overflow"><a>Maintenance Technician </a> - This is a place to display company name.</li>
            <li class="text-overflow"><a>Sale indoor 2 position </a> - This is a place to display company name.</li>
            <li class="text-overflow"><a>Assistance account </a>- This is a place to display company name.</li>
            <li class="text-overflow"><a>Cashier </a> - This is a place to display company name.</li>
            <li class="text-overflow"><a>Public Relation Manager </a> - This is a place to display company name.</li>
            <li class="text-overflow"><a>Branch Director </a> - This is a place to display company name.</li>
            <li class="text-overflow"><a>Branch Director </a> - This is a place to display company name.</li>
            <li class="text-overflow"><a>Branch Director </a> - This is a place to display company name.</li>
            <li class="text-overflow"><a>Branch Director </a>- This is a place to display company name.</li>
            <li class="text-overflow"><a>Assistance account </a>- This is a place to display company name.</li>
        </ul>
        <div class="row pos-relative">
            <button class="btn btn-default col-lg-12 border-radius-0 no-border-left no-border-right" style="position:relative; top:7px;">
                <i class="glyphicon glyphicon-chevron-down color-pink"></i>
            </button>
        </div>
    </aside>


</div>

