<div class="box-white border-radius-5 clearfix margin-top-10 doc-share-panel">
    <aside class="col-md-9 border-right-gray">
        <header class="font-16 color-light-black padding-10-0 border-bottom-gray">
            Document Share
        </header>
        <div class="margin-10-0 row font-13 padding-5-0">
            <aside class="col-md-4">
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="<?php echo $this->basePath(); ?>/img/no-img.png" alt="..." width="64">
                    </a>
                    <div class="media-body">
                        <h5 class="media-heading">Document share one</h5>
                        Cras sit amet nibh libero, in gravida nulla.
                    </div>
                </div>
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="<?php echo $this->basePath(); ?>/img/no-img.png" alt="..." width="64">
                    </a>
                    <div class="media-body">
                        <h5 class="media-heading">Document share one</h5>
                        Cras sit amet nibh libero, in gravida nulla.
                    </div>
                </div>
            </aside>
            <aside class="col-md-4">
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="<?php echo $this->basePath(); ?>/img/no-img.png" alt="..." width="64">
                    </a>
                    <div class="media-body">
                        <h5 class="media-heading">Document share one</h5>
                        Cras sit amet nibh libero, in gravida nulla.
                    </div>
                </div>
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="<?php echo $this->basePath(); ?>/img/no-img.png" alt="..." width="64">
                    </a>
                    <div class="media-body">
                        <h5 class="media-heading">Document share one</h5>
                        Cras sit amet nibh libero, in gravida nulla.
                    </div>
                </div>
            </aside>
            <aside class="col-md-4">
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="<?php echo $this->basePath(); ?>/img/no-img.png" alt="..." width="64">
                    </a>
                    <div class="media-body">
                        <h5 class="media-heading">Document share one</h5>
                        Cras sit amet nibh libero, in gravida nulla.
                    </div>
                </div>
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="<?php echo $this->basePath(); ?>/img/no-img.png" alt="..." width="64">
                    </a>
                    <div class="media-body">
                        <h5 class="media-heading">Document share one</h5>
                        Cras sit amet nibh libero, in gravida nulla.
                    </div>
                </div>
            </aside>
        </div>
    </aside>
    <aside class="col-md-3 latest-edu">
        <menu class="no-padding border-bottom-gray font-16 padding-10-0 no-margin">
            Job Announcement
        </menu>
        <ul class="edu-panel"></ul>
        <div class="row more full-w">
            <button class="btn btn-default col-lg-12 border-radius-0 no-border border-radius-bottom-5" style="position:relative; top:7px; border-top:#ccc solid 1px;">
                <i class="glyphicon glyphicon-chevron-down color-pink"></i>
            </button>
        </div>
    </aside>
</div>