<div class="box-white border-radius-5 clearfix margin-top-10 doc-share-panel">
    <aside class="p-15">
        <header class="font-16 color-light-black padding-10-0 border-bottom-gray">
            Document Share
            <a href="<?php echo $this->basepath()."/document-share";?>" class="pull-right font-13">View all <i class="glyphicon glyphicon-chevron-right"></i></a>
        </header>
        <div class="margin-10-0 row font-13 padding-5-0">
            <?php foreach($this->document as $k=>$v):?>
            <aside class="col-md-4 margin-top-10">
                <div class="media">
                    <a class="pull-left" href="<?php echo $this->basepath()."/document-share/".$v["share_id"];?>">
                        <span class="media-object" style="background-image: url('<?php echo $this->basepath() ."/img/share/".$v["shar_img"] ?>'); background-position: center; background-repeat: no-repeat; background-size:cover; width:60px; height:50px;"></span>
                    </a>
                    <div class="media-body">
                        <h5 class="media-heading" title="<?php echo $v["shar_title"]; ?>"><?php echo substr($v["shar_title"],0,25)." ..."; ?></h5>
                        <?php //echo substr(strip_tags($v["shar_detail"]),0,30)." ..."; ?>
                    </div>
                </div>
            </aside>
                <?php if(($k+1)%3==0) echo "<div class='padding-5-0' style='clear: both;'></div>" ?>
            <?php endforeach; ?>
        </div>
    </aside>
</div>