<div class="box-white border-radius-5 clearfix margin-top-10 doc-share-panel">
    <aside class="p-15">
        <header class="font-16 color-light-black padding-10-0 border-bottom-gray">
            Document Share
            <a href="<?php echo $this->basepath()."/document-share";?>" class="pull-right font-13">View all <i class="glyphicon glyphicon-chevron-right"></i></a>
        </header>
        <div class="margin-10-0 row font-13 padding-5-0">
            <aside class="col-md-4">
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="<?php echo $this->basePath(); ?>/img/no-img.png" alt="..." width="64">
                    </a>
                    <div class="media-body">
                        <h5 class="media-heading">Document share one</h5>
                        Cras sit amet nibh libero, in gravida nulla.
                    </div>
                </div>
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="<?php echo $this->basePath(); ?>/img/no-img.png" alt="..." width="64">
                    </a>
                    <div class="media-body">
                        <h5 class="media-heading">Document share one</h5>
                        Cras sit amet nibh libero, in gravida nulla.
                    </div>
                </div>
            </aside>
            <aside class="col-md-4">
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="<?php echo $this->basePath(); ?>/img/no-img.png" alt="..." width="64">
                    </a>
                    <div class="media-body">
                        <h5 class="media-heading">Document share one</h5>
                        Cras sit amet nibh libero, in gravida nulla.
                    </div>
                </div>
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="<?php echo $this->basePath(); ?>/img/no-img.png" alt="..." width="64">
                    </a>
                    <div class="media-body">
                        <h5 class="media-heading">Document share one</h5>
                        Cras sit amet nibh libero, in gravida nulla.
                    </div>
                </div>
            </aside>
            <aside class="col-md-4">
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="<?php echo $this->basePath(); ?>/img/no-img.png" alt="..." width="64">
                    </a>
                    <div class="media-body">
                        <h5 class="media-heading">Document share one</h5>
                        Cras sit amet nibh libero, in gravida nulla.
                    </div>
                </div>
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="<?php echo $this->basePath(); ?>/img/no-img.png" alt="..." width="64">
                    </a>
                    <div class="media-body">
                        <h5 class="media-heading">Document share one</h5>
                        Cras sit amet nibh libero, in gravida nulla.
                    </div>
                </div>
            </aside>
        </div>
    </aside>
</div>