<menu class="no-padding border-bottom-gray font-16 padding-10-0 no-margin">
    News You May Read
</menu>
<ul class="edu-panel padding-10-0" style="height: 215px;">
    <?php foreach($this->education as $k=>$v): ?>
        <li class="text-overflow margin-5">
            <img width="30" class="img-thumbnail" alt="" src="/ourjob/public/img/user-login.png">
            <a href="<?php echo $this->basepath()."/education/detail/".$v["education_id"] ?>"> <?php echo $v["educ_title"]; ?></a></li>
    <?php endforeach; ?>
</ul>
<div class="more full-w" style="left:0">
    <button class="btn btn-default col-lg-12 border-radius-0 no-border border-radius-bottom-5 no-background" style="position:relative; top:7px; border-top:#ccc solid 1px;">
        <i class="glyphicon glyphicon-chevron-down color-pink"></i>
    </button>
</div>