<?php
$f = $this->feature;
?>
<div class="clearfix">
    <aside class="w70">
        <div class="box-white border-radius-5 p-15 feature-panel">
            <header class="font-16 color-light-black padding-10-0 border-bottom-gray">
                Featured Companies
            </header>
            <div class="margin-10-0 row font-13 padding-5-0">
                <?php for($i=0; $i<=17; $i++):
                    if($i<count($f)):
                    ?>
                    <div class="col-md-2 margin-10-0  text-center <?php if($i==0 || ($i+1) % 7==0) echo " "?> ">
                        <div class="full-w border-light-gray" style="height:70px; ">
                            <img class="margin-top-5" src="<?php echo $this->basePath()?>/img/featured/<?php echo $f[$i]["feat_image"]; ?>" style="max-height:60px; max-width:100%">
                        </div>
                    </div>
                    <?php else: ?>
                    <div class="col-md-2 margin-10-0 text-center <?php if($i==0 || ($i+1) %7==0) echo " "?> ">
                        <div class="full-w border-light-gray" style="height:70px; ">
                            <img class="margin-top-5" src="<?php echo $this->basePath()?>/img/no-img.png" style="max-height:60px; max-width:100%">
                        </div>
                    </div>

                    <?php endif; ?>


                <?php endfor;?>
            </div>

        </div>
        <?php echo $this->partial("application/index/_docshare"); ?>
    </aside>
    <aside class="w30">
        <div class="box-white border-radius-5 padding-10 clearfix adv-panel">
            <div>
                <div class="border-bottom-gray padding-bottom-11 font-16 margin-bottom-10">Payment Terms</div>
                <div class="clearfix">
                    <div class="col-md-5"><img style="width:30px;" src="<?php echo $this->basepath(); ?>/img/acleda.png"></div>
                    <label class="margin-top-5">Acleda Bank PLC.</label>
                </div>
                <div class="clearfix">
                    <div class="col-md-5"><img style="width:60px;" src="<?php echo $this->basepath(); ?>/img/logo-wing.png"></div>
                    <label class="margin-top-10">Wing Cambodia Ltd.</label>
                </div>
                <div class="clearfix">
                    <div class="col-md-5"><img style="width:30px;" src="<?php echo $this->basepath(); ?>/img/dollar.jpg"></div>
                    <label class="margin-top-5">Cash Payment</label>
                </div>
            </div>
        </div>

        <div class="box-white border-radius-5 latest-edu pos-relative p-10 clearfix margin-10-0">
            <?php echo $this->partial("application/index/_edu_share"); ?>
        </div>

    </aside>
</div>