<div class="clearfix">
    <aside class="w70">
        <div class="box-white border-radius-5 p-15">
            <header class="font-16 color-light-black padding-10-0 border-bottom-gray">
                Featured Companies
            </header>
            <div class="margin-10-0 row font-13 padding-5-0">
                <?php foreach($this->feature as $k=>$v):?>
                <div class="col-md-2 text-center <?php if($k==0 || $k+1 % 6==0) echo " no-padding-left"?> ">
                    <img  src="<?php echo $this->basePath()?>/img/company/<?php echo $v["com_logo"]; ?>" style="max-height:60px; max-width:100%">
                </div>
                <?php endforeach;?>
            </div>

        </div>
        <?php echo $this->partial("application/index/_docshare"); ?>
    </aside>
    <aside class="box-white border-radius-5 w30">
        <header class="font-16 color-white padding-10-0">.</header>
        <div>
            <img src="<?php echo $this->basePath()?>/img/promotion/1.png" class="col-md-12">
            <img src="<?php echo $this->basePath()?>/img/promotion/2.gif" class="col-md-12 margin-10-0">
        </div>
        <div class="lastest-edu pos-relative p-10 clearfix">
            <?php echo $this->partial("application/index/_edu_share"); ?>
        </div>

    </aside>
</div>