<?php
//$resultSet = new \Zend\Db\ResultSet\ResultSet();
//$locations = $resultSet->initialize($this->locations);
$locations = $this->locations;

$cateList = '';
$asideList = '';

$count = count($locations);
$perColumn = round(($count-($count%3)) / 3);
$add=0;
$j=0;
for($i=1; $i<=3; $i++){
    if(($count % 3) <> 0){
        if(($count % 3) >= $i){
            $add=1;
        }else{
            $add=0;
        }
    }
    if($i==1){
        $asideList = '<aside class="col-md-4 no-padding-left border-right-gray "><ul>';
    }elseif($i == 2){
        $asideList = '<aside class="col-md-4 border-right-gray"><ul>';
    }else{
        $asideList = '<aside class="col-md-4 no-padding-right"><ul>';
    }

    $column = array_slice($locations,$j,($perColumn+$add));
    foreach($column as $k=>$v){
        $asideList .='<li class="full-w clearfix"><a href="'.$this->basepath()."/home/location/".$v["city_id"].'" class="pull-left color-black">'.$v["city_name"].'</a><label class="pull-right">('.$v["num"].')</label></li>';
        $j++;
    }
    $cateList .= $asideList .'</ul></aside>';
}
echo $cateList;
?>