			<div class="col-md-4">
				<div>
					<image src="<?php echo $this->basepath(); ?>/img/portfolio/m/sarikar.png" width="335" />
					<p>
						<strong>Sarikar.com</strong> is a site that focus on play both khmer songs or international songs and including  with lyrics which make user excites the listening and singing during once time. 
					</p>
				</div> 
				<div>
					<image src="<?php echo $this->basepath(); ?>/img/portfolio/m/cambodia-supe-page.png" width="335" />
					<p>
						<strong>www.cambodiasuperpages.com</strong> is a directory of businesses classified by types of business in Cambodia and arranged alphabetically within each classification. 	
					</p>
				</div> 
			</div>