			<div class="col-md-4">
					<article class="">
						<aside class="col-md-1">1./</aside>
						<aside class="col-md-11">
							<span>why don't we use exec() in php do something?</span>
							<footer>
								<ul class="clearfix">
									<li class="orange li-view"><i class="s-icon view-icon"></i>7 Views</li>
									<li class="green li-comment"><i class="s-icon comt-icon"></i>3 Comments</li>
									<li class="blue li-like"><i class="s-icon like-icon"></i>3 Likes</li>
								</ul>
							</footer>
						</aside>
					</article>
					<article class="clearfix h02">
						<span>How to Make the iPhone 5 Battery Last Longer?</span>
						<footer>
							<ul>
								<li class="orange li-view"><i class="s-icon view-icon"></i>7 Views</li>
								<li class="green li-comment"><i class="s-icon comt-icon"></i>3 Comments</li>
								<li class="blue li-like"><i class="s-icon like-icon"></i>3 Likes</li>
							</ul>
						</footer>
					</article>
					<article class="clearfix h02">
						<span>10 Useful Apps to Recover a Lost or Stolen iPhone</span>
						<footer>
							<ul class="clearfix">
								<li class="orange li-view"><i class="s-icon view-icon"></i>7 Views</li>
								<li class="green li-comment"><i class="s-icon comt-icon"></i>3 Comments</li>
								<li class="blue li-like"><i class="s-icon like-icon"></i>3 Likes</li>
							</ul>
						</footer>
					</article>
					<article class="clearfix h02">
						<span>How to Subversion (SVN) on GoDaddy Shared Hosting?</span>
						<footer>
							<ul class="clearfix">
								<li class="orange li-view"><i class="s-icon view-icon"></i>7 Views</li>
								<li class="green li-comment"><i class="s-icon comt-icon"></i>3 Comments</li>
								<li class="blue li-like"><i class="s-icon like-icon"></i>3 Likes</li>
							</ul>
						</footer>
					</article>
					<article class="clearfix h02">
						<span>តើ Intel HD Graphics 4000 មានសម្ថភាពកំរិតណាសំរាប់ loptop ឬ  Pc របស់អ្នក?</span>
						<footer>
							<ul class="clearfix">
								<li class="orange li-view"><i class="s-icon view-icon"></i>7 Views</li>
								<li class="green li-comment"><i class="s-icon comt-icon"></i>3 Comments</li>
								<li class="blue li-like"><i class="s-icon like-icon"></i>3 Likes</li>
							</ul>
						</footer>
					</article>
					<article class="clearfix h02">
						<span>why don't we use exec() in php do something?</span>
					</article>
					<article class="clearfix">
						<span>why don't we use exec() in php do something?</span>
					</article>
			</div>