<div class="col-md-4">
<div class="cont01">
					<div class="h clearfix">
						<div class="h01"></div>
						<div class="h02">
							<header>
								<article>ACID Complaint</article>
								<time>July 2013</time>
							</header>
							<div class="sub-title">Atomicity, Consistency, Isolation, Durability</div>
							<footer>
								<ul>
									<li class="orange li-view"><i class="s-icon view-icon"></i>1 Views</li>
									<li class="green li-comment"><i class="s-icon comt-icon"></i>2 Comments</li>
									<li class="blue li-like"><i class="s-icon like-icon"></i>3 Likes</li>
								</ul>
							</footer>
						</div>
						<div class="h03">
							<div class="inner">
								<i class="m-icon db-icon"></i>
							</div>
						</div>
					</div>
					<p>
						In computer science, ACID (Atomicity, Consistency, Isolation, Durability) is a set of properties that guarantee that database transactions are processed reliably. 
					</p>
				</div> 
				
				<div class="cont01">
					<div class="h clearfix">
						<div class="h01"></div>
						<div class="h02">
							<header>
								<article>Using Indexes</article>
								<time>July 2013</time>
							</header>
							<div class="sub-title">Index table to speed up searching.</div>
							<footer>
								<ul>
									<li class="orange li-view"><i class="s-icon view-icon"></i>7 Views</li>
									<li class="green li-comment"><i class="s-icon comt-icon"></i>3 Comments</li>
									<li class="blue li-like"><i class="s-icon like-icon"></i>5 Likes</li>
								</ul>
							</footer>
						</div>
						<div class="h03">
							<div class="inner">
								<i class="m-icon db-icon"></i>
							</div>
						</div>
					</div>
					<p>
						To speed up searches and reduce query execution time, MySQL lets you index particular fields of a table. 
						The term "index" here means much the same as in the real world. 
						Similar in concept to the index you find at the end of a book, index is a list of sorted field values used to simplify the task of locating specific records in response to queries. 
					</p>
				</div> 
			</div>