<div class="box-white border-radius-5 margin-10-0 clearfix">
    <aside class="col-md-9 ">
        <header class="font-16 color-light-black padding-10-0 border-bottom-gray">
            Job :: Accounting/Audit/Tax Service
        </header>

        <div class="margin-10-0 row padding-5-0">
            <div class="table-responsive">
                <table class="table table-hover table-bordered">
                    <tr class="bg-gray">
                        <th class="text-center">No</th>
                        <th>Position</th>
                        <th>Company</th>
                        <th>Location</th>
                        <th>Close date</th>
                    </tr>
                    <?php
                    $i=1;
                    foreach ( $this->paginator as $key => $row ) {?>
                        <tr class="tr-job" href="<?php echo $this->basePath() ."/jobdt/?job=" .$row["job_id"]; ?>">
                            <td class="text-center"><?php echo $i?></td>
                            <td><?php echo $row['job_name']?></td>
                            <td><?php echo $row['com_name']?></td>
                            <td><?php echo $row['city_name']?></td>
                            <td class="color-red"><?php echo date("d-M-Y", strtotime($row["job_close_date"])); ?></td>

                        </tr>
                        <?php $i++; }?>
                </table>
            </div>
            <div class="text-center"> <?php echo $this->paginationControl($this->paginator,'sliding',array('layout/_paginator.phtml','viewmore'),array('controller' => 'Index','category'=>$this->category));?> </div>
        </div>

    </aside>
    <aside class="col-md-3">
        <header class="font-16 color-white padding-10-0">.</header>
        <div>
            <img src="<?php echo $this->basePath()?>/img/promotion/1.png" class="col-md-12">
            <img src="<?php echo $this->basePath()?>/img/promotion/2.gif" class="col-md-12 margin-10-0">
        </div>
    </aside>
</div>
<script>
    $('.tr-job').click(function(){
        href =  $(this).attr('href');
        window.location = href;
    });

</script>
