<div class="box-white border-radius-5 margin-10-0 clearfix">
    <aside class="col-md-10 ">
        <header class="font-16 color-light-black padding-10-0 border-bottom-gray">
            Job :: <?php echo $this->cateDetail["cate_name"]; ?>
        </header>

        <div class="margin-10-0 row padding-5-0">
            <div class="table-responsive">
                <table class="table table-hover table-bordered">
                    <tr class="bg-gray">
                        <th class="text-center">No</th>
                        <th>Position</th>
                        <th>Company</th>
                        <th>Location</th>
                        <th>Close date</th>
                    </tr>
                    <?php
                    $i=1;
                    foreach ( $this->paginator as $key => $row ) {
                        $jobStatus = "";
                        if($row["job_status"] == 1){
                            $jobStatus = ' <span class="color-red font-10 up-10">Urgent</span>';
                        }elseif($row["job_status"] == 2){
                            $jobStatus = ' <span class="color-yellow font-10 up-10">New</span>';
                        }
                        ?>
                        <tr class="tr-job" href="<?php echo $this->basePath() ."/jobdt/?job=" .$row["job_id"]; ?>">
                            <td class="text-center"><?php echo $i?></td>
                            <td><?php echo $row['job_name'] . $jobStatus ?></td>
                            <td><?php echo $row['com_name']?></td>
                            <td><?php echo $row['city_name']?></td>
                            <td class="color-red"><?php echo date("d-M-Y", strtotime($row["job_close_date"])); ?></td>

                        </tr>
                        <?php $i++; }?>
                </table>
            </div>
            <div class="text-center"> <?php echo $this->paginationControl($this->paginator,'sliding',array('layout/_paginator.phtml','viewmore'),array('controller' => 'Index','category'=>$this->category));?> </div>
        </div>

    </aside>
    <aside class="col-md-2 no-padding-left">
        <header class="font-16 color-white padding-10-0">.</header>
        <div>
            <?php foreach($this->advs as $k=>$v): ?>
            <img src="<?php echo $this->basePath()?>/img/promotion/<?php echo $v["adv_image"] ?>" class="col-md-12 no-padding">
            <?php endforeach; ?>
        </div>
    </aside>
</div>
<script>
    $('.tr-job').click(function(){
        href =  $(this).attr('href');
        window.location = href;
    });

</script>
