<?php
$this->headLink ()->prependStylesheet ( $this->basePath () . '/css/home.css');
echo $this->partial("application/index/_category");
echo $this->partial("application/index/_feature");
//echo $this->partial("application/index/_docshare");

?>
<script>
    var urgentJob = <?php echo $this->urgentJob;?>;
    var currentUrgentId = null;
    var baseUrl = '<?php $this->basepath();?>';

    $(document).ready(function(){

        setInterval(function() {
            $('.newest-panel li:first').slideUp(200, function(){
                _this = this;
                $(this).remove();
                $('.newest-panel').append(_this);
                $(_this).slideDown(200);
            });

            $('.edu-panel li:first').slideUp(200, function(){
                _this = this;
                $(this).remove();
                $('.edu-panel').append(_this);
                $(_this).slideDown(200);
            });
        }, 1500);


        h = $('.all-cate').height();
        $('.newest-job').height(h+2);
        h = $('.doc-share-panel').height();
        featureH = $('.feature-panel').height();
        advH = $('.adv-panel').height();
        $('.latest-edu').height(h+featureH-advH+11);

        //initialize urgent jobs
        $.each(urgentJob, function(k,v){
            $('.newest-panel').append('<li class="text-overflow"><a href="'+baseUrl+'/jobdt/?job='+ v.job_id+'">'+ v.job_name+' </a>- '+ v.com_info+'</li>');
        });
    });
</script>