<?php
$this->headLink ()->prependStylesheet ( $this->basePath () . '/css/application/detail.css');
if(isset($this->jobDetail)):
$job = $this->jobDetail;
    ?>
<div class="bg-gray border-gray margin-10-0 border-radius-5">
    <div class="border-radius-top-5 no-padding">
        <ol class="breadcrumb no-margin no-background">
            <li><a href="<?php echo $this->basepath(); ?>/"><i class="glyphicon glyphicon-home"></i> Home</a></li>
            <li><a href="<?php echo $this->basepath(); ?>/jobs/"> <i class="glyphicon glyphicon-briefcase"></i> Jobs </a></li>
            <li class="active"> <i class="glyphicon glyphicon-align-justify"></i> Job Detail </li>
        </ol>
    </div>
</div>

<div class="clearfix">
        <div class="w70 box-white border-radius-5 p-15">
            <header class="full-w clearfix">
                <h4 class="bold clearfix color-blue"><?php echo $job["job_name"]; ?></h4>
                <div class="col-md-6 padding-5-0">
                    <span class="col-md-12 no-padding-left"><b class="col-md-5">Location</b> <span> : <?php echo $job["city_name"];?></span> </span>
                    <span class="col-md-12 no-padding-left"><b class="col-md-5">Job Type</b> : <?php echo $job["job_schedule"]; ?></span>
                    <span class="col-md-12 no-padding-left"><b class="col-md-5">Hiring No.</b> : <?php echo $job["job_hiring_number"]; ?> position(s)</span>
                    <span class="col-md-12 no-padding-left"><b class="col-md-5">Salary</b> : <?php echo "$".$job["job_salary_from"] ." - " ."$".$job["job_salary_to"]; ?></span>
                </div>
                <div class="col-md-6 text-right">
                    <h4 class=""><?php echo $job["com_name"]; ?></h4>
                </div>
            </header>

            <div>
                <h4 class="padding-10-0 margin-10-0 border-bottom-gray font-16">Company Profile</h4>
                <div class="col-md-12">
                    <?php echo $job["com_info"]; ?>
                </div>
                <br><br>
                <h4 class="padding-10-0 margin-10-0 border-bottom-gray font-16">Responsibilities</h4>
                <div class="col-md-12">
                    <?php echo $job["job_duty"] ?>
                </div>
                <br><br>
                <h4 class="padding-10-0 margin-10-0 border-bottom-gray font-16">Requirements</h4>
                <div class="col-md-12 clearfix">
                    <?php echo $job["job_requirement"]; ?>
                </div>
            </div>
            <br><br>
            <h4 class="padding-10-0 margin-10-0 border-bottom-gray font-16 clearfix">How To Apply</h4>
            <p class="more-text-area col-md-12">
                <b>Phone</b>: Call between 9:00 ~ 16:00 Monday ~ Friday<br>
                <b>Contact Person:</b> Kakvei<br>
                <b>Phone:</b> 063-964-206, 088-592-0392<br>
                <b>Email:</b> recruit@skyrivers.net<br>
                <b>Address:</b> T40 Borey Prem Prey, Sang kat Kouk chork, Siem Reap<br>
                <b>Website:</b>http://www.skyrivers.net/</p>
            </p>

        </div>
        <div class="w30 box-white border-radius-5 p-15">
            <menu class="no-padding border-bottom-gray font-16 padding-5-0 no-margin">
                Related Jobs
            </menu>
            <ul class="padding-10-0">
                <li class="text-overflow"><a class="pull-left">Branch Director </a>  - This is a place to display</li>
                <li class="text-overflow"><a>Maintenance Technician </a> - This is a place to display company name.</li>
                <li class="text-overflow"><a>Sale indoor 2 position </a> - This is a place to display company name.</li>
                <li class="text-overflow"><a>Assistance account </a>- This is a place to display company name.</li>
                <li class="text-overflow"><a>Cashier </a> - This is a place to display company name.</li>
                <li class="text-overflow"><a>Public Relation Manager </a> - This is a place to display company name.</li>
                <li class="text-overflow"><a>Branch Director </a> - This is a place to display company name.</li>
                <li class="text-overflow"><a>Branch Director </a> - This is a place to display company name.</li>
                <li class="text-overflow"><a>Branch Director </a> - This is a place to display company name.</li>
                <li class="text-overflow"><a>Branch Director </a>- This is a place to display company name.</li>
                <li class="text-overflow"><a>Assistance account </a>- This is a place to display company name.</li>
            </ul>


            <menu class="no-padding border-bottom-gray font-16 padding-5-0">
                Recommended Jobs
            </menu>
        </div>
</div>
<?php endif;?>