<?php
$this->headLink ()->prependStylesheet ( $this->basePath () . '/css/application/detail.css');
if(isset($this->jobDetail)):
$job = $this->jobDetail;
    ?>
<div class="clearfix">
<!--    <div class="bg-gray padding-10-0 clearfix border-bottom-gray">-->
<!--        <div class="col-md-12">-->
<!--            <div>-->
<!--                <a href="--><?php //echo $this->basePath() ?><!--">Home </a> <i class="glyphicon glyphicon-chevron-right"></i>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->

<br>
        <div class="w70 box-white border-radius-5 p-15">
            <header class="full-w clearfix">
                <h4 class="bold clearfix color-blue"><?php echo $job["job_name"]; ?></h4>
                <div class="col-md-6 padding-5-0">
                    <span class="col-md-12 no-padding-left"><b>LOCATION:</b> <?php echo $job["city_name"];?></span>
                    <span class="col-md-12 no-padding-left"><b>JOB TYPE:</b><?php echo $job["job_schedule"]; ?></span>
                    <span class="col-md-12 no-padding-left"><b># OF HIRING:</b> <?php echo $job["job_hiring_number"]; ?> position(s)</span>
                    <span class="col-md-12 no-padding-left"><b>SALARY:</b> <?php echo "$".$job["job_salary_from"] ." - " ."$".$job["job_salary_to"]; ?></span>
                </div>
                <div class="col-md-6 text-right">
                    <h4 class=""><?php echo $job["com_name"]; ?></h4>
                </div>
            </header>

            <div>
                <h4 class="padding-10-0 margin-10-0 border-bottom-gray">COMPANY PROFILE</h4>
                <div>
                    <?php echo $job["com_info"]; ?>
                </div>
                <br><br>
                <h4 class="padding-10-0 margin-10-0 border-bottom-gray">RESPONSIBILITIES</h4>
                <details>
                    <?php echo $job["job_duty"] ?>
                </details>
                <br><br>
                <h4 class="padding-10-0 margin-10-0 border-bottom-gray">REQUIREMENTS</h4>
                <details>
                    <?php echo $job["job_requirement"]; ?>
                </details>
            </div>
            <br><br>
            <h4 class="padding-10-0 margin-10-0 border-bottom-gray color-yellow">HOW TO APPLY</h4>
            <p class="more-text-area">
                <b>Phone</b>: Call between 9:00 ~ 16:00 Monday ~ Friday<br>
                <b>Contact Person:</b> Kakvei<br>
                <b>Phone:</b> 063-964-206, 088-592-0392<br>
                <b>Email:</b> recruit@skyrivers.net<br>
                <b>Address:</b> T40 Borey Prem Prey, Sang kat Kouk chork, Siem Reap<br>
                <b>Website:</b>http://www.skyrivers.net/</p>
            </p>

        </div>
        <div class="w30 box-white border-radius-5 p-15">
            <menu class="no-padding border-bottom-gray font-16 padding-5-0 no-margin">
                Related Jobs
            </menu>
            <ul class="padding-10-0">
                <li class="text-overflow"><a class="pull-left">Branch Director </a>  - This is a place to display</li>
                <li class="text-overflow"><a>Maintenance Technician </a> - This is a place to display company name.</li>
                <li class="text-overflow"><a>Sale indoor 2 position </a> - This is a place to display company name.</li>
                <li class="text-overflow"><a>Assistance account </a>- This is a place to display company name.</li>
                <li class="text-overflow"><a>Cashier </a> - This is a place to display company name.</li>
                <li class="text-overflow"><a>Public Relation Manager </a> - This is a place to display company name.</li>
                <li class="text-overflow"><a>Branch Director </a> - This is a place to display company name.</li>
                <li class="text-overflow"><a>Branch Director </a> - This is a place to display company name.</li>
                <li class="text-overflow"><a>Branch Director </a> - This is a place to display company name.</li>
                <li class="text-overflow"><a>Branch Director </a>- This is a place to display company name.</li>
                <li class="text-overflow"><a>Assistance account </a>- This is a place to display company name.</li>
            </ul>


            <menu class="no-padding border-bottom-gray font-16 padding-5-0">
                Recommended Jobs
            </menu>
        </div>
</div>
<?php endif;?>