<?php
/**
 * Created by PhpStorm.
 * User: dimang12
 * Date: 11/21/14
 * Time: 8:01 PM
 */
//$this->headLink ()->prependStylesheet ( $this->basePath () . '/css/jquery-ui.css');
?>

<div class="frm">
    <h3 class="margin-10-0 border-bottom-gray padding-10-0">Education
        <span class="label label-danger pull-right font-14 margin-top-10 hidden sms-fail"> Update fail.</span>
        <i class="loading pull-right margin-top-10 hidden"></i>
    </h3>
    <div>
        <div class="clearfix">
            <div class="col-md-12 form-group">
                <label>Education Detail:</label>
                <textarea class="form-control"></textarea>
            </div>
        </div>

        <div class="clearfix text-center">
            <a href="<?php echo $this->basepath()?>/resume" class="btn btn-danger"> <i class="glyphicon glyphicon-remove-sign"></i> Cancel</a>
            <button class="btn btn-info btn-update"> <i class="glyphicon glyphicon-floppy-disk"></i> Save Education</button>
        </div>
    </div>
</div>
<script>
    var general = <?php if(count($this->general)>0) echo json_encode($this->general); else echo '[]'?>;
    var baseUrl = '<?php echo $this->basepath(); ?>';
    $(function(){
        setValueToField(general, '.frm');
        $('.btn-update').on('click', function () {
            $('.loading').removeClass('hidden');
            $('.sms-fail').addClass('hidden');
            $.ajax({
                url: baseUrl + '/resume/updatecareer',
                data: getValueFromField('.frm'),
                type:'post',
                success: function(){
                    $('.loading').addClass('hidden');
                    window.location.href = baseUrl + '/resume'
                },
                error: function(){
                    $('.loading').addClass('hidden');
                    $('.sms-fail').removeClass('hidden');
                }
            });
        });

        $('.form-control.dob ').datepicker({dateFormat:'yy-mm-dd'});
    });
</script>